### ISSUE TITLE
Error in pikaur -Syu

### ISSUE THREAD

**Issue by XavierCLL** [actionless/pikaur#11]
First, thanks for the amazing alternative to pacaur and yaourt, the error is:

$ pikaur -Syu                                                                                            
[sudo] password for xavier: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 herecura is up to date
 home_pbek_QOwnNotes_Arch_Extra is up to date
 arch4edu is up to date
 archlinuxcn is up to date
:: Starting full system upgrade...
Reading repository package databases............................................................................................................
:: Starting full AUR upgrade...
Reading local package database..................................................................................................................
Traceback (most recent call last):
  File "/home/xavier/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur.py", line 8, in <module>
  File "/home/xavier/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 244, in main
  File "/home/xavier/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 196, in cli_entry_point
  File "/home/xavier/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 79, in cli_upgrade_packages
  File "/home/xavier/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/meta_package.py", line 212, in exclude_ignored_packages
  File "/home/xavier/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/core.py", line 314, in get
  File "/home/xavier/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/core.py", line 308, in get_config
  File "/usr/lib/python3.6/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<string>' [line 42]: option 'server' in section 'all' already exists

**Comment by actionless** [comment]
thanks for reporting!
