### ISSUE TITLE
Fail to install packages with `--needed`

### ISSUE THREAD

**Issue by AlexWayfer** [actionless/pikaur#142]
```
$ pikaur -S atom
Reading local package database...

:: Repository package will be installed:
 atom                                                      -> 1.25.1-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>>

$ pikaur -S --needed atom
Reading local package database...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 261, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 212, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 98, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 134, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 138, in install_packages
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 241, in get_all_packages_info
    self.exlude_already_uptodate()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 229, in exlude_already_uptodate
    print_package_uptodate(package_name, PackageSource.REPO)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 92, in print_package_uptodate
    PackageDB.get_local_dict()[package_name].version
KeyError: 'atom'
```

**Comment by actionless** [comment]
is it the same problem as it was in https://github.com/actionless/pikaur/issues/141?

**Comment by actionless** [comment]
if so -- i guess i'll need to issue a minor release on the stable branch

**Comment by AlexWayfer** [comment]
> is it the same problem as it was in #141?

Yes, there are the same line numbers, sorry.

> if so -- i guess i'll need to issue a minor release

As you wish. Work-around: using `pacman` for not-AUR package, or another AUR-helper for AUR-package.

**Comment by actionless** [comment]
i've tagged 0.10.1
