### ISSUE TITLE
FileExistsError: [Errno 17]

### ISSUE THREAD

**Issue by ckotte** [actionless/pikaur#164]
I get the above mentioned error and pikaur crashes if I use --keepbuild. It works if I delete the src directory, but it fails the next time. 

I want to avoid a git clone every time I want to do a system upgrade. --keepbuild is the right parameter for this, right? 

```
# pikaur -Syu --devel --needed --keepbuild
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full AUR upgrade...
Reading local package database...
Reading repository package databases...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    js    
    libcloudproviders    
Resolving AUR dependencies...

:: AUR packages will be installed:
 gnome-shell-extension-caffeine-git    r148.d7bc1ab-1      -> devel (108 days old)
 gnome-shell-extension-shelltile-git   0+39+gd221a6d-1     -> devel (49 days old)
 gnome-shell-extension-weather-git     1:r589.ea2d56a-1    -> devel (18 days old)
 gtk-arc-flatabulous-theme-git         20180201.r5.g96fb133-1 -> devel (36 days old)
 macchiato-git                         20170604-1          -> devel (44 days old)
 materia-theme-git                     r668.df19037-1      -> devel (18 days old)
 numix-circle-arc-icons-git            9.3-1               -> devel (143 days old)
 numix-circle-icon-theme-git           0.r23.be25c10-1     -> devel (30 days old)
 numix-icon-theme-git                  0.r1976.763489fcf-1 -> devel (30 days old)
 pikaur-git                            0.10.1+47+gd2452f9-1 -> devel
 powerstat-git                         0.02.15.r0.gbb31d9f-1 -> devel (66 days old)
 rhythmbox-plugin-alternative-toolbar-git 0.r357.1d3e263-1    -> devel (39 days old)
 wat-git                               r25.1302640-1       -> devel (106 days old)

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> y
looking for conflicting packages...
:: Downloading the latest sources for a devel package wat-git...
:: Downloading the latest sources for a devel package gnome-shell-extension-caffeine-git...
:: Downloading the latest sources for a devel package gtk-arc-flatabulous-theme-git...
:: Downloading the latest sources for a devel package macchiato-git...
:: Downloading the latest sources for a devel package numix-circle-arc-icons-git...
:: Downloading the latest sources for a devel package materia-theme-git...
:: Downloading the latest sources for a devel package gnome-shell-extension-shelltile-git...
:: Downloading the latest sources for a devel package pikaur-git...
:: Downloading the latest sources for a devel package rhythmbox-plugin-alternative-toolbar-git...
:: Downloading the latest sources for a devel package powerstat-git...
:: Downloading the latest sources for a devel package numix-circle-icon-theme-git...
:: Downloading the latest sources for a devel package gnome-shell-extension-weather-git...
:: Downloading the latest sources for a devel package numix-icon-theme-git...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 289, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 212, in cli_entry_point
    cli_upgrade_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 123, in cli_upgrade_packages
    packages=args.positional,
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 105, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 171, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 183, in install_packages
    self.review_build_files()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 714, in review_build_files
    self._preload_latest_sources()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 710, in _preload_latest_sources
    thread.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 180, in version_already_installed
    self.prepare_build_destination()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 341, in prepare_build_destination
    copy_tree(self.repo_path, self.build_dir)
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 229, in just_copy_damn_tree
    copy_tree(from_path, to_path, preserve_symlinks=True)
  File "/usr/lib/python3.6/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python3.6/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python3.6/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  [Previous line repeated 1 more times]
  File "/usr/lib/python3.6/distutils/dir_util.py", line 152, in copy_tree
    os.symlink(link_dest, dst_name)
FileExistsError: [Errno 17] File exists: 'nm-stage01-connecting01.svg' -> '/home/arch/.cache/pikaur/build/numix-icon-theme-git/src/numix-icon-theme/Numix-Light/16/animations/nm-stage02-connecting01.svg'
```

```
# pikaur -Vq
Pikaur v0.10.1+47+gd2452f9
Pacman v5.0.2 - libalpm v10.0.2
```

**Comment by actionless** [comment]
please check if the fix helps

**Comment by ckotte** [comment]
I still have the same error:
```
...
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 234, in just_copy_damn_tree
    preserve_symlinks=True, update=True
...
```

**Comment by actionless** [comment]
are you able to reproduce the problem when running just `pikaur -S numix-icon-theme-git --keepbuild --needed ?`

**Comment by ckotte** [comment]
yes
```
# pikaur -S numix-icon-theme-git --keepbuild --needed 
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 numix-icon-theme-git                  0.r1976.763489fcf-1 -> 0.r1864.27ddab5-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> y
looking for conflicting packages...
Reading repository package databases...
:: Downloading the latest sources for a devel package numix-icon-theme-git...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 289, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 220, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 105, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 171, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 183, in install_packages
    self.review_build_files()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 714, in review_build_files
    self._preload_latest_sources()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 710, in _preload_latest_sources
    thread.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 180, in version_already_installed
    self.prepare_build_destination()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 341, in prepare_build_destination
    copy_tree(self.repo_path, self.build_dir)
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 234, in just_copy_damn_tree
    preserve_symlinks=True, update=True
  File "/usr/lib/python3.6/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python3.6/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python3.6/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  [Previous line repeated 1 more times]
  File "/usr/lib/python3.6/distutils/dir_util.py", line 152, in copy_tree
    os.symlink(link_dest, dst_name)
FileExistsError: [Errno 17] File exists: 'nm-stage01-connecting01.svg' -> '/home/arch/.cache/pikaur/build/numix-icon-theme-git/src/numix-icon-theme/Numix-Light/16/animations/nm-stage02-connecting01.svg'
```

**Comment by actionless** [comment]
weird, can't reproduce it that way

**Comment by ckotte** [comment]
I deleted the folders in aur_repos and build and now it works without failing. Thanks for checking.
