### ISSUE TITLE
pikaur -Syu --devel --help crashes

### ISSUE THREAD

**Issue by K900** [actionless/pikaur#178]
```
❯ pikaur -Syu --devel --help
Traceback (most recent call last):
  File "/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 293, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 210, in cli_entry_point
    cli_print_help(args)
  File "/usr/lib/python3.6/site-packages/pikaur/args.py", line 69, in cli_print_help
    [PikaurConfig().misc.PacmanPath, ] + args.raw,
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by actionless** [comment]
thanks for reporting!
