### ISSUE TITLE
Skipping a package due to merge conflicts crashes pikaur

### ISSUE THREAD

**Issue by aenda** [actionless/pikaur#180]
For example, I got this output on version 0.11.1:
```
➜ pikaur -Syu
[sudo] password for root: 
:: Synchronizing package databases...
 testing is up to date
 community-testing is up to date
 core is up to date
 extra is up to date
 community is up to date
:: Starting full AUR upgrade...
Reading local package database...
Reading repository package databases...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    qpdfview-git    
Resolving AUR dependencies...

:: Repository packages will be installed:
 gsm                                   1.0.17-1            -> 1.0.18-1
 linux                                 4.16.9-1            -> 4.16.10-1
 run-parts                             4.8.4-1             -> 4.8.6-1
 lm_sensors                            3.4.0-2             -> 3.4.0-3

:: AUR package will be installed:
 sway-wlroots-git                      1.0.alpha.2.r39.gc2c5a3f5-1 -> 1.0.alpha.2.r65.ga7adbf4b-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> y
Can't pull 'sway-wlroots-git' in '/home/gmend/.cache/pikaur/aur_repos/sway-wlroots-git' from AUR:
Updating 1675a41..8c9b6ae

From https://aur.archlinux.org/sway-wlroots-git
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        .SRCINFO
        PKGBUILD
Please commit your changes or stash them before you merge.
Aborting

:: Try recovering?
[c] git checkout -- '*'
[r] remove dir and clone again
[s] skip this package
[a] abort
> s
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 629, in get_package_builds
    clone_aur_repos(self.all_aur_packages_names)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 507, in clone_aur_repos
    result=result
pikaur.exceptions.CloneError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 293, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 216, in cli_entry_point
    cli_upgrade_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 127, in cli_upgrade_packages
    packages=args.positional,
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 109, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 183, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 190, in install_packages
    self.get_package_builds()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 667, in get_package_builds
    self.discard_aur_package(skip_pkg_name)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 609, in discard_aur_package
    pkg_build = self.package_builds_by_name.get(pkg_name)
AttributeError: 'InstallPackagesCLI' object has no attribute 'package_builds_by_name'
```

**Comment by actionless** [comment]
thanks for reporting1
