### ISSUE TITLE
pacman 5.1.0 incompatible

### ISSUE THREAD

**Issue by cg505** [actionless/pikaur#184]
From the NEWS file of pacman 5.1.0, released last night: "makepkg --packagelist now lists the built filenames, rather than all possible basenames without extensions".

This breaks pikaur's logic for calculating the built package files to copy/move. Here is a log (the same thing occurs with any package):

```
$ pikaur -S package-query                                                                                                                                                               
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 package-query                         1.9-2               -> 1.9-3

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>>  y
looking for conflicting packages...
Reading repository package databases...
Do you want to edit PKGBUILD for package-query package? [Y/n]  n

==> Making package: package-query 1.9-3 (Mon 28 May 2018 08:56:11 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading package-query-1.9.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  357k  100  357k    0     0   338k      0  0:00:01  0:00:01 --:--:--  338k
==> Validating source files with sha256sums...
    package-query-1.9.tar.gz ... Passed
==> Extracting sources...
  -> Extracting package-query-1.9.tar.gz with bsdtar
==> Starting build()...
[snip successful build]
==> Entering fakeroot environment...
==> Starting package()...
[snip successful package]
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "package-query"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: package-query 1.9-3 (Mon 28 May 2018 08:56:21 PM EDT)

Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cooperc/.cache/pikaur/build/package-query/package-query-1.9-3-x86_64.pkg.tar.pkg.tar' -> '/home/cooperc/.cache/pikaur/pkg/package-query-1.9-3-x86_64.pkg.tar.pkg.tar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 293, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 224, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 109, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 188, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 210, in install_packages
    self.build_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 846, in build_packages
    repo_status.build(self.package_builds_by_name)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 478, in build
    self._set_built_package_path()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 327, in _set_built_package_path
    shutil.move(built_package_path, PACKAGE_CACHE_PATH)
  File "/usr/lib/python3.6/shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cooperc/.cache/pikaur/build/package-query/package-query-1.9-3-x86_64.pkg.tar.pkg.tar'
```

Downgrading pacman and pyalpm resolves the issue.

**Comment by cg505** [comment]
The new packages were only moved from testing to core 3 hours ago. It's likely that most people have not yet upgraded, so it may be a good idea to warn people somehow.

**Comment by bertptrs** [comment]
The cause is the function `_set_built_package_path`. It attempts to get the package names and construct the filenames from them.

The package names are queried by running `makepkg --packagelist`, but those names already include a pkgext, causing a duplicate pkgext when moving the file.

The fix is not exactly trivial, as those names are first checked whether they end with `-any`.

It appears to be an upstream bug too, since `makepkg --packagelist` is documented to _not_ produce PKGEXT.

**Comment by ShapeShifter499** [comment]
This appears to be the same issue I have #185 I just switched to using pikaur from yaourt a few moments ago.

**Comment by cg505** [comment]
One awkward consequence of this is that if a user tries to upgrade pikaur and pacman at the same time, pacman is actually upgraded first, so the pikaur build/install will fail. Subsequent `pikaur -Syu`s will also fail, because pikaur hasn't been updating and can't successfully update itself. Unfortunately I don't think there is anything we can do about this, except maybe warn in the pikaur documentation that manual intervention is required.

**Comment by actionless** [comment]
i was thinking of adding that into FAQ section but if somebody would go so far then the one would also discover one of the issues filed about that

**Comment by cg505** [comment]
So what is the recommended fix when this occurs? The only thing that seems to consistently work for me is to just manually build the newly released pikaur.

**Comment by Morganamilo** [comment]
I would say building with makepkg should be the suggested way.
