### ISSUE TITLE
"No such file error", pikaur name error.

### ISSUE THREAD

**Issue by ShapeShifter499** [actionless/pikaur#185]
I'm getting the following error.  It seems to be tacking on a extra ".pkg.tar" to the end of the actual name of the package.  In this case the package is built and appears at "/home/alarm/.cache/pikaur/build/mergerfs-tools-git/mergerfs-tools-git-r71.9b4fe00-1-any.pkg.tar"

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alarm/.cache/pikaur/build/mergerfs-tools-git/mergerfs-tools-git-r71.9b4fe00-1-any.pkg.tar.pkg.tar' -> '/home/alarm/.cache/pikaur/pkg/mergerfs-tools-git-r71.9b4fe00-1-any.pkg.tar.pkg.tar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 293, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 216, in cli_entry_point
    cli_upgrade_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 127, in cli_upgrade_packages
    packages=args.positional,
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 109, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 188, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 210, in install_packages
    self.build_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 846, in build_packages
    repo_status.build(self.package_builds_by_name)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 478, in build
    self._set_built_package_path()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 327, in _set_built_package_path
    shutil.move(built_package_path, PACKAGE_CACHE_PATH)
  File "/usr/lib/python3.6/shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alarm/.cache/pikaur/build/mergerfs-tools-git/mergerfs-tools-git-r71.9b4fe00-1-any.pkg.tar.pkg.tar'
```

```
[alarm@kumo ~]$ pikaur --version

      /:}               _
     /--1             / :}
    /   |           / `-/
   |  ,  --------  /   /
   |'                 Y      Pikaur v0.11.2
  /                   l      (C) 2018 Pikaur development team
  l  /       \        l      Licensed under GPLv3
  j  ●   .   ●        l
 { )  ._,.__,   , -.  {      Pacman v5.1.0 - libalpm v11.0.0
  У    \  _/     ._/   \

[alarm@kumo ~]$ 
```

**Comment by ShapeShifter499** [comment]
I think this might be a duplicate of #184 if so please close this one.    I just switched to using pikaur from yaourt so I wasn't sure.

**Comment by ShapeShifter499** [comment]
Thank you for the fix, it works now.

**Comment by actionless** [comment]
thanks for reporting!
