### ISSUE TITLE
Exception while building package

### ISSUE THREAD

**Issue by arashm** [actionless/pikaur#188]
When trying to install `ttf-fantasque-sans-mono` package from AUR, pikaur throws an error:

```
==> Making package: fantasque-sans-mono 1.7.2-1 (Wed 30 May 2018 04:26:07 PM +0430)                                                                                                            
==> Checking runtime dependencies...                                                                                                                                                           
==> Checking buildtime dependencies...                                                                                                                                                         
==> Retrieving sources...                                                                                                                                                                      
  -> Downloading fantasque-sans-mono-1.7.2.tar.gz...                                                                                                                                           
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                                  
100   621    0   621    0     0    241      0 --:--:--  0:00:02 --:--:--   241                                                                                                                 
100 1800k  100 1800k    0     0   109k      0  0:00:16  0:00:16 --:--:--  266k                                                                                                                 
==> Validating source files with sha512sums...                                                                                                                                                 
    fantasque-sans-mono-1.7.2.tar.gz ... Passed                                                                                                                                                
==> Extracting sources...                                                                                                                                                                      
  -> Extracting fantasque-sans-mono-1.7.2.tar.gz with bsdtar                                                                                                                                   
==> Entering fakeroot environment...                                                                                                                                                           
==> Starting package_otf-fantasque-sans-mono()...                                                                                                                                              
==> Tidying install...                                                                                                                                                                         
  -> Removing libtool files...                                                                                                                                                                 
  -> Purging unwanted files...                                                                                                                                                                 
  -> Removing static library files...                                                                                                                                                          
  -> Stripping unneeded symbols from binaries and libraries...                                                                                                                                 
  -> Compressing man and info pages...                                                                                                                                                         
==> Checking for packaging issues...                                                                                                                                                           
==> Creating package "otf-fantasque-sans-mono"...                                                                                                                                              
  -> Generating .PKGINFO file...                                                                                                                                                               
  -> Generating .BUILDINFO file...                                                                                                                                                             
  -> Generating .MTREE file...                                                                                                                                                                 
  -> Compressing package...                                                                                                                                                                    
==> Starting package_ttf-fantasque-sans-mono()...                                                                                                                                              
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "ttf-fantasque-sans-mono"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: fantasque-sans-mono 1.7.2-1 (Wed 30 May 2018 04:26:25 PM +0430)

Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'ttf-fantasque-sans-mono-1.7.2-1-any.pkg.tar.xz' -> '/home/arashm/.cache/pikaur/pkg/ttf-fantasque-sans-mono-1.7.2-1-any.pkg.tar.xz'   

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 293, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 224, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 109, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 188, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 210, in install_packages
    self.build_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 846, in build_packages
    repo_status.build(self.package_builds_by_name)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 479, in build
    self._set_built_package_path()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 326, in _set_built_package_path                                                                                               
    shutil.move(pkg_path, PACKAGE_CACHE_PATH)
  File "/usr/lib/python3.6/shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'ttf-fantasque-sans-mono-1.7.2-1-any.pkg.tar.xz'                                                                                      
```

I think the reason is the downloaded package name is `fantasque-sans-mono` maybe.

**Comment by actionless** [comment]
i think that's related to pacman update to 5.1: #184

you need to re-install pikaur manually

**Comment by arashm** [comment]
I actually installed pikaur manually this morning, which for sure was after updating pacman, yesterday.

**Comment by actionless** [comment]
thanks for reporting!
