### ISSUE TITLE
[v0.5] crash in full AUR upgrade

### ISSUE THREAD

**Issue by hazzl** [actionless/pikaur#19]
Hi there,

when I try to do a full system update, pikaur crashes with the following error:

```
hazzl@eressea:~$ pikaur -Suy
:: Synchronisiere Paketdatenbanken...
 testing ist aktuell
 core ist aktuell
 extra ist aktuell
 community-testing ist aktuell
 community ist aktuell
 multilib-testing ist aktuell
 multilib ist aktuell
:: Starting full system upgrade...
Reading repository package databases............................................
:: Starting full AUR upgrade...
Reading local package database..................................................
Traceback (most recent call last):
  File "/home/hazzl/tmp/pikaur-git/src/pikaur-git/pikaur.py", line 8, in <module>
  File "/home/hazzl/tmp/pikaur-git/src/pikaur-git/pikaur/main.py", line 244, in main
  File "/home/hazzl/tmp/pikaur-git/src/pikaur-git/pikaur/main.py", line 196, in cli_entry_point
  File "/home/hazzl/tmp/pikaur-git/src/pikaur-git/pikaur/main.py", line 79, in cli_upgrade_packages
  File "/home/hazzl/tmp/pikaur-git/src/pikaur-git/pikaur/meta_package.py", line 212, in exclude_ignored_packages
  File "/home/hazzl/tmp/pikaur-git/src/pikaur-git/pikaur/core.py", line 325, in get
AttributeError: 'list' object has no attribute 'split'
```

**Comment by actionless** [comment]
i think it's fixed already (will be in released as 0.6)
could you try `pikaur -S pikaur-git ; pikaur -Suy` ?
