### ISSUE TITLE
Cannot `pikaur -Su`: KeyError: '\x1b[1;34m::\x1b[0;1m Starting full system upgrade...'

### ISSUE THREAD

**Issue by ohjames** [actionless/pikaur#213]
Here's the full output:

```
% pikaur -Su 
:: Starting full AUR upgrade...
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Reading repository package databases...                                                                                                            
Reading local package database...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 283, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 204, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 110, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 207, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 366, in install_packages
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 470, in get_all_packages_info
    self.get_repo_pkgs_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 559, in get_repo_pkgs_info
    for pkg_update in self._get_repo_pkgs_info(extra_args=self.args.positional):
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 545, in _get_repo_pkgs_info
    pkg = repo_pkgs[line]
KeyError: '\x1b[1;34m::\x1b[0;1m Starting full system upgrade...'
```

Everything on the system is fully up to date, including `pikaur` itself. Maybe a few aur packages besides `pikaur` need to be upgraded though.

**Comment by ohjames** [comment]
Weird my system still had pacman 5.0 despite the db claiming it had pacman 5.1. Not sure how it got into that state. I reinstalled pacman and it works now.
