### ISSUE TITLE
Cannot update/install transmission-sequential-gtk

### ISSUE THREAD

**Issue by carpikes** [actionless/pikaur#221]
Hi, I'm trying to update `transmission-sequential-gtk`. Everything is working smoothly using `yaourt`. Instead if I try to install it using `pikaur` I get this:
```
pikaur -S transmission-sequential-gtk
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 transmission-sequential-gtk           2.93-1               -> 2.94-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> v

:: AUR package will be installed:
 transmission-sequential-gtk           2.93-1               -> 2.94-1
    Fast, easy, and free BitTorrent client (GTK+ GUI) (+sequential patch)    

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> y
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 277, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 198, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 109, in cli_install_packages
    InstallPackagesCLI(args=args)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 154, in __init__
    self.get_package_builds()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 373, in get_package_builds
    clone_aur_repos(self.all_aur_packages_names)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 506, in clone_aur_repos
    build=package_builds_by_name[package_name],
KeyError: 'transmission-sequential'
```

**Comment by actionless** [comment]
it works for me, which version of pikaur do you use?

**Comment by carpikes** [comment]
Hi! I'm using pikaur 0.14.4(-1), the last one available on AUR.

**Comment by actionless** [comment]
and can you reproduce it with `pikaur-git`?

**Comment by carpikes** [comment]
Yes, exactly the same:
```
~ $ pikaur -S transmission-sequential-gtk
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 transmission-sequential-gtk           2.94-1               -> 2.94-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 277, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 198, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 109, in cli_install_packages
    InstallPackagesCLI(args=args)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 154, in __init__
    self.get_package_builds()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 373, in get_package_builds
    clone_aur_repos(self.all_aur_packages_names)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 533, in clone_aur_repos
    build=package_builds_by_name[package_name],
KeyError: 'transmission-sequential'
~ $ pikaur --version                     

      /:}               _
     /--1             / :}
    /   |           / `-/
   |  ,  --------  /   /
   |'                 Y      Pikaur v0.14.4.r24.g42c8458
  /                   l      (C) 2018 Pikaur development team
  l  /       \        l      Licensed under GPLv3
  j  ●   .   ●        l
 { )  ._,.__,   , -.  {      Pacman v5.1.0 - libalpm v11.0.0
  У    \  _/     ._/   \
```

**Comment by actionless** [comment]
please update `pikaur-git` and see the updated error message

**Comment by carpikes** [comment]
It works now, and I have no idea why.. ¯\_(ツ)_/¯
I have successfully installed transmission-sequential-* with pikaur v0.14.4.r25.gc23bf10

Thank you.

**Comment by actionless** [comment]
mb you was out of free sidk space to clone the repo or smth else -- the problem was what pikaur was crashing while trying to write a message about git clone error
