### ISSUE TITLE
Cannot upgrade virtualbox-ck-host-modules

### ISSUE THREAD

**Issue by SpineEyE** [actionless/pikaur#229]
```
$ pikaur -Syu virtualbox-ck-host-modules
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 309, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 229, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 140, in cli_install_packages
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 134, in cli_install_packages
    install_packages_thread.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 129, in <lambda>
    install_packages_thread = pool.apply_async(lambda: InstallPackagesCLI(args=args))
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 147, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 199, in get_all_packages_info
    manually_excluded_packages_names=self.manually_excluded_packages_names,
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 44, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 102, in get_all_packages_info
    self.get_aur_deps_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 292, in get_aur_deps_info
    self.aur_deps_relations = find_aur_deps(all_aur_packages_names)
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 234, in find_aur_deps
    results = request.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 132, in find_missing_deps_for_aur_pkg
    source=PackageSource.LOCAL
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 101, in check_deps_versions
    del deps[dep_name]
KeyError: 'linux-ck'
```

**Comment by actionless** [comment]
hi, i did a fix but i think it will still fail, but with some other nicer message :-)

**Comment by SpineEyE** [comment]
Alright thanks^^ So apparently 4.17.3-1 > 4.17, so I would need to ask the package maintainer to consider this?

**Comment by Morganamilo** [comment]
You might want to consider `community/virtualbox-host-dkms` instead.

**Comment by actionless** [comment]
@SpineEyE 

i see such message when trying to just install it:
```
Version mismatch:
virtualbox-ck-host-modules depends on: 'linux-ck>=4.16,linux-ck<4.17'
 found in 'PackageSource.AUR': '4.17.3-1'
```

ie even 4.17 wouldn't match
