### ISSUE TITLE
pikaur.exceptions.PackagesNotFoundInRepo when `picaur -S kaitai-struct-visualizer `

### ISSUE THREAD

**Issue by YinTianliang** [actionless/pikaur#232]
```
> pikaur -S kaitai-struct-visualizer 
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 309, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 229, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 140, in cli_install_packages
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 134, in cli_install_packages
    install_packages_thread.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 129, in <lambda>
    install_packages_thread = pool.apply_async(lambda: InstallPackagesCLI(args=args))
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 147, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 199, in get_all_packages_info
    manually_excluded_packages_names=self.manually_excluded_packages_names,
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 44, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 102, in get_all_packages_info
    self.get_aur_deps_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 292, in get_aur_deps_info
    self.aur_deps_relations = find_aur_deps(all_aur_packages_names)
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 234, in find_aur_deps
    results = request.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 142, in find_missing_deps_for_aur_pkg
    source=PackageSource.REPO
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 49, in check_deps_versions
    version_matchers[dep_name].line.split(',')[0]
  File "/usr/lib/python3.6/site-packages/pikaur/pacman.py", line 396, in find_repo_package
    raise PackagesNotFoundInRepo(packages=[pkg_name])
pikaur.exceptions.PackagesNotFoundInRepo
```

```
> pikaur --version 

      /:}               _
     /--1             / :}
    /   |           / `-/
   |  ,  --------  /   /
   |'                 Y      Pikaur v0.14.6
  /                   l      (C) 2018 Pikaur development team
  l  /       \        l      Licensed under GPLv3
  j  ●   .   ●        l
 { )  ._,.__,   , -.  {      Pacman v5.1.0 - libalpm v11.0.0
  У    \  _/     ._/   \
```

At first I think it's a bug of `kaitai-struct-visualizer ` package, but I can install it by `yaourt -S kaitai-struct-visualizer `

**Comment by actionless** [comment]
i did a commit which should address it, please try `pikaur-git` package to test it

**Comment by YinTianliang** [comment]
`pikaur-git` doesn't crash, but still works incorrectly... (p is an alias of `proxychains -q`)
those packages should be found in AUR.
```
> p pikaur -S kaitai-struct-visualizer 
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
:: warning: Following packages cannot be found in AUR:
    错误：未找到目标：kaitai-struct-compiler    
    错误：未找到目标：ruby-kaitai-struct    
```

But `LANG=en_US.UTF-8 p pikaur -S kaitai-struct-visualizer` works well.

```
> LANG=en_US.UTF-8 p pikaur -S kaitai-struct-visualizer
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: New dependencies will be installed from repository:
 ruby (for rubygems, ruby-rdoc, kaitai-struct-visualizer, ruby-kaitai-struct)    -> 2.5.1-2
 ruby-rdoc (for kaitai-struct-visualizer, ruby-kaitai-struct)    -> 6.0.4-1
 rubygems (for ruby)                              -> 2.7.7-1

:: AUR package will be installed:
 kaitai-struct-visualizer                         -> 0.7-1

:: New dependencies will be installed from AUR:
 kaitai-struct-compiler (for kaitai-struct-visualizer)     -> 0.8-1
 ruby-kaitai-struct (for kaitai-struct-visualizer)     -> 0.8-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
```

**Comment by actionless** [comment]
what exactly locale do you use?

**Comment by YinTianliang** [comment]
I use `zh_CN.UTF-8`

**Comment by YinTianliang** [comment]
works well.
Thank you very much!

**Comment by actionless** [comment]
thanks for reporting!
