### ISSUE TITLE
Error when using a command that does not exist

### ISSUE THREAD

**Issue by TheForgetTime** [actionless/pikaur#237]
<pre>
$ pikaur  -icon-theme 
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 24, in <module>
    from .core import (
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 14, in <module>
    from .pprint import print_stderr, color_line
  File "/usr/lib/python3.6/site-packages/pikaur/pprint.py", line 14, in <module>
    _ARGS = parse_args()
  File "/usr/lib/python3.6/site-packages/pikaur/args.py", line 145, in parse_args
    parsed_args = parser.parse_pikaur_args(args)
  File "/usr/lib/python3.6/site-packages/pikaur/args.py", line 53, in parse_pikaur_args
    parsed_args, unknown_args = self.parse_known_args(raw_args)
  File "/usr/lib/python3.6/site-packages/pikaur/argparse.py", line 1784, in parse_known_args
    self.error(str(err))
  File "/usr/lib/python3.6/site-packages/pikaur/args.py", line 49, in error
    raise exc
  File "/usr/lib/python3.6/site-packages/pikaur/argparse.py", line 1777, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/site-packages/pikaur/argparse.py", line 1992, in _parse_known_args
    start_index, unknown_args = consume_optional(start_index)
  File "/usr/lib/python3.6/site-packages/pikaur/argparse.py", line 1914, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
pikaur.argparse.ArgumentError: argument -c/--clean: ignored explicit argument 'theme'
</pre>

The above is error message
----

this error when i  want remove some pacakges named *-icon-theme.
I can't use zsh's auto-completion to complete the command section before ‘-’，So I pressed the Enter key and this error appeared.

**Comment by TheForgetTime** [comment]
It seems that not only pikaur.
When I found this error, I tested this aur Helper along with yaourt, aurman, yay.
Only yaourt output normal commands do not exist instead of crashing.

It outputs:

<pre>
pacman: not applicable options -- -
</pre>

**Comment by actionless** [comment]
pikaur.argparse is actually python stdlib argparse (with one small patch) so i don't want to patch it even more, so i will just hide a stacktrace :-)

thanks for reporting!
