### ISSUE TITLE
verify dependencies pf packages non installed...

### ISSUE THREAD

**Issue by simona70** [actionless/pikaur#244]
```
pikaur -Syu

```

##### Attached log:
:: unable to satisfy dependency 'xorg-server<1.18.0' required by catalyst-utils
:: unable to satisfy dependency 'catalyst-utils' required by lib32-catalyst-utils
:: unable to satisfy dependency 'lib32-libtxc_dxtn' required by lib32-mesa-noglvnd

Traceback (most recent call last):
  File "/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 273, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 187, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 127, in cli_install_packages
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 121, in cli_install_packages
    install_packages_thread.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 116, in <lambda>
    install_packages_thread = pool.apply_async(lambda: InstallPackagesCLI(args=args))
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 153, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 211, in get_all_packages_info
    manually_excluded_packages_names=self.manually_excluded_packages_names,
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 54, in __init__
    self.replacements = find_replacements() if self.args.sysupgrade else {}
  File "/usr/lib/python3.6/site-packages/pikaur/replacements.py", line 29, in find_replacements
    PackageDB.find_repo_package(pkg_name).db.name
  File "/usr/lib/python3.6/site-packages/pikaur/pacman.py", line 433, in find_repo_package
    raise PackagesNotFoundInRepo(packages=[pkg_name])
pikaur.exceptions.PackagesNotFoundInRepo

```
pikaur -S my-precious-package


```

**Comment by actionless** [comment]
could you please share the full log including the package name?

**Comment by actionless** [comment]
with `catalyst-utils` i myself have a different error and it seems to be legit:

```
$ pikaur -S catalyst-utils
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
Version mismatch:
catalyst-utils depends on: 'xorg-server>=1.7.0,xorg-server<1.18.0'
 found in 'PackageSource.REPO': '{'xorg-server': '1.20.0-9'}'
```

**Comment by actionless** [comment]
thanks, and what about `pikaur -Qu`

also please surround the log between ```

**Comment by simona70** [comment]
[simona@simonapc1 ~]$ pikaur -Qu
Reading local package database...
Reading repository package databases...
Reading AUR packages info...

 [simona@simonapc1 ~]$

**Comment by actionless** [comment]
i did some changes to improve the error message, please install `pikaur-git` and try to `-Syu` again

**Comment by actionless** [comment]
@simona70 i did one more commit, it should fix the problem

**Comment by simona70** [comment]
Thanks very much :-)

**Comment by actionless** [comment]
so it's working fine now?
