### ISSUE TITLE
Exception when installing AUR package with sudo

### ISSUE THREAD

**Issue by lectrode** [actionless/pikaur#245]
pikaur throws the following exception when installing libc++abi with sudo. Works as expected when sudo is omitted.

```
$ pikaur -Vq
Pikaur v1.2.3.r0.g6aeedb2
Pacman v5.1.0 - libalpm v11.0.0
```

Output:
```
$ sudo pikaur -S --needed --noconfirm --mflags="--skippgpcheck,--nocheck" libc++abi
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
looking for conflicting AUR packages...
:: Skipping review of PKGBUILD for libc++abi package (--noconfirm)

Running as unit: run-u3756.service
/usr/bin/cp: target '/var/cache/pikaur/build/libc++/' is not a directory
Finished with result: exit-code
Main processes terminated with: code=exited/status=1
Service runtime: 25ms
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 342, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 253, in cli_entry_point
    cli_install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 120, in cli_install_packages
    _run_install()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 117, in _run_install
    InstallPackagesCLI()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 171, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 760, in install_packages
    self.build_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 588, in build_packages
    resolved_conflicts=self.resolved_conflicts
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 633, in build
    self.prepare_build_destination()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 422, in prepare_build_destination
    copy_aur_repo(self.repo_path, self.build_dir)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 62, in copy_aur_repo
    raise Exception(_(f"Can't copy '{from_path}' to '{to_path}'."))
Exception: Can't copy '/var/cache/pikaur/aur_repos/libc++' to '/var/cache/pikaur/build/libc++/'.
```

**Comment by actionless** [comment]
is it working with sudo but other AUR packages?

**Comment by lectrode** [comment]
Tested installing xboxdrv with a simplified command. It also crashed (updated title accordingly):

```
$ sudo pikaur -S  xboxdrv
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: New dependency will be installed from repository:
 scons (for xboxdrv)                                        -> 3.0.1-1

:: AUR package will be installed:
 xboxdrv                                                    -> 0.8.8-4

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
looking for conflicting AUR packages...
Do you want to edit PKGBUILD for xboxdrv package? [Y/n] n

Running as unit: run-u4676.service
/usr/bin/cp: target '/var/cache/pikaur/build/xboxdrv/' is not a directory
Finished with result: exit-code
Main processes terminated with: code=exited/status=1
Service runtime: 33ms
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 342, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 253, in cli_entry_point
    cli_install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 120, in cli_install_packages
    _run_install()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 117, in _run_install
    InstallPackagesCLI()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 171, in __init__
    self.install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 760, in install_packages
    self.build_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 588, in build_packages
    resolved_conflicts=self.resolved_conflicts
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 633, in build
    self.prepare_build_destination()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 422, in prepare_build_destination
    copy_aur_repo(self.repo_path, self.build_dir)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 62, in copy_aur_repo
    raise Exception(_(f"Can't copy '{from_path}' to '{to_path}'."))
Exception: Can't copy '/var/cache/pikaur/aur_repos/xboxdrv' to '/var/cache/pikaur/build/xboxdrv/'.
```

**Comment by actionless** [comment]
thanks for reporting!
