### ISSUE TITLE
AttributeError: 'PackagesNotFoundInAUR' object has no attribute 'wanted_by'

### ISSUE THREAD

**Issue by sh4nks** [actionless/pikaur#249]
When Installing 'multisystem' from the AUR I ran into following exception:

```
pikaur -Vq

Pikaur v1.2.6
Pacman v5.1.1 - libalpm v11.0.1

```

##### Attached log:

```
pikaur -S multisystem

[sudo] password for peter: 
Reading local package database...
Resolving AUR dependencies...
Reading repository package databases...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 212, in get_all_packages_info
    manually_excluded_packages_names=self.manually_excluded_packages_names,
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 55, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 117, in get_all_packages_info
    self.get_aur_deps_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_info_fetcher.py", line 342, in get_aur_deps_info
    self.aur_deps_relations = find_aur_deps(all_aur_pkgs)
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 244, in find_aur_deps
    results = request.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 182, in find_missing_deps_for_aur_pkg
    not_found_aur_deps=not_found_aur_deps,
  File "/usr/lib/python3.6/site-packages/pikaur/aur_deps.py", line 99, in handle_not_found_aur_pkgs
    wanted_by=problem_packages_names
pikaur.exceptions.PackagesNotFoundInAUR: vte wanted by gtkdialog

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 345, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 253, in cli_entry_point
    cli_install_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 135, in cli_install_packages
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 129, in cli_install_packages
    install_packages_thread.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 117, in _run_install
    InstallPackagesCLI()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 160, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 215, in get_all_packages_info
    if exc.wanted_by:
AttributeError: 'PackagesNotFoundInAUR' object has no attribute 'wanted_by'

```

**Comment by sh4nks** [comment]
Thanks for the quickfix!
