### ISSUE TITLE
pikaur -G throws exceptions

### ISSUE THREAD

**Issue by soloturn** [actionless/pikaur#255]
```
$ pikaur -G gnome
Reading repository package databases...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 343, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 240, in cli_entry_point
    cli_getpkgbuild()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 152, in cli_getpkgbuild
    repo_pkg = PackageDB.find_repo_package(pkg_name)
  File "/usr/lib/python3.6/site-packages/pikaur/pacman.py", line 476, in find_repo_package
    raise Exception(f'Failed to find "{pkg_name}" in the output: {found_pkgs}')
```

**Comment by soloturn** [comment]
```
$ pikaur -G gnome-shell
Reading repository package databases...

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 343, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 240, in cli_entry_point
    cli_getpkgbuild()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 180, in cli_getpkgbuild
    repo_pkg.name,
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 95, in interactive_spawn
    process = InteractiveSpawn(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'asp': 'asp'

```

**Comment by actionless** [comment]
thanks for reporting!

please create two issues for these next time
