### ISSUE TITLE
FileNotFoundError in copy_aur_repo

### ISSUE THREAD

**Issue by ivica-k** [actionless/pikaur#264]
```
pikaur -Vq
Pikaur v1.2.17
Pacman v5.1.1 - libalpm v11.0.1
```
##### Attached log:
Sorry for the short/poorly formatted traceback, Ansible garbled it a bit
```
File "/usr/lib/python3.7/site-packages/pikaur/build.py", line 61, in copy_aur_repo
   remove_dir(to_path)
File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 188, in remove_dir
   shutil.rmtree(dir_path)
File "/usr/lib/python3.7/shutil.py", line 476, in rmtree
   onerror(os.lstat, path, sys.exc_info())
File "/usr/lib/python3.7/shutil.py", line 474, in rmtree
   orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/private/pikaur/build/virtualbox-ext-oracle/
```

```
pikaur -S my-precious-package
##### Manual installation worked
```
Looking at the line 61 in `pikaur/build.py` I'd say that the condition is wrong

```
if result.returncode != 0:
    if not os.path.exists(to_path):
            remove_dir(to_path)
```
How can it remove a path if the path does not exist? If my logic is sound. I'd be happy to provide a PR.

A bit more info:
```
[root@archlinux ~]# pikaur -S --noconfirm --needed --overwrite networkamanager-qt pycharm-professional teamviewer jre
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
looking for conflicting AUR packages...
> /usr/lib/python3.7/site-packages/pikaur/build.py(399)prepare_build_destination()
-> copy_aur_repo(self.repo_path, self.build_dir)
(Pdb) self.repo_path
'/var/cache/pikaur/aur_repos/jre'
(Pdb) self.build_dir
'/var/cache/pikaur/build/teamviewer'
```
These two values are from two different packages, doesn't look right.

**Comment by actionless** [comment]
btw, not related to the issue, but you need to use `--overwrite` option with the value, in your case it got parsed as `--overwrite=networkmanager-qt`

**Comment by actionless** [comment]
and also try `sudo pikaur -S virtualbox-ext-oracle --debug`

(use pikaur-git aur package to have the latest git fix mentied above)

**Comment by ivica-k** [comment]
Thank you for looking into this so quickly. Here's some more info

What I ran:
```
pikaur -S --noconfirm --needed networkmanager-qt pycharm-professional teamviewer jre viber virtualbox-ext-oracle ttf-ms-fonts
```

```
[root@archlinux pikaur]# pikaur -Vq
Pikaur v1.2.18-dev
Pacman v5.1.1 - libalpm v11.0.1
```

What I got
```
(Pdb) Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 322, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 232, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 100, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 171, in __init__
    self.review_build_files()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 521, in review_build_files
    self._preload_latest_sources()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 515, in _preload_latest_sources
    thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/build.py", line 256, in version_already_installed
    self.get_latest_dev_sources()
  File "/usr/lib/python3.7/site-packages/pikaur/build.py", line 218, in get_latest_dev_sources
    self.prepare_build_destination()
  File "/usr/lib/python3.7/site-packages/pikaur/build.py", line 397, in prepare_build_destination
    copy_aur_repo(self.repo_path, self.build_dir)
  File "/usr/lib/python3.7/site-packages/pikaur/build.py", line 64, in copy_aur_repo
    result = interactive_spawn(cmd_args)
Exception: Can't copy '/var/cache/private/pikaur/aur_repos/teamviewer' to '/var/cache/private/pikaur/build/teamviewer/'.
```
But I can copy manually
```
[root@archlinux ~]# cp -r /var/cache/private/pikaur/aur_repos/teamviewer /var/cache/private/pikaur/build/teamviewer/
[root@archlinux ~]# ls /var/cache/private/pikaur/build/teamviewer/
PKGBUILD  teamviewer.install
[root@archlinux ~]# ls /var/cache/private/pikaur/aur_repos/teamviewer
PKGBUILD  teamviewer.install
```

**Comment by actionless** [comment]
please share the full log, not only the stack trace

**Comment by ivica-k** [comment]
This is the full output with `--debug`

[pikaur.txt](https://github.com/actionless/pikaur/files/2284060/pikaur.txt)

**Comment by actionless** [comment]
please try the latest `pikaur-git` aur package again and upload the log with the same args as previous

**Comment by ivica-k** [comment]
Here you go

[pikaur.txt](https://github.com/actionless/pikaur/files/2284304/pikaur.txt)

**Comment by actionless** [comment]
now we finally can see the root cause of the problem:

```
=> systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp mkdir -p /var/cache/private/pikaur/build/virtualbox-ext-oracle

Running as unit: run-u37.service
/usr/bin/mkdir: cannot create directory ‘/var/cache/private/pikaur/build/virtualbox-ext-oracle/’: Permission denied
Finished with result: exit-code
Main processes terminated with: code=exited/status=1
Service runtime: 39ms
```


can you reproduce the error when running this command manually?

**Comment by actionless** [comment]
if it works i suspect what systemd dynamic users is deadlocking when running several commands with them simultaneously

in that case you could try if it will work in one thread:

in `pikaur/install_cli.py` change 

```py
    def _get_installed_status(self) -> None:
        all_package_builds = set(self.package_builds_by_name.values())
        with ThreadPool() as pool:
```

to 

```py
    def _get_installed_status(self) -> None:
        all_package_builds = set(self.package_builds_by_name.values())
        with ThreadPool(processes=1) as pool:
```

**Comment by actionless** [comment]
but i didn't changed anything from the last time, please see my previous 2 messages

**Comment by actionless** [comment]
but it still working fine when you set `processes=1`??

please run the same command and add `--debug` flag at the end

**Comment by actionless** [comment]
oh, wait, i've re-read the log and got what is the problem

**Comment by actionless** [comment]
try now please

**Comment by lectrode** [comment]
looks good now from my testing. thanks!

**Comment by actionless** [comment]
thanks for testing!
