### ISSUE TITLE
AttributeError: 'PikspectPopen' object has no attribute '_wait'

### ISSUE THREAD

**Issue by voger** [actionless/pikaur#266]
In Manjaro I am getting this error after the latest pikaur update.

```
pikaur -Vq
Pikaur v1.2.17
Pacman v5.1.1 - libalpm v11.0.1

```

##### Attached log:
?? Where is it?
```
pikaur -Syyuu --noedit --noconfirm
[sudo] password for voger:
:: Synchronizing package databases...
 core                      147,6 KiB   642K/s 00:00 [##########################] 100%
 extra                    1811,5 KiB   567K/s 00:03 [##########################] 100%
 community                   4,8 MiB   553K/s 00:09 [##########################] 100%
 multilib                  180,0 KiB   621K/s 00:00 [##########################] 100%
 sublime-text             1080,0   B   264K/s 00:00 [##########################] 100%
 sublime-text.sig          543,0   B  0,00B/s 00:00 [##########################] 100%

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    fontconfig-enhanced-defaults
    gegl02
    libtxc_dxtn
    linux413
    linux413-ndiswrapper
    linux413-virtualbox-host-modules
    otf-cantarell-ib
    pcmciautils
    t1-urw-fonts-ib
    ttf-fantasque-sans
    xfce4-power-manager-dev
    xorg-server-utils
    xorg-utils

Error in the thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pikaur/threading.py", line 55, in decorated
    return fun(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pikaur/pikspect.py", line 160, in communicator_thread
    return self._wait(None)
AttributeError: 'PikspectPopen' object has no attribute '_wait'
:: Starting full system upgrade...
 there is nothing to do

And then it just hangs in there. I have to hit Ctrl+C to get my shell back. After that I run yaourt to get whatever updates are available from AUR.


```

**Comment by Morganamilo** [comment]
_wait is new to python 3.7.
