### ISSUE TITLE
AttributeError: 'PikspectPopen' object has no attribute '_wait

### ISSUE THREAD

**Issue by ShapeShifter499** [actionless/pikaur#267]
I'm seeing the below issue, it hangs and I have to 'ctrl-c' to escape it. 

```
pikaur -Vq
Pikaur v1.2.17
Pacman v5.1.1 - libalpm v11.0.1

```

##### Attached log:

```
[alarm@kumo ~]$ pikaur -S mergerfs-tools-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 mergerfs-tools-git                    r71.9b4fe00-1        -> r67.0138e09-2

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
Do you want to edit PKGBUILD for mergerfs-tools-git package? [y/N] n

:: Downloading the latest sources for a devel package mergerfs-tools-git...
Error in the thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pikaur/threading.py", line 55, in decorated
    return fun(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pikaur/pikspect.py", line 160, in communicator_thread
    return self._wait(None)
AttributeError: 'PikspectPopen' object has no attribute '_wait'

```

**Comment by actionless** [comment]
do you know when manjaro is going to sync python3 version with arch?

**Comment by ShapeShifter499** [comment]
I don't sorry

**Comment by actionless** [comment]
they already did
