### ISSUE TITLE
Problems with ctr+c

### ISSUE THREAD

**Issue by Morganamilo** [actionless/pikaur#281]
```
Pikaur v1.2.23.r4.g61b23f7
Pacman v5.1.1 - libalpm v11.0.1
```

Pikaur seems to have some problems with ctr+c. Firstly it completely ignores it, then when hitting continue it causes an error. Here are Two examples:

```
morganamilo@Vinyl ~ % pikaur -Su
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 vim-youcompleteme-git                 2324.00874fab-1      -> 2373.15362d9c-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 


Canceled by user (SIGINT)


Canceled by user (SIGINT)
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 301, in handle_sig_int
    sys.exit(125)
SystemExit: 125

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 301, in handle_sig_int
    sys.exit(125)
SystemExit: 125

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 322, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 235, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 265, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 259, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 651, in get
    self.wait(timeout)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 648, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 553, in wait
    return signaled
  File "/usr/lib/python3.7/threading.py", line 244, in __exit__
    return self._lock.__exit__(*args)
RuntimeError: release unlocked lock
morganamilo@Vinyl ~ % pikaur -Su
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 vim-youcompleteme-git                 2324.00874fab-1      -> 2373.15362d9c-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> //Hit ctr+c here, nothing happens prompt is still waiting for input

//This happens after hitting enter, so the ctr+c was kind of delayed
Canceled by user (SIGINT)
morganamilo@Vinyl ~ % 
```

Same as before but I actually hit ctr+c twice, then hit enter:
```
morganamilo@Vinyl ~ % pikaur -Su
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 vim-youcompleteme-git                 2324.00874fab-1      -> 2373.15362d9c-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 


Canceled by user (SIGINT)


Canceled by user (SIGINT)
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 301, in handle_sig_int
    sys.exit(125)
SystemExit: 125

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 301, in handle_sig_int
    sys.exit(125)
SystemExit: 125

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 322, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 235, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 265, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 259, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 651, in get
    self.wait(timeout)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 648, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 553, in wait
    return signaled
  File "/usr/lib/python3.7/threading.py", line 244, in __exit__
    return self._lock.__exit__(*args)
RuntimeError: release unlocked lock
```

**Comment by actionless** [comment]
please try the fix above

**Comment by Morganamilo** [comment]
Fixes the lock error but the ctr+c is still delayed

```
morganamilo@Octavia ~ % pikaur -Su          
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR packages will be installed:
 pamac-aur                             6.5.0-1              -> 6.9.0-2
 libgaminggear                         0.15.1-3             -> 0.15.1-4

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> //ctr+c twice then enter


Canceled by user (SIGINT)


Canceled by user (SIGINT)
```

**Comment by actionless** [comment]
and now?

**Comment by Morganamilo** [comment]
Yep that one fixed it.

**Comment by actionless** [comment]
thanks for helping to debug this!
