### ISSUE TITLE
Pikaur hanged when trying to search/update packages

### ISSUE THREAD

**Issue by spielkind** [actionless/pikaur#288]
```

=> pacman --version
Pikaur v1.2.25
Pacman v5.1.1 - libalpm v11.0.1

```

Pikaur hangs since today when trying to search/update packages.
Even a downgrade didn't helped.

Let me know which informations you need.

##### Attached log:

```
$> pikaur -Ss pikaur                            
Searching... [##^CTraceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 323, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 233, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.7/site-packages/pikaur/search_cli.py", line 143, in cli_search_packages
    else []
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 651, in get
    self.wait(timeout)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 648, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt


 $> pikaur -Suy                                                                                                                                             x1 
=> sudo pacman --color=always --sync --refresh
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
^CTraceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 323, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 236, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 259, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 651, in get
    self.wait(timeout)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 648, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt


```

**Update:**
A reboot fixed the problem, weird. 'yay', 'sudo' and 'pacman' worked fine.

**Comment by actionless** [comment]
it looks like network connectivity problem or some unexpected response from AUR but indeed error handling for this case is not implemented
