### ISSUE TITLE
Repos cache migration breaks invocation from root

### ISSUE THREAD

**Issue by NikitaPuzyryov** [actionless/pikaur#303]
```
$ pikaur -Vq
Pikaur v1.3.0.1
Pacman v5.1.1 - libalpm v11.0.1
```

##### Attached log:

```
# pikaur -Syu     
Traceback (most recent call last):
  File "/usr/sbin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 316, in main
    create_dirs()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 296, in create_dirs
    migrate_old_aur_repos_dir()
  File "/usr/lib/python3.7/site-packages/pikaur/config.py", line 46, in migrate_old_aur_repos_dir
    os.renames(_OLD_AUR_REPOS_CACHE_PATH, AUR_REPOS_CACHE_PATH)
  File "/usr/lib/python3.7/os.py", line 268, in renames
    rename(old, new)
OSError: [Errno 18] Invalid cross-device link: '/var/cache/pikaur/aur_repos' -> '/root/.local/share/pikaur/aur_repos'
```
IMO in case of `systemd-run`-builds migration shouldnʼt take place or should be done in a similar fashion (e.g. move to `/var/lib/pikaur`?).

**Comment by actionless** [comment]
please check with `pikaur-git`
