### ISSUE TITLE
Using PKGDEST causes errors

### ISSUE THREAD

**Issue by bertptrs** [actionless/pikaur#308]
```
pikaur -Vq
Pikaur v1.3.0.6
Pacman v5.1.1 - libalpm v11.0.1
```

Using an alternate PKGDEST causes some glitches in pikaur, most notably being unable to install any built packages. When the custom PKGDEST is removed, everything works fine.

##### [Optional] Prerequisites:
Configure a PKGDEST that is not in the default pikaur.
Ensure you do not have the package already compiled in `~/.cache/pikaur/pkg`
Build a package.

##### Attached log:

```
PKGDEST=~/.cache/pacman/pkg pikaur -S python-scikit-image
[SNIPPED]
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 328, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 238, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 257, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 251, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 100, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 152, in __init__
    self.install_packages()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 751, in install_packages
    self.install_aur_packages()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 714, in install_aur_packages
    for pkg_name in self.aur_packages_names
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 714, in <dictcomp>
    for pkg_name in self.aur_packages_names
KeyError: 'python-scikit-image'
```
Full logs are attached but quite long since they contain all of the compilation done.
[pikaur-scikit.log](https://github.com/actionless/pikaur/files/2464041/pikaur-scikit.log)

**Comment by actionless** [comment]
also please note what makepkg not expanding `~` if PKGDEST passed as env var

**Comment by actionless** [comment]
if it's still not working please upload the new log with `--debug` flag also passed to pikaur
