### ISSUE TITLE
ERROR: The package group has already been built. (use -f to overwrite)

### ISSUE THREAD

**Issue by simonbcn** [actionless/pikaur#309]
```
Pikaur v1.3.0.6
Pacman v5.1.1 - libalpm v11.0.1
```
Due a previous errors in upgrade the packages `vte-tilix-common` and `vte3-tilix`, I've tried again but:

##### Attached log:

```
$ pikaur -Syu --needed --devel
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 DEB_Arch_Extra                                                         4,2 KiB  1393K/s 00:00 [#######################################################] 100%
 DEB_Arch_Extra.sig                                                   280,0   B  0,00B/s 00:00 [#######################################################] 100%
 xenlism-arch is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: New dependency will be installed from repository:
 python-distutils-extra (for gnome-gmail)                   -> 2.39-3

:: AUR packages will be installed:
 flameshot-git                         r496.6c49a22-1       -> devel (4 days old)
 gnome-backgrounds-bitday-git          r14.9d71483-1        -> devel (14 days old)
 numix-circle-icon-theme-git           0.r32.7637f41-1      -> devel (4 days old)
 numix-icon-theme-git                  0.r1978.53daae839-1  -> devel (11 days old)
 pinta-git                             r1794.dd226b9a-1     -> devel (12 days old)
 vte-tilix-common                      0.52.2-1             -> 0.54.1-1
 vte3-tilix                            0.52.2-1             -> 0.54.1-1
 gnome-gmail                           2.5.4-1              -> 2.5.6-1
 plex-media-server-plexpass            1.13.8.5395-1        -> 1.13.9.5439-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
looking for conflicting AUR packages...
:: Downloading the latest sources for a devel package flameshot-git...
:: Downloading the latest sources for a devel package numix-icon-theme-git...
:: Downloading the latest sources for a devel package numix-circle-icon-theme-git...
:: Downloading the latest sources for a devel package pinta-git...
:: Downloading the latest sources for a devel package gnome-backgrounds-bitday-git...
:: warning: flameshot-git r496.6c49a22-1 AUR package is up to date - skipping
:: warning: pinta-git r1794.dd226b9a-1 AUR package is up to date - skipping
:: warning: numix-icon-theme-git 0.r1978.53daae839-1 AUR package is up to date - skipping
:: warning: numix-circle-icon-theme-git 0.r32.7637f41-1 AUR package is up to date - skipping
:: warning: gnome-backgrounds-bitday-git r14.9d71483-1 AUR package is up to date - skipping
:: Skipping review of PKGBUILD for plex-media-server-plexpass package (--noedit)
:: Skipping review of PKGBUILD for gnome-gmail package (--noedit)
:: Skipping review of PKGBUILD for vte-tilix-common, vte3-tilix package (--noedit)

:: Starting full system upgrade...
 there is nothing to do
Reading local package database...
Reading local package database...
Reading local package database...

:: Starting the build:
==> ERROR: The package group has already been built. (use -f to overwrite)

Command 'makepkg' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
------------------------
[s] skip building this package
[a] abort building all the packages
> d
==> ERROR: The package group has already been built. (use -f to overwrite)

Command 'makepkg' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
------------------------
[s] skip building this package
[a] abort building all the packages
> s

Can't build 'vte3-tilix'.

:: Package gnome-gmail is already built. Pass '--rebuild' flag to force the build.

:: Package plex-media-server-plexpass is already built. Pass '--rebuild' flag to force the build.

loading packages...
resolving dependencies...
looking for conflicting packages...

Package (2)                 Old Version    New Version    Net Change

gnome-gmail                 2.5.4-1        2.5.6-1          0,00 MiB
plex-media-server-plexpass  1.13.8.5395-1  1.13.9.5439-1    0,13 MiB

Total Installed Size:  208,04 MiB
Net Upgrade Size:        0,13 MiB

:: Proceed with installation? [Y/n] Y
(2/2) checking keys in keyring                                                                 [#######################################################] 100%
(2/2) checking package integrity                                                               [#######################################################] 100%
(2/2) loading package files                                                                    [#######################################################] 100%
(2/2) checking for file conflicts                                                              [#######################################################] 100%
(2/2) checking available disk space                                                            [#######################################################] 100%
:: Processing package changes...
(1/2) upgrading gnome-gmail                                                                    [#######################################################] 100%
(2/2) upgrading plex-media-server-plexpass                                                     [#######################################################] 100%
usermod: user plex is currently used by process 492
Could not change plex users home directory.
Run: sudo systemctl stop plexmediaserver ; sudo usermod -d /usr/lib/plexmediaserver plex ; sudo systemctl start plexmediaserver
:: Running post-transaction hooks...
(1/8) Cleaning pacman cache...
==> no candidate packages found for pruning
(2/8) Updating icon theme caches...
(3/8) orphans.hook
glade 3.22.1-2
gobject-introspection 1.58.0+2+g1f1dd7f4-2
gperf 3.1-1
(4/8) Reloading system manager configuration...
(5/8) Creating system user accounts...
(6/8) Creating temporary files...
(7/8) Arming ConditionNeedsUpdate...
(8/8) Updating the desktop file MIME type cache...
Failed to build following packages:
vte-tilix-common
vte3-tilix
```
In the first question I press `d` (_delete build dir and try again_) but it doesn't delete nothing because the error happens again.

If I delete manually the makepkg folder with `rm -rf /tmp/makepkg` and I try again:
```
....
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 328, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 238, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 257, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 251, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 100, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 152, in __init__
    self.install_packages()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 751, in install_packages
    self.install_aur_packages()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 714, in install_aur_packages
    for pkg_name in self.aur_packages_names
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 714, in <dictcomp>
    for pkg_name in self.aur_packages_names
KeyError: 'vte-tilix-common'

```

The error that causes packages not to be compiled/installed occurs again.
I was able to update those packages without problems using another AUR helper.

**Comment by actionless** [comment]
are you using custom PKGDEST?

**Comment by actionless** [comment]
please try with latest `pikaur`
