### ISSUE TITLE
German translation: pikaur -S aur packages and -Su failed with "KeyError: 'package' "

### ISSUE THREAD

**Issue by Novite5** [actionless/pikaur#319]
pikaur v1.3.2
pacman v5.1.1 - libalpm v11.0.1

pacman packages work well, only related to aur packages.

##### Attached log:
```
Suche nach in Konflikt stehenden AUR-Paketen...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 328, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 238, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 257, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 251, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 683, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 100, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 150, in __init__
    self.review_build_files()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 561, in review_build_files
    reason=_("installing for the first time")
KeyError: 'package'
```

BTW.  How to get more details about the errors for debugging?

**Comment by actionless** [comment]
aha, i see you're using german translation, seems like a problem is there, i'll have a look into it

in the meantime you can workaround it by pikaur as `env LC_ALL=en_US.utf-8 LANG=en_US.utf-8 LANGUAGE=en_US.utf-8 pikaur`

**Comment by actionless** [comment]
pushed a fix; you can check it with `pikaur-git`

**Comment by Novite5** [comment]
It works. Thank you very much for your work!
