### ISSUE TITLE
Verbose option fails

### ISSUE THREAD

**Issue by mi01** [actionless/pikaur#330]
```
pikaur -Vq
Pikaur v1.3.4
Pacman v5.1.1 - libalpm v11.0.1
```
I currently try to install ROS on Arch Linux and having some problems. So i tested if pikaur can give me verbose output with the -v flag. Pikaur gave me with the following error ...

##### Attached log:

```
pikaur -Sk ros-melodic-class-loader --verbose --noconfirm
[sudo] ...
Lese Repository-Paketdatenbank...
Lese lokale Paketdatenbank...
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : ros-melodic-class-loader
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 329, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 239, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 257, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 251, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 683, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 102, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 143, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 195, in get_all_packages_info
    manually_excluded_packages_names=self.manually_excluded_packages_names,
  File "/usr/lib/python3.7/site-packages/pikaur/install_info_fetcher.py", line 55, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.7/site-packages/pikaur/install_info_fetcher.py", line 106, in get_all_packages_info
    self.get_repo_pkgs_info()
  File "/usr/lib/python3.7/site-packages/pikaur/install_info_fetcher.py", line 203, in get_repo_pkgs_info
    self._get_repo_pkgs_info(pkg_lines=self.install_package_names) +
  File "/usr/lib/python3.7/site-packages/pikaur/install_info_fetcher.py", line 161, in _get_repo_pkgs_info
    pkg = all_repo_pkgs[pkg_print.full_name]
KeyError: 'Root      : /'
```

**Comment by actionless** [comment]
thanks for reporting!

**Comment by actionless** [comment]
(you can try it with `pikaur-git` AUR package)

**Comment by mi01** [comment]
Works, thx :)
