### ISSUE TITLE
Running pikaur via xargs causes it to fail with EOFError

### ISSUE THREAD

**Issue by ow97** [actionless/pikaur#35]
When running 

`xargs pikaur -S < aur_packages`

Execution fails with the following output

```
resolving dependencies...
Reading repository package databases...
Reading local package database...

:: AUR packages will be installed:
 pikaur-git                            0.6-1               -> 0.6-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
> Traceback (most recent call last):
  File "/home/oliver/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur.py", line 8, in <module>
    main()
  File "/home/oliver/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 250, in main
    cli_entry_point()
  File "/home/oliver/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 210, in cli_entry_point
    cli_install_packages(args)
  File "/home/oliver/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 59, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/home/oliver/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/install_cli.py", line 136, in __init__
    self.install_prompt()
  File "/home/oliver/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/install_cli.py", line 296, in install_prompt
    answer = _print_sysupgrade()
  File "/home/oliver/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/install_cli.py", line 285, in _print_sysupgrade
    answer = input('{} {}\n{} {}\n> '.format(
EOFError: EOF when reading a line
```

**Comment by actionless** [comment]
solution could be to use --noconfirm when there is no valid tty

however idk if it should happen automatically or user should pass explicitly --noconfirm in such case?

**Comment by actionless** [comment]
// depends on #25

**Comment by actionless** [comment]
could you check if it's working now with `--noconfirm` option passed?

**Comment by ow97** [comment]
Works like a charm :+1:
