### ISSUE TITLE
pikaur crash when install cargo with --needed specified

### ISSUE THREAD

**Issue by lectrode** [actionless/pikaur#359]
```
$ pikaur -Vq
Pikaur v1.4.r9.g277d66d
Pacman v5.1.3 - libalpm v11.0.3
```

##### Attached log:

Fail:
```
$ pikaur -S cargo --needed
Reading repository package databases...
Reading local package database...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 329, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 239, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 275, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 269, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 102, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 153, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 248, in get_all_packages_info
    print_package_uptodate(install_info.name, install_info.package_source)
  File "/usr/lib/python3.7/site-packages/pikaur/print_department.py", line 401, in print_package_uptodate
    PackageDB.get_local_dict()[package_name].version
KeyError: 'cargo'

```

No crash (remove `--needed`):
```
pikaur -S cargo
Reading repository package databases...
Reading local package database...

:: New dependency will be installed from repository:
 cargo (rust # rustup)                                     

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
```

**Comment by actionless** [comment]
and what is the current installed version and pkgname of cargo/rust/whatever?

**Comment by lectrode** [comment]
it is not currently installed. it's a build dependency for another package.

**Comment by actionless** [comment]
but do you have rust installed

**Comment by lectrode** [comment]
`rust` is not installed

**Comment by actionless** [comment]
`rustup`?

**Comment by lectrode** [comment]
```
$ pacman -Qs rust
local/ca-certificates-mozilla 3.42.1-1
    Mozilla's set of trusted CA certificates
local/dnssec-anchors 20181003-1
    DNSSEC trust anchors for the root zone
```

**Comment by actionless** [comment]
thanks for the info provided!
i'll try to dig into it tomorrow (now too sleepy already)

**Comment by actionless** [comment]
also just one more thing, could you please re-run the same command with `-v` flag, with a more verbose output?

**Comment by lectrode** [comment]
no problem. thank you for all your hard work! pikaur is awesome

**Comment by actionless** [comment]
thanks for your support :-)

**Comment by lectrode** [comment]
```
pikaur -Sv cargo --needed
[sudo] password for lectrode: 
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync cargo --print-format %r/%n
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 329, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 239, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 275, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 269, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 102, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 153, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 248, in get_all_packages_info
    print_package_uptodate(install_info.name, install_info.package_source)
  File "/usr/lib/python3.7/site-packages/pikaur/print_department.py", line 401, in print_package_uptodate
    PackageDB.get_local_dict()[package_name].version
KeyError: 'cargo'
```

**Comment by lectrode** [comment]
An easy means to always reproduce the error from a fresh install:

1. Fresh install Manjaro Xfce 18.0.4 in a VM
2. Install `pikaur-git`
```
sudo pacman -S --noconfirm yay
yay -S --noconfirm pikaur-git
```
3. run `pikaur -S --needed oomox`

**Comment by actionless** [comment]
thanks for reporting!

**Comment by lectrode** [comment]
that works! thank you!
