### ISSUE TITLE
Ctrl-D causes EOFError

### ISSUE THREAD

**Issue by cmdrkotori** [actionless/pikaur#361]
```
tux@oniichan ~> pikaur -Vq
Pikaur v1.4.1
Pacman v5.1.3 - libalpm v11.0.3

```

##### [Optional] Prerequisites:

Press Ctrl-D at a prompt. Ctrl-D inserts an EOF and is typically used to cause tui programs to quit, such as in gdb.
Possibly related to #35.

##### Attached log:

```
tux@oniichan ~> pikaur -Syuu
Reading repository package databases...
Reading local package database...
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    fonts-meta-extended    
    ttf-ddc-uchen    
Resolving AUR dependencies...

:: AUR packages will be installed:
 lib32-libbluray                       1.0.2-1              -> 1.1.0-1
 lib32-libheif                         1.3.2-2              -> 1.4.0-1
 lib32-jasper                          2.0.14-2             -> 2.0.16-1
 lib32-libgphoto2                      2.5.21-1             -> 2.5.22-1
 lib32-srt                             1.3.1-1              -> 1.3.2-1
 lib32-x264                            155.r0a84d986-3      -> 155.r0a84d986-4
 monodevelop-stable                    7.8.0.1471-1         -> 7.8.1.8-1
 phonon-qt4                            4.10.1-4             -> 4.10.2-5
 lib32-gsm                             1.0.18-1             -> 1.0.18-2
 lib32-imagemagick                     7.0.8.23-1           -> 7.0.8.34-1
 lib32-libfdk-aac                      2.0.0-1              -> 2.0.0-2
 lib32-libomxil-bellagio               0.9.3-4              -> 0.9.3-5
 lib32-openjpeg2                       2.3.0-1              -> 2.3.0-2
 ttf-iosevka                           2.2.0-1              -> 2.2.0-2

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 329, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 239, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 275, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 269, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 102, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 160, in __init__
    self.install_prompt()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 357, in install_prompt
    answer = _confirm_sysupgrade()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 347, in _confirm_sysupgrade
    answer = get_input(prompt, _('y').upper() + _('n') + _('v') + _('m'))
  File "/usr/lib/python3.7/site-packages/pikaur/prompt.py", line 89, in get_input
    answer = input(split_last_line(prompt)).lower()
EOFError

```

**Comment by actionless** [comment]
thanks for reporting!
