### ISSUE TITLE
simply doesn't work

### ISSUE THREAD

**Issue by Ghotrix** [actionless/pikaur#432]
```
pikaur -Vq
Pikaur v1.5.4
Pacman v5.2.1 - libalpm v12.0.1
```

##### Attached log:

```
pikaur -S teams-for-linux-official-bin (basically any package)
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
:: error: Can't resolve dependencies for AUR package 'teams-for-linux-official-bin':
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 398, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 308, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 288, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 282, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 123, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 147, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 195, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 55, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 117, in get_all_packages_info
    self.get_aur_deps_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 380, in get_aur_deps_info
    self.aur_deps_relations = find_aur_deps(all_aur_pkgs)
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 252, in find_aur_deps
    raise exc
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 247, in find_aur_deps
    results = request.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 168, in find_missing_deps_for_aur_pkg
    not_found_repo_pkgs = check_deps_versions(
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 21, in check_deps_versions
    deps_lines = [
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 22, in <listcomp>
    version_matchers[dep_name].line
KeyError: ''


```

**Comment by actionless** [comment]
because PKGBUILD is incorrect https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=teams-for-linux-official-bin

**Comment by Ghotrix** [comment]
how does it come that it's correct for makepkg and incorrect for pikaur?

**Comment by otakutyrant** [comment]
I encountered this situation too when I try to `pikaur -Syu`. The error is: `error: Can't resolve dependencies for AUR package 'python-hydra-core'`.

Then I manualy compiled the package with `makepkg` and it worked. Although I still encounter the dependencies error with pikaur.
