### ISSUE TITLE
Aborting AUR download / ctrl+c

### ISSUE THREAD

**Issue by felixwiemuth** [actionless/pikaur#434]
```
pikaur -Vq
Pikaur v1.5.4
Pacman v5.2.1 - libalpm v12.0.1
```
How does one properly abort pikaur in the download phase of an AUR package?
Hitting ctrl-c, even multiple times, does not work:

```
==> Retrieving sources...
  -> Downloading android-studio-ide-191.6010548-linux.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 32  738M   32  239M    0     0   685k      0  0:18:23  0:05:58  0:12:25  732k^C

Canceled by user (SIGINT)


Canceled by user (SIGINT)
$ ^C
 32  738M   32  240M    0     0   685k      0  0:18:24  0:05:59  0:12:25  707k^C
$ ^C
 32  738M   32  240M    0     0   685k      0  0:18:24  0:06:00  0:12:24  700k^C
```
The program apparently receives SIGINT but the download, and even building the package afterwards, continues.
I would expect that pikaur terminates completely, or would at least have a supported means of doing so.

Maybe related: #281

**Comment by actionless** [comment]
are you running pikaur with sudo?

**Comment by felixwiemuth** [comment]
No, as normal user and it requests the password for sudo.

Some more info, with pikaur 1.5.5 (same after upgrade to 1.5.6):
When using ctrl+c on a default repository download, it does cancel (also showing two "Canceled by user (SIGINT)" messages), whereas for an AUR download (e.g.g pikaur), it continues as described above:

```
:: Starting the build:
Running as unit: run-u989.service
==> Making package: pikaur 1.5.6-1 (2019-12-21T12:12:49 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading pikaur-1.5.6.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0   124    0     0    282      0 --:--:-- --:--:-- --:--:--   281
  0 2102k    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0^C

Canceled by user (SIGINT)


Canceled by user (SIGINT)
100 2102k  100 2102k    0     0   474k      0  0:00:04  0:00:04 --:--:--  622k
==> Validating source files with md5sums...
    pikaur-1.5.6.tar.gz ... Passed
==> Extracting sources...
  -> Extracting pikaur-1.5.6.tar.gz with bsdtar
==> Starting build()...

... (build output) ...

==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "pikaur"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: pikaur 1.5.6-1 (2019-12-21T12:13:01 CET)
```

- It stops however after the last line shown above.
- Could the line "Running as unit: run-u989.service" be an important hint?

When not aborting, the above log continues with
```
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 13.006s

loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) pikaur-1.5.6-1

Total Installed Size:  0.87 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
...
```

Here is my `pikaur.conf`:
```
[sync]
alwaysshowpkgorigin = no
develpkgsexpiration = -1
upgradesorting = versiondiff
showdownloadsize = yes

[build]
keepbuilddir = no
keepdevbuilddir = yes
skipfailedbuild = no
alwaysusedynamicusers = yes
noedit = no
donteditbydefault = no
nodiff = no
gitdiffargs = --ignore-space-change,--ignore-all-space
keepbuilddeps = no

[colors]
version = 10
versiondiffold = 11
versiondiffnew = 9

[ui]
requireenterconfirm = yes
diffpager = auto
printcommands = no
reversesearchsorting = no

[misc]
sudoloopinterval = -1
pacmanpath = pacman
aurhost = aur.archlinux.org
newsurl = https://www.archlinux.org/feeds/news/

[network]
socks5proxy = 
```
Relevant changes to default may be `alwaysusedynamicusers = yes` and `sudoloopinterval = -1`.

**Comment by actionless** [comment]
thanks for reporting, please try with `pikaur-git`

**Comment by felixwiemuth** [comment]
Unfortunately it fails when trying to install `pikaur-git`:

```
$ pikaur -Syu pikaur-git
[sudo] password for user: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 pikaur-git                                                 -> 1.5.6-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
looking for conflicting AUR packages...
:: pikaur-git and pikaur are in conflict. Remove pikaur? [y/N] y
:: Downloading the latest sources for a devel package pikaur-git...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 399, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 306, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 123, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 159, in __init__
    self.review_build_files()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 616, in review_build_files
    self._get_installed_status()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 605, in _get_installed_status
    print_local_package_newer(
  File "/usr/lib/python3.8/site-packages/pikaur/print_department.py", line 446, in print_local_package_newer
    version=bold_line(_get_local_version(package_name)),
  File "/usr/lib/python3.8/site-packages/pikaur/print_department.py", line 429, in _get_local_version
    return PackageDB.get_local_dict()[package_name].version
KeyError: 'pikaur-git'
```
Is this another issue?

**Comment by actionless** [comment]
no, i can't reproduce this, please show me `pacman -Qs pikaur`

**Comment by actionless** [comment]
also in traceback i see line 616, however as you can see from the sources, 

https://github.com/actionless/pikaur/blob/1.5.6/pikaur/install_cli.py#L612-L616

it could be executed only if pikaur is running with `--needed` or `--devel` commandline flag

**Comment by actionless** [comment]
the error is indeed reproducing if i run the same pikaur command but with adding `--needed` flag

**Comment by actionless** [comment]
also fixed that in `pikaur-git`

but you'll need to run pikaur without `--needed` flag in order to upgrade sucessfully

**Comment by felixwiemuth** [comment]
Sorry, I did not mention that I use `--needed`.
With `1f20d6c`, it works with `--needed`.

Regarding aborting, the behavior still seems a bit strange.

If I use `ctrl+c`, it asks for aborting, which is fine and works:

```
$ pikaur -Syu android-studio --rebuild
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 android-studio                        3.5.3.0-1            -> 3.5.3.0-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> Y
looking for conflicting AUR packages...
:: warning: Not showing diff for android-studio package (already reviewed)
Do you want to edit PKGBUILD for android-studio package? [y/N] y

:: Starting full system upgrade...
 there is nothing to do

:: Starting the build:
Running as unit: run-u345.service
Press ^] three times within 1s to disconnect TTY.
==> Making package: android-studio 3.5.3.0-1 (2019-12-23T13:28:43 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading android-studio-ide-191.6010548-linux.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  738M    2 16.0M    0     0  1360k      0  0:09:16  0:00:12  0:09:04 1356k^C
==> ERROR: Aborted by user! Exiting...
Finished with result: exit-code
Main processes terminated with: code=exited/status=2
Service runtime: 16.909s

Command 'systemd-run --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/android-studio sh -c trap "exit 2" INT ; makepkg --force' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
[e] edit PKGBUILD
------------------------
[s] skip building this package
[a] abort building all the packages
> s

Can't build 'android-studio'.

Failed to build following packages:
android-studio

```
However, the output could of course be better than "Command xxx failed". But that is secondary.
It is nice that a menu gives the choice of how to continue - e.g. (if that works) one could still continue building other packages.

When I use `ctrl+]`, as suggested by the output, I get the following behavior though:
```
$ pikaur -Syu android-studio --rebuild
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 android-studio                        3.5.3.0-1            -> 3.5.3.0-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> Y
looking for conflicting AUR packages...
:: warning: Not showing diff for android-studio package (already reviewed)
Do you want to edit PKGBUILD for android-studio package? [y/N] 

:: Starting full system upgrade...
 there is nothing to do

:: Starting the build:
Running as unit: run-u367.service
Press ^] three times within 1s to disconnect TTY.
==> Making package: android-studio 3.5.3.0-1 (2019-12-23T13:30:16 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading android-studio-ide-191.6010548-linux.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  738M    2 17.7M    0     0  1366k      0  0:09:13  0:00:13  0:09:00 1359kError on PTY forwarding logic: Operation canceled

Finished with result: success

loading packages...
warning: android-studio-3.5.3.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) android-studio-3.5.3.0-1

Total Installed Size:  1327.60 MiB
Net Upgrade Size:         0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                  [##################################] 100%
(1/1) checking package integrity                                [##################################] 100%
(1/1) loading package files                                     [##################################] 100%
(1/1) checking for file conflicts                               [##################################] 100%
(1/1) checking available disk space                             [##################################] 100%
:: Processing package changes...
(1/1) reinstalling android-studio                               [######----------------------------]  18%
```
I hit `ctrl+]` during download and the download cancels. However, strangely, the package still installs (probably from a cached version). This might be a special case when reinstalling, but of course it should also abort the whole process here.

**Comment by actionless** [comment]
> still seems a bit strange.

see the explanation here: https://github.com/actionless/pikaur/commit/54f5dec86ae8608f86622c4ab3952c190449c1ba#diff-9d86e312251424240088036cf597f4dcR176-R178

basically because of that, when using systemd dynamic users pikaur will see SIGINT-ed process as just failed

> I hit ctrl+] during download and the download cancels. However, strangely, the package still installs (probably from a cached version).

but systemd message says `Press ^] three times within 1s to disconnect TTY.`
disconnect means what the process continue in the background disconnecting from the terminal
