### ISSUE TITLE
Python error when upgrading packages (news.py)

### ISSUE THREAD

**Issue by bavellone** [actionless/pikaur#435]
```
pikaur -Vq

Pikaur v1.5.6
Pacman v5.2.1 - libalpm v12.0.1
```

##### Attached log:

```
pikaur -Syu

Resolving AUR dependencies...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 399, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 309, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 294, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 288, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 123, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 151, in __init__
    self.news.print_news()
  File "/usr/lib/python3.8/site-packages/pikaur/news.py", line 39, in print_news
    if self._is_new(str(child.text)):
  File "/usr/lib/python3.8/site-packages/pikaur/news.py", line 90, in _is_new
    last_seen_news_date = datetime.datetime.strptime(
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%a, %d %b %Y %H:%M:%S %z'
```

I hadn't upgraded packages for a week or two and after running pacman -Syu I then tried upgrading AUR packages with pikaur and received the error seen in the log above. I downloaded latest pikaur with git and rebuilt package but still no luck.

Let me know if there's any other info you need!

**Comment by actionless** [comment]
thanks for reporting!

please try with the latest `pikaur-git`

**Comment by bavellone** [comment]
Fixed! Thank you for all that you do!
