### ISSUE TITLE
Latest git vesion not working using  "--needed"

### ISSUE THREAD

**Issue by fleixi** [actionless/pikaur#436]
```
pikaur -Vq

Pikaur v1.5.6
Pacman v5.2.1 - libalpm v12.0.1

```
The ansible-aur module is using pikaur with the options " --noconfirm --noedit --needed" with is working since the last few days but now is creating a error.

Without the "--needed"  options it is still working but this is should be a legit option.

The last working version is 1.5.4

```
[fleixi@momo ~]$ pikaur -S --noconfirm --noedit --needed nano-syntax-highlighting-git
[sudo] password for fleixi: 
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
looking for conflicting AUR packages...
Not showing diff for nano-syntax-highlighting-git package (--noconfirm)
:: Skipping review of PKGBUILD for nano-syntax-highlighting-git package (--noedit)
:: Skipping review of nano-syntax-highlighting.install for nano-syntax-highlighting-git package (--noedit)

:: Downloading the latest sources for a devel package nano-syntax-highlighting-git...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 399, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 309, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 294, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 288, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 123, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 871, in install_packages
    self.build_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 695, in build_packages
    self._get_installed_status()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 605, in _get_installed_status
    print_local_package_newer(
  File "/usr/lib/python3.8/site-packages/pikaur/print_department.py", line 446, in print_local_package_newer
    version=bold_line(_get_local_version(package_name)),
  File "/usr/lib/python3.8/site-packages/pikaur/print_department.py", line 429, in _get_local_version
    return PackageDB.get_local_dict()[package_name].version
KeyError: 'nano-syntax-highlighting-git'

[fleixi@momo ~]$ pikaur -S nano-syntax-highlighting-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 nano-syntax-highlighting-git                               -> 2019.10.17.r8.g6bee1b2-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
:: warning: Not showing diff for nano-syntax-highlighting-git package (already reviewed)
Do you want to edit PKGBUILD for nano-syntax-highlighting-git package? [y/N] n
Do you want to edit nano-syntax-highlighting.install for nano-syntax-highlighting-git package? [y/N] n

:: Downloading the latest sources for a devel package nano-syntax-highlighting-git...

:: Starting the build:
==> Making package: nano-syntax-highlighting-git 2019.10.17.r27.g8a999dd-1 (Tue 24 Dec 2019 12:24:24 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating nano-syntax-highlighting git repo...
Fetching origin
==> Validating source files with md5sums...
    nano-syntax-highlighting ... Skipped
==> Extracting sources...
  -> Creating working copy of nano-syntax-highlighting git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> Starting build()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "nano-syntax-highlighting-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: nano-syntax-highlighting-git 2019.10.17.r27.g8a999dd-1 (Tue 24 Dec 2019 12:24:27 PM CET)

loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) nano-syntax-highlighting-git-2019.10.17.r27.g8a999dd-1

Total Installed Size:  0.14 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                          [###################################################] 100%
(1/1) checking package integrity                                                        [###################################################] 100%
(1/1) loading package files                                                             [###################################################] 100%
(1/1) checking for file conflicts                                                       [###################################################] 100%
(1/1) checking available disk space                                                     [###################################################] 100%
:: Processing package changes...
(1/1) installing nano-syntax-highlighting-git                                           [###################################################] 100%

==> IMPORTANT!!!
==> To prevent overwriting your existing configuration, nanorc
==> was installed to /usr/share/nano-syntax-highlighting/nanorc.sample
==>
==> To install you should add the languages you want to your nano configuration file, system-wide or user-specific
==> system-wide: $ echo "include /usr/share/nano-syntax-highlighting/*.nanorc" >> /etc/nanorc
==> user-specific: $ echo "include /usr/share/nano-syntax-highlighting/*.nanorc" >> ~/.nanorc

:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

```

**Comment by actionless** [comment]
> pikaur -Vq
> Pikaur v1.5.6

latest git version would print:

```
$ pikaur -Vq
Pikaur v1.5.6.r9.g9e024b9
```

**Comment by actionless** [comment]
is already fixed in https://github.com/actionless/pikaur/commit/1f20d6c7e26f48b5ff23c55d7cb8fc05b4d96e38
