### ISSUE TITLE
pikaur fails in dockers when using sudo pikaur -S x

### ISSUE THREAD

**Issue by DreamingRaven** [actionless/pikaur#438]
```
pikaur -Vq

Pikaur v1.5.8
Pacman v5.2.1 - libalpm v12.0.1

```
Pikaur fails inside docker containers if using sudo, but not when running without sudo.

##### [Optional] Prerequisites:

Pikaur will fail inside containers when installing any package if using sudo. This can be recreated by creating the following ``Dockerfile`` then in the same directory running ``sudo docker build -t archer/pikaur .`` to generate the error.
```
FROM archlinux:latest

# variable for user username to use in the container
ARG user_name=archie

# variable for user password to use in the container
ARG user_password=archer

# creating basic gpu capable archlinux system with user and python
RUN pacman -Syyuu sudo nvidia git base-devel python python-pip pyalpm --noconfirm && \
    useradd -m -p $(openssl passwd -1 ${user_password}) ${user_name} && \
    echo "${user_name} ALL=(ALL) ALL" >> /etc/sudoers

# swapping to our newly created user
USER ${user_name}

# clone, build, and install pikaur
RUN mkdir ~/git && \
    cd ~/git && \
    git clone "https://aur.archlinux.org/pikaur.git" && \
    cd ~/git/pikaur && \
    echo "${user_password}" | makepkg -s --noconfirm && \
    echo "${user_password}" | sudo -S pacman -U *pkg.tar.xz --noconfirm

# attempt to install any package in our case python-tensorflow-cuda
RUN echo "${user_password}" | sudo -S pikaur -S python-tensorflow-cuda --noconfirm
```

##### Attached log:

Inside docker as user with password user_password for one line invocation
```
echo "${user_password}" | sudo -S pikaur -S htop --noconfirm

Traceback (most recent call last):
  File "/usr/sbin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 389, in main
    create_dirs()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 361, in create_dirs
    raise Exception(result)
Exception: InteractiveSpawn returned 1:
STDOUT:


STDERR:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
```

I have also compared running without sudo interactively by using this ``Dockerfile`` included after this paragraph instead, running ``sudo docker build -t archer/pikaur .`` to build the container and then `` sudo docker run -it archer/pikaur bash`` to run the container interactiveley so I could issue the command ``pikaur -S python-tensorflow-cuda`` which runs successfully: 

```FROM archlinux:latest

# variable for user username to use in the container
ARG user_name=archie

# variable for user password to use in the container
ARG user_password=archer

# variable for which branch to use of nemesyst when installing it
# ARG branch=master

# creating basic gpu capable archlinux system with user and python
RUN pacman -Syyuu sudo nvidia git base-devel python python-pip pyalpm --noconfirm && \
    useradd -m -p $(openssl passwd -1 ${user_password}) ${user_name} && \
    echo "${user_name} ALL=(ALL) ALL" >> /etc/sudoers

# swapping to our newly created user
USER ${user_name}

# clone, build, and install pikaur
RUN mkdir ~/git && \
    cd ~/git && \
    git clone "https://aur.archlinux.org/pikaur.git" && \
    cd ~/git/pikaur && \
    echo "${user_password}" | makepkg -s --noconfirm && \
    echo "${user_password}" | sudo -S pacman -U *pkg.tar.xz --noconfirm
```

I believe this is due to the operation difference in this if statement in pikaur when running as root compared to when not running as root: 

https://github.com/actionless/pikaur/blob/3c9bbfbd9b92e2adf09694bd99be0c0735a5423e/pikaur/main.py#L355-L369

because this means as root this code is executed wheras as user it is not: https://github.com/actionless/pikaur/blob/3c9bbfbd9b92e2adf09694bd99be0c0735a5423e/pikaur/core.py#L158-L166

Along with the InteractiveSpawn class https://github.com/actionless/pikaur/blob/3c9bbfbd9b92e2adf09694bd99be0c0735a5423e/pikaur/core.py#L123 which is where the error occurs, although I have yet to pinpoint more specifically as the error and stack trace inside InteractiveSpawn is swallowed somewhere.
Potentially a fix could be to check if we are running in a container and to just create directories without attempting to call systemd or a cli option to create directories without the use of systemd.

**Comment by actionless** [comment]
you can't run `makepkg` as root anyway

see https://github.com/actionless/pikaur/blob/master/Dockerfile#L16-L23
and https://github.com/actionless/pikaur/blob/master/Dockerfile#L37-L38

**Comment by actionless** [comment]
(and in docker you can't run systemd dynamic-users neither)

**Comment by DreamingRaven** [comment]
Hey, thanks for replying so quick.
I use ``USER ${user_name}`` to change user since all following commands are as the user, so makepkg is not being called as root. But I was still passing in the user password arbitrarily which I have now removed. Although both ways still succeed for installing pikaur.

It looks like you are just giving the user unlimited passwordless sudo access here which is not desirable even inside a container but I will try it to see if it makes a difference: https://github.com/actionless/pikaur/blob/a36531e7f6c02423445828f244aaaf7bbdd0b7a6/Dockerfile#L16-L23

I then try pairing it according to your other link:
https://github.com/actionless/pikaur/blob/a36531e7f6c02423445828f244aaaf7bbdd0b7a6/Dockerfile#L37-L38

resulting in:

```
FROM archlinux:latest

# variable for user username to use in the container
ARG user_name=archie

# variable for user password to use in the container
ARG user_password=archer

# variable for which branch to use of nemesyst when installing it
ARG branch=master

# creating basic gpu capable archlinux system with user and python
RUN pacman -Syyuu sudo nvidia git base-devel python python-pip pyalpm --noconfirm && \
    useradd -m -p $(openssl passwd -1 ${user_password}) ${user_name} && \
    echo "${user_name} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# swapping to our newly created user
USER ${user_name}

# clone, build, and install pikaur
RUN mkdir ~/git && \
    cd ~/git && \
    git clone "https://aur.archlinux.org/pikaur.git" && \
    cd ~/git/pikaur && \
    makepkg -s --noconfirm && \
    echo "${user_password}" | sudo -S pacman -U *pkg.tar.xz --noconfirm


# attempt to install any package in our case python-tensorflow-cuda
# RUN echo "${user_password}" | sudo -S pikaur -S python-tensorflow-cuda --noconfirm

USER root
RUN sudo -u ${user_name} pikaur -S --noconfirm python-tensorflow-cuda
```
Will result in this error:
```
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
Traceback (most recent call last):
  File "/usr/sbin/pikaur", line 5, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 20, in <module>
    from .args import (
  File "/usr/lib/python3.8/site-packages/pikaur/args.py", line 8, in <module>
    from .core import spawn
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 18, in <module>
    from .config import PikaurConfig
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/pikaur/config.py'
The command '/bin/sh -c sudo -u ${user_name} pikaur -S --noconfirm python-tensorflow-cuda' returned a non-zero code: 1
```

Am I missing something?

Also side note is it necessary to set root nopasswd in /etc/sudoers like here https://github.com/actionless/pikaur/blob/a36531e7f6c02423445828f244aaaf7bbdd0b7a6/Dockerfile#L19? I tried it with and without, both fail, but I guess there is no harm in being explicit.

**Comment by actionless** [comment]
first try literally copy the stuff from pikaur's Dockerfile

next try to figure out how the difference affects the result

**Comment by DreamingRaven** [comment]
Your docker also can not use pikaur as root or using sudo.
It is not a problem with my or your dockerfile. (also your travis section fails)

### reproduce
```
git clone https://github.com/actionless/pikaur
cd pikaur
sudo docker build -t archer/pikaur .
```
Results in:
```
 => pikaur -Su --noconfirm --ignore expac
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
:: Ignoring package update expac (8-2 => 10-1)
Reading AUR packages info...
looking for conflicting AUR packages...
:: Skipping review of PKGBUILD for etc-update package (--noconfirm)
:: Package etc-update is already built. Pass '--rebuild' flag to force the build.

Reading local package database...
ok
:: Took 32.33 seconds

======================================================================
FAIL: test_aur_package_with_alternative_aur_dep (pikaur_test.test_basic.InstallTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app-build/pikaur_test/test_basic.py", line 55, in test_aur_package_with_alternative_aur_dep
    self.assertInstalled(pkg_name)
  File "/opt/app-build/pikaur_test/helpers.py", line 241, in assertInstalled
    self.fail(f'Package "{pkg_name}" is not installed.')
AssertionError: Package "pacaur" is not installed.

======================================================================
FAIL: test_aur_package_with_aur_dep (pikaur_test.test_basic.InstallTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app-build/pikaur_test/test_basic.py", line 38, in test_aur_package_with_aur_dep
    self.assertInstalled(pkg_name)
  File "/opt/app-build/pikaur_test/helpers.py", line 241, in assertInstalled
    self.fail(f'Package "{pkg_name}" is not installed.')
AssertionError: Package "pacaur" is not installed.

======================================================================
FAIL: test_aur_pkg_with_already_installed_alternative_aur_dep (pikaur_test.test_basic.InstallTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app-build/pikaur_test/test_basic.py", line 74, in test_aur_pkg_with_already_installed_alternative_aur_dep
    self.assertInstalled(pkg_name)
  File "/opt/app-build/pikaur_test/helpers.py", line 241, in assertInstalled
    self.fail(f'Package "{pkg_name}" is not installed.')
AssertionError: Package "pacaur" is not installed.

----------------------------------------------------------------------
Ran 51 tests in 379.303s

FAILED (failures=3)
The command '/bin/sh -c sudo -u user env 	TRAVIS=$TRAVIS 	TRAVIS_JOB_ID=$TRAVIS_JOB_ID 	TRAVIS_BRANCH=$TRAVIS_BRANCH 	TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST 	./maintenance_scripts/ci.sh $MODE --write-db' returned a non-zero code: 1
```

Comment step 14 (travis) out:

```
# This file is licensed under GPLv3, see https://www.gnu.org/licenses/

FROM archlinux/base
WORKDIR /opt/app-build/

ARG TRAVIS
ARG TRAVIS_JOB_ID
ARG TRAVIS_BRANCH
ARG TRAVIS_PULL_REQUEST
ARG MODE=--local

RUN echo 'Server = https://mirrors.xtom.nl/archlinux/$repo/os/$arch' >> /etc/pacman.d/mirrorlist ; \
	echo 'Server = https://archlinux.mirror.pcextreme.nl/$repo/os/$arch' >> /etc/pacman.d/mirrorlist ; \
	echo 'Server = https://archlinux.mirror.wearetriple.com/$repo/os/$arch' >> /etc/pacman.d/mirrorlist ; \
	echo 'Server = https://mirror.mijn.host/archlinux/$repo/os/$arch' >> /etc/pacman.d/mirrorlist
RUN rm /usr/share/libalpm/hooks/package-cleanup.hook ; \
	pacman -Syu --noconfirm --needed sudo base-devel git && \
	useradd -m user && \
	echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
	echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
	echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
	echo "LANG=en_US.UTF-8" > /etc/locale.conf && \
	locale-gen
ENV LANG=en_US.utf8 \
	LANGUAGE=en_US.UTF-8 \
	LC_ALL=en_US.UTF-8

COPY . /opt/app-build/
RUN pacman -Sy ruby-ronn asp --noconfirm --needed && \
	chown -R user /opt/app-build/ && \
	sudo -u user git fetch -t || true && \
	sudo -u user make check_man && \
	sudo -u user tar --transform 's,^,pikaur-git/,' -cf pikaur-git.tar.gz . && \
	sudo -u user sed -i 's/"$pkgname::.*"/"pikaur-git.tar.gz"/' PKGBUILD && \
	sudo -u user makepkg -fsi --noconfirm && \
	sleep 0.1 && \
	sudo -u user pikaur -S --noconfirm --color=always iputils python-virtualenv \
		python-pylint flake8 mypy python-vulture python-coveralls

RUN pacman -S --noconfirm --needed python-pip && pip install -U mypy==0.720  # @TODO: mypy 0.730 is broken
# RUN pacman -S --noconfirm --needed python-pip && pip install -U git+https://github.com/python/mypy/  # @TODO: mypy 0.730 is broken

# RUN sudo -u user env \
# 	TRAVIS=$TRAVIS \
# 	TRAVIS_JOB_ID=$TRAVIS_JOB_ID \
# 	TRAVIS_BRANCH=$TRAVIS_BRANCH \
# 	TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST \
# 	./maintenance_scripts/ci.sh $MODE --write-db
```
Build it successfully using ``sudo docker build -t archer/pikaur .``
Run it interactiveley using `` sudo docker run --gpus all -it archer/pikaur bash`` or `` sudo docker run  -it archer/pikaur bash`` if you dont have nvidia dockers (https://wiki.archlinux.org/index.php/Docker#With_NVIDIA_Container_Toolkit_(recommended)) 
In the now root terminal just type ``pikaur -h``:
You can even try as "user" type ``sudo pikaur -h``:
both fail

```archer@azuran ~/g/pikaur> sudo docker run --gpus all -it archer/pikaur bash
[root@a67fef49c2e2 app-build]# pikaur
Traceback (most recent call last):
  File "/usr/sbin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 396, in main
    create_dirs()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 368, in create_dirs
    raise Exception(result)
Exception: InteractiveSpawn returned 1:
STDOUT:


STDERR:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
```

This issue is both in your docker and in mine, across several different archlinux machines (not that it matters much in docker).

**Comment by actionless** [comment]
> Your docker also can not use pikaur as root or using sudo.

yes ,i wrote above why it's not possible to use it

just copy paste the command from my Dockerfile (it for sure works in both my loacl machine and Travis CI, so i don't have any question to it):

> sudo -u user pikaur -S --noconfirm python-vulture

**Comment by actionless** [comment]
also you could make a wrapper in your dockerfile:

```dockerfile
RUN echo -e "#!/bin/sh\nexec sudo -u user pikaur -S --noconfirm $@" > /usr/local/bin/pikaur
```

**Comment by actionless** [comment]
>  but I guess there is no harm in being explicit.

instead of `ALL` you could adjust sudoers to allow NOPASSWD only for `pacman`

**Comment by DreamingRaven** [comment]
Actually that is quite a cool idea to wrap it up like that to keep it all clean, cheers thanks actionless.
Thanks for taking the time to respond as well, I appreciate it, and keep up to great work with pikaur!
Yeah thats also a good shout to specify pacman instead of all in sudoers.

**Comment by DreamingRaven** [comment]
for anyone in future looking at this and being caught out, my working solution is:

```
FROM archlinux:latest

# variable for user username to use in the container
ARG user_name=archie

# variable for user password to use in the container
ARG user_password=archer

# variable for which branch to use of nemesyst when installing it
ARG branch=master

# creating basic gpu capable archlinux system
RUN pacman -Syyuu sudo nvidia git base-devel python python-pip pyalpm --noconfirm

# creating user with the desired permissions (NOPASS required for pikaur stages)
RUN useradd -m -p $(openssl passwd -1 ${user_password}) ${user_name} && \
    echo "${user_name} ALL=(ALL) NOPASSWD:/usr/bin/pacman" >> /etc/sudoers

# swapping to our newly created user
USER ${user_name}

# clone, build, and install pikaur
RUN mkdir /home/${user_name}/git && \
    cd /home/${user_name}/git && \
    git clone "https://github.com/DreamingRaven/pikaur" && \
    cd /home/${user_name}/git/pikaur && \
    makepkg -s --noconfirm && \
    echo "${user_password}" | sudo -S pacman -U *pkg.tar.xz --noconfirm

# swapping back to root to continue since we no longer desire to be a user for makepkg
USER root

# install more specific packages from community and AUR as needed
RUN sudo -u ${user_name} pikaur -S --noconfirm python-tensorflow-cuda
```

I could clean up the user swaps but it works.
