### ISSUE TITLE
Local pkgbuild not works when running pikaur as root user

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#448]
I accidentally did this from the root user, which leads to this error: 

```
# pikaur -P ./go-ipfs/trunk/PKGBUILD 
Reading local package database...
:: error: failed to generate .SRCINFO from ./go-ipfs/trunk/PKGBUILD:
Running as unit: run-u23555.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=200
Service runtime: 7ms

```

That's a bug I guess.

_Originally posted by @RubenKelevra in https://github.com/actionless/pikaur/issues/366#issuecomment-580729864_

**Comment by actionless** [comment]
@RubenKelevra the issue caused by systemd-dynamic users not able to access that directory


a workaround would be to copy the whole directory containing PKGBUILD under `/var/cache/private/pikaur` where dynamic users are living, but that would either require adding more code to remove it after the build or will grow the size of `/var/cache/private/pikaur` even more

**Comment by RubenKelevra** [comment]
@actionless Not asking for this to work, just asking for a nice error message. I was quite confused.

And yes, I had multiple failed services in systemctl

**Comment by actionless** [comment]
IMHO instead of investing the time into detecting this error-prone case would be better to just apply the workaround described above, just don't have time for it right now

**Comment by RubenKelevra** [comment]
@actionless your time, your choice ;)

**Comment by actionless** [comment]
though i'm always happy for contributions :3

**Comment by RubenKelevra** [comment]
@actionless I got the same issue as you, time constrains ;)

**Comment by lectrode** [comment]
[This commit](https://github.com/actionless/pikaur/commit/bf204697cf7830f6593f39d91f6873509b8175d8) breaks the ability to successfully install some packages as root.

Failure (with that commit intact):
```
$ sudo pikaur -Sa pikaur-git --pikaur-debug --noconfirm
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-Sa', 'pikaur-git', '--pikaur-debug', '--noconfirm']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=[]
    not_found_repo_pkgs_names=['pikaur-git']
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['pikaur-git']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'pikaur-git': <VersionMatcher pikaur-git['cmp_default']None>}
Reading local package database...
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pikaur-git
:: debug: install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[<AURPackageInfo "pikaur-git" 1.8-1>]
    not_found_aur_pkgs=[]

:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "pikaur-git" 1.8.r20.gf1e630b-1 -> 1.8-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest pyalpm git python-commonmark
=> pacman --color=always --sync --print-format=%% python-commonmark
=> pacman --color=always --deptest pyalpm git python-commonmark
Reading repository package databases...
=> pacman --color=always --sync python-commonmark --print-format %r/%n
=> pacman --color=always --sync --noconfirm --needed python-commonmark --print-format %r/%n
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/pikaur-git pull origin master
=> pacman --color=always --deptest pyalpm git
=> pacman --color=always --deptest python-commonmark
looking for conflicting AUR packages...
=> pacman --color=always --deptest pyalpm git python-commonmark
Not showing diff for pikaur-git package (--noconfirm)
:: Skipping review of PKGBUILD for pikaur-git package (--noconfirm)
:: debug: Gonna build self.package_builds_by_name={'pikaur-git': <pikaur.build.PackageBuild object at 0x7fb746c065b0>}
:: debug: Gonna build pkg_build.package_names=['pikaur-git']
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp cp -r /var/cache/private/pikaur/aur_repos/pikaur-git/CHANGELOG /var/cache/private/pikaur/aur_repos/pikaur-git/PKGBUILD /var/cache/private/pikaur/aur_repos/pikaur-git/.SRCINFO /var/cache/private/pikaur/build/pikaur-git/
=> pacman --color=always --deptest python-commonmark
Reading local package database...
=> pacman --color=always --deptest pyalpm git
=> pacman --color=always --deptest python-commonmark
:: Installing repository dependencies for pikaur-git:
=> pacman --color=always --noconfirm --sync --asdeps python-commonmark
resolving dependencies...
looking for conflicting packages...

Packages (3) python-docutils-0.17.1-2  python-future-0.18.2-5  python-commonmark-0.9.1-3

Total Installed Size:  8.51 MiB

:: Proceed with installation? [Y/n] 
(3/3) checking keys in keyring                                                                                  [##################################################################] 100%
(3/3) checking package integrity                                                                                [##################################################################] 100%
(3/3) loading package files                                                                                     [##################################################################] 100%
(3/3) checking for file conflicts                                                                               [##################################################################] 100%
(3/3) checking available disk space                                                                             [##################################################################] 100%
:: Processing package changes...
(1/3) installing python-docutils                                                                                [##################################################################] 100%
(2/3) installing python-future                                                                                  [##################################################################] 100%
Optional dependencies for python-future
    python-setuptools: futurize and pasteurize scripts [installed]
(3/3) installing python-commonmark                                                                              [##################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Reading local package database...
:: Downloading the latest sources for a devel package pikaur-git...
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/pikaur-git makepkg --nobuild --noprepare --nocheck --nodeps
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 36, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 352, in main
    cli_entry_point()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 268, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 1019, in install_packages
    self.build_packages()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 852, in build_packages
    pkg_build.build(
  File "/usr/lib/python3.9/site-packages/pikaur/build.py", line 764, in build
    if self.check_if_already_built():
  File "/usr/lib/python3.9/site-packages/pikaur/build.py", line 449, in check_if_already_built
    self.get_latest_dev_sources()
  File "/usr/lib/python3.9/site-packages/pikaur/build.py", line 302, in get_latest_dev_sources
    SrcInfo(self.build_dir).regenerate()
  File "/usr/lib/python3.9/site-packages/pikaur/srcinfo.py", line 128, in regenerate
    isolate_root_cmd(
  File "/usr/lib/python3.9/site-packages/pikaur/core.py", line 213, in isolate_root_cmd
    raise Exception("Please run pikaur -P as a standard user")
Exception: Please run pikaur -P as a standard user
```

Success (the 2 lines from that commit commented out):
```
$ sudo pikaur -Sa pikaur-git --pikaur-debug --noconfirm
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-Sa', 'pikaur-git', '--pikaur-debug', '--noconfirm']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=[]
    not_found_repo_pkgs_names=['pikaur-git']
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['pikaur-git']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'pikaur-git': <VersionMatcher pikaur-git['cmp_default']None>}
Reading local package database...
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pikaur-git
:: debug: install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[<AURPackageInfo "pikaur-git" 1.8-1>]
    not_found_aur_pkgs=[]

:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "pikaur-git" 1.8.r20.gf1e630b-1 -> 1.8-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest pyalpm git python-commonmark
Reading repository package databases...
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/pikaur-git pull origin master
=> pacman --color=always --deptest pyalpm git
=> pacman --color=always --deptest python-commonmark
looking for conflicting AUR packages...
Not showing diff for pikaur-git package (--noconfirm)
:: Skipping review of PKGBUILD for pikaur-git package (--noconfirm)
:: debug: Gonna build self.package_builds_by_name={'pikaur-git': <pikaur.build.PackageBuild object at 0x7f129152ef10>}
:: debug: Gonna build pkg_build.package_names=['pikaur-git']
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp cp -r /var/cache/private/pikaur/aur_repos/pikaur-git/CHANGELOG /var/cache/private/pikaur/aur_repos/pikaur-git/PKGBUILD /var/cache/private/pikaur/aur_repos/pikaur-git/.SRCINFO /var/cache/private/pikaur/build/pikaur-git/
:: Downloading the latest sources for a devel package pikaur-git...
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/pikaur-git makepkg --nobuild --noprepare --nocheck --nodeps
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/pikaur-git makepkg --printsrcinfo -p PKGBUILD
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/pikaur-git makepkg --packagelist

:: Starting the build:
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/pikaur-git makepkg --force
Running as unit: run-u426.service
Press ^] three times within 1s to disconnect TTY.
==> Making package: pikaur-git 1.8.r20.gf1e630b-1 (Wed 01 Dec 2021 11:23:23 PM MST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating pikaur-git git repo...
Fetching origin
==> Validating source files with md5sums...
    pikaur-git ... Skipped
==> Extracting sources...
  -> Creating working copy of pikaur-git git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> Starting build()...
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
find pikaur -type f -name '*.py' \
	| xargs xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 --keyword='_n:1,2' --output=locale/pikaur.pot
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
........................ done.
msgfmt -o locale/fr.mo locale/fr.po
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
....................... done.
msgfmt -o locale/ru.mo locale/ru.po
test -f locale/pt.po || msginit --locale=pt --no-translator --input=locale/pikaur.pot --output=locale/pt.po
msgmerge --update locale/pt.po locale/pikaur.pot
........................ done.
msgfmt -o locale/pt.mo locale/pt.po
test -f locale/pt_BR.po || msginit --locale=pt_BR --no-translator --input=locale/pikaur.pot --output=locale/pt_BR.po
msgmerge --update locale/pt_BR.po locale/pikaur.pot
....................... done.
msgfmt -o locale/pt_BR.mo locale/pt_BR.po
test -f locale/de.po || msginit --locale=de --no-translator --input=locale/pikaur.pot --output=locale/de.po
msgmerge --update locale/de.po locale/pikaur.pot
........................ done.
msgfmt -o locale/de.mo locale/de.po
test -f locale/is.po || msginit --locale=is --no-translator --input=locale/pikaur.pot --output=locale/is.po
msgmerge --update locale/is.po locale/pikaur.pot
...................... done.
msgfmt -o locale/is.mo locale/is.po
test -f locale/tr.po || msginit --locale=tr --no-translator --input=locale/pikaur.pot --output=locale/tr.po
msgmerge --update locale/tr.po locale/pikaur.pot
....................... done.
msgfmt -o locale/tr.mo locale/tr.po
test -f locale/da.po || msginit --locale=da --no-translator --input=locale/pikaur.pot --output=locale/da.po
msgmerge --update locale/da.po locale/pikaur.pot
........................... done.
msgfmt -o locale/da.mo locale/da.po
test -f locale/nl.po || msginit --locale=nl --no-translator --input=locale/pikaur.pot --output=locale/nl.po
msgmerge --update locale/nl.po locale/pikaur.pot
....................... done.
msgfmt -o locale/nl.mo locale/nl.po
test -f locale/es.po || msginit --locale=es --no-translator --input=locale/pikaur.pot --output=locale/es.po
msgmerge --update locale/es.po locale/pikaur.pot
....................... done.
msgfmt -o locale/es.mo locale/es.po
test -f locale/zh_CN.po || msginit --locale=zh_CN --no-translator --input=locale/pikaur.pot --output=locale/zh_CN.po
msgmerge --update locale/zh_CN.po locale/pikaur.pot
....................... done.
msgfmt -o locale/zh_CN.mo locale/zh_CN.po
test -f locale/it.po || msginit --locale=it --no-translator --input=locale/pikaur.pot --output=locale/it.po
msgmerge --update locale/it.po locale/pikaur.pot
........................ done.
msgfmt -o locale/it.mo locale/it.po
test -f locale/ja.po || msginit --locale=ja --no-translator --input=locale/pikaur.pot --output=locale/ja.po
msgmerge --update locale/ja.po locale/pikaur.pot
....................... done.
msgfmt -o locale/ja.mo locale/ja.po
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
sed -i \
	-e '/coveralls/d' \
	-e '/Screenshot/d' \
	pikaur.1
mkdir -p dist/usr/bin
sed \
	-e "s/%PYTHON_BUILD_VERSION%/$(python -c 'import sys ; print(f"{sys.version_info.major}.{sys.version_info.minor}")')/g" \
	packaging/usr/bin/pikaur > dist/usr/bin/pikaur
chmod +x dist/usr/bin/pikaur
==> Entering fakeroot environment...
==> Starting package()...
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/pikaur
copying pikaur/__init__.py -> build/lib/pikaur
copying pikaur/__main__.py -> build/lib/pikaur
copying pikaur/argparse.py -> build/lib/pikaur
copying pikaur/args.py -> build/lib/pikaur
copying pikaur/aur.py -> build/lib/pikaur
copying pikaur/aur_deps.py -> build/lib/pikaur
copying pikaur/build.py -> build/lib/pikaur
copying pikaur/conflicts.py -> build/lib/pikaur
copying pikaur/core.py -> build/lib/pikaur
copying pikaur/exceptions.py -> build/lib/pikaur
copying pikaur/filelock.py -> build/lib/pikaur
copying pikaur/getpkgbuild_cli.py -> build/lib/pikaur
copying pikaur/help_cli.py -> build/lib/pikaur
copying pikaur/i18n.py -> build/lib/pikaur
copying pikaur/info_cli.py -> build/lib/pikaur
copying pikaur/install_cli.py -> build/lib/pikaur
copying pikaur/install_info_fetcher.py -> build/lib/pikaur
copying pikaur/main.py -> build/lib/pikaur
copying pikaur/makepkg_config.py -> build/lib/pikaur
copying pikaur/news.py -> build/lib/pikaur
copying pikaur/pacman.py -> build/lib/pikaur
copying pikaur/pacman_i18n.py -> build/lib/pikaur
copying pikaur/pikspect.py -> build/lib/pikaur
copying pikaur/pprint.py -> build/lib/pikaur
copying pikaur/print_department.py -> build/lib/pikaur
copying pikaur/progressbar.py -> build/lib/pikaur
copying pikaur/prompt.py -> build/lib/pikaur
copying pikaur/replacements.py -> build/lib/pikaur
copying pikaur/search_cli.py -> build/lib/pikaur
copying pikaur/srcinfo.py -> build/lib/pikaur
copying pikaur/updates.py -> build/lib/pikaur
copying pikaur/urllib.py -> build/lib/pikaur
copying pikaur/version.py -> build/lib/pikaur
copying pikaur/config.py -> build/lib/pikaur
running install_lib
creating /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr
creating /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib
creating /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9
creating /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages
creating /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/__init__.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/__main__.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/argparse.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/args.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/aur.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/aur_deps.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/build.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/conflicts.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/core.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/exceptions.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/filelock.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/getpkgbuild_cli.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/help_cli.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/i18n.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/info_cli.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/install_cli.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/install_info_fetcher.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/main.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/makepkg_config.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/news.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/pacman.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/pacman_i18n.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/pikspect.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/pprint.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/print_department.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/progressbar.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/prompt.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/replacements.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/search_cli.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/srcinfo.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/updates.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/urllib.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/version.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
copying build/lib/pikaur/config.py -> /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/__init__.py to __init__.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/__main__.py to __main__.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/argparse.py to argparse.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/args.py to args.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/aur.py to aur.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/aur_deps.py to aur_deps.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/build.py to build.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/conflicts.py to conflicts.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/core.py to core.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/exceptions.py to exceptions.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/filelock.py to filelock.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/getpkgbuild_cli.py to getpkgbuild_cli.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/help_cli.py to help_cli.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/i18n.py to i18n.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/info_cli.py to info_cli.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/install_cli.py to install_cli.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/install_info_fetcher.py to install_info_fetcher.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/main.py to main.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/makepkg_config.py to makepkg_config.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/news.py to news.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/pacman.py to pacman.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/pacman_i18n.py to pacman_i18n.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/pikspect.py to pikspect.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/pprint.py to pprint.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/print_department.py to print_department.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/progressbar.py to progressbar.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/prompt.py to prompt.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/replacements.py to replacements.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/search_cli.py to search_cli.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/srcinfo.py to srcinfo.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/updates.py to updates.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/urllib.py to urllib.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/version.py to version.cpython-39.pyc
byte-compiling /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur/config.py to config.cpython-39.pyc
writing byte-compilation script '/tmp/tmphdl7tphg.py'
/usr/bin/python3 /tmp/tmphdl7tphg.py
removing /tmp/tmphdl7tphg.py
running install_egg_info
Writing /var/cache/private/pikaur/build/pikaur-git/pkg/pikaur-git/usr/lib/python3.9/site-packages/pikaur-1.8-py3.9.egg-info
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "pikaur-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: pikaur-git 1.8.r20.gf1e630b-1 (Wed 01 Dec 2021 11:23:33 PM MST)
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 11.585s
CPU time consumed: 6.187s

=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/pikaur-git makepkg --packagelist
:: debug: Build done for packages pkg_build.package_names=['pikaur-git'], removing from queue
=> pacman --color=always --upgrade --noconfirm /var/cache/pikaur/pkg/pikaur-git-1.8.r20.gf1e630b-1-any.pkg.tar.zst
loading packages...
warning: pikaur-git-1.8.r20.gf1e630b-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) pikaur-git-1.8.r20.gf1e630b-1

Total Installed Size:  1.02 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                  [##################################################################] 100%
(1/1) checking package integrity                                                                                [##################################################################] 100%
(1/1) loading package files                                                                                     [##################################################################] 100%
(1/1) checking for file conflicts                                                                               [##################################################################] 100%
(1/1) checking available disk space                                                                             [##################################################################] 100%
:: Running pre-transaction hooks...
(1/1) Creating Timeshift snapshot before upgrade...
:: Processing package changes...
(1/1) reinstalling pikaur-git                                                                                   [##################################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Checking which packages need to be rebuilt
```

**Comment by actionless** [comment]
thanks for update, reverted it for now: https://github.com/actionless/pikaur/pull/608

**Comment by lectrode** [comment]
thank you, much appreciated!
