### ISSUE TITLE
pikaur crash if removing build-dep on some packages

### ISSUE THREAD

**Issue by fleixi** [actionless/pikaur#452]
```
pikaur -Vq
Pikaur v1.6.3
Pacman v5.2.1 - libalpm v12.0.1
```
As example installing odoo

`pikaur -S odoo`

i get this error:

```
(1/1) removing python2                                                                                  [#############################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 409, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 319, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 325, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 130, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 157, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 170, in main_sequence
    self.get_package_builds()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 503, in get_package_builds
    self._find_extra_aur_build_deps(
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 475, in _find_extra_aur_build_deps
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 176, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 952, in install_packages
    self.build_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 822, in build_packages
    packages_to_be_built.remove(_pkg_name)
ValueError: list.remove(x): x not in list
```
##### Attached log:

Long output so i used a pastebin-server

https://paste.ubuntu.com/p/6Fb8rTtY9M/

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by jplatte** [comment]
I'm using pikaur-git and am running into what seems to be the same error when trying to build `zopflipng-git` (I think it's important that this is already installed and some things are thus cached):

```
% LC_ALL=C pikaur -S zopflipng-git                                                                                                                                                                                 :(
[sudo] password for jplatte:
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 zopflipng-git                         1.0.3.r1.g00e21c3-1  -> 1.0.1.r19.g16e0741-1

:: Proceed with installation? [Y/n]
:: [v]iew package details   [m]anually select packages
>>
:: warning: New build deps found for zopflipng-git package: glibc
Resolving AUR dependencies...

:: AUR package will be installed:
 zopflipng-git                         1.0.3.r1.g00e21c3-1  -> 1.0.1.r19.g16e0741-1

:: Proceed with installation? [Y/n]
:: [v]iew package details   [m]anually select packages
>>
looking for conflicting AUR packages...
:: warning: Not showing diff for zopfli-git, libzopfli-git, zopflipng-git, libzopflipng-git package (already reviewed)
:: Skipping review of PKGBUILD for zopfli-git, libzopfli-git, zopflipng-git, libzopflipng-git package (--noedit)

:: Downloading the latest sources for devel packages zopfli-git, libzopfli-git, zopflipng-git, libzopflipng-git...
:: Packages zopfli-git, libzopfli-git, zopflipng-git, libzopflipng-git are already built. Pass '--rebuild' flag to force the build.

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 411, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 319, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 325, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 130, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 174, in main_sequence
    self.get_package_builds()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 509, in get_package_builds
    self._find_extra_aur_build_deps(
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 481, in _find_extra_aur_build_deps
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 949, in install_packages
    self.build_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 819, in build_packages
    packages_to_be_built.remove(_pkg_name)
ValueError: list.remove(x): x not in list
```

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by jplatte** [comment]
Fixed, thanks! :)
