### ISSUE TITLE
Bug in print_department printing packages to upgrade

### ISSUE THREAD

**Issue by OlMon** [actionless/pikaur#454]
```
Pikaur v1.6.4
Pacman v5.2.1 - libalpm v12.0.1

```

##### Attached log:

```
❯ pikaur -Qu
Reading local package database...
Reading repository package databases...
Reading AUR packages info...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 409, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 316, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 123, in cli_print_upgradeable
    print_stdout(pretty_format_upgradeable(
  File "/usr/lib/python3.8/site-packages/pikaur/print_department.py", line 246, in pretty_format_upgradeable
    line for line, _ in sorted(
TypeError: '<' not supported between instances of 'str' and 'NoneType'


```
I can not say when this started, and I can not find any other commands that would create this error. Maybe it is somehow related to a package i have installed.

**Comment by actionless** [comment]
is it works as `pikaur -Quq`? and if so, what are the packages?

**Comment by actionless** [comment]
and also please share the value from `[sync] upgradesorting` from your  `~/.config/pikaur.conf`

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by OlMon** [comment]
It works, thanks a lot!
