### ISSUE TITLE
pikaur crashes with permission error after update to 1.6.5

### ISSUE THREAD

**Issue by RubenKelevra** [actionless/pikaur#456]
I run `pikaur -S pikaur` since `pikaur-Syu` showed an update from 1.6.4 to 1.6.5.

Afterwards pikaur cannot be started anymore:

```
$ pikaur -Syu
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 41, in <module>
    from .install_cli import InstallPackagesCLI
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 45, in <module>
    from .news import News
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/pikaur/news.py'

```

**Comment by actionless** [comment]
try `fsck` :)

**Comment by RubenKelevra** [comment]
This isn't a filesystem error and your arrogance isn't helping to get this issue solved.

```
[ruben@loki ~]$ pikaur -Syu --rebuild 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 archzfs is up to date
 archzfs-kernels is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 pikaur                                1.5.9.1-1            -> 1.6.5-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
looking for conflicting AUR packages...
:: warning: Not showing diff for pikaur package (already reviewed)
Do you want to edit PKGBUILD for pikaur package? [y/N] 

:: Starting full system upgrade...
warning: linux: ignoring package upgrade (5.4.15.arch1-1 => 5.5.5.arch1-1)
warning: linux-headers: ignoring package upgrade (5.4.15.arch1-1 => 5.5.5.arch1-1)
 there is nothing to do

:: Starting the build:
==> Making package: pikaur 1.6.5-1 (Tue 25 Feb 2020 12:16:51 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading pikaur-1.6.5.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0   124    0     0    532      0 --:--:-- --:--:-- --:--:--   532
100 2106k    0 2106k    0     0  1708k      0 --:--:--  0:00:01 --:--:-- 3001k
==> Validating source files with md5sums...
    pikaur-1.6.5.tar.gz ... Passed
==> Extracting sources...
  -> Extracting pikaur-1.6.5.tar.gz with bsdtar
==> Starting build()...
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
        #
find pikaur -type f -name '*.py' \
        | xargs xgettext --language=python --add-comments --sort-output \
                --default-domain=pikaur --from-code=UTF-8 --keyword='_n:1,2' --output=locale/pikaur.pot
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
..................... done.
msgfmt -o locale/fr.mo locale/fr.po
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
..................... done.
msgfmt -o locale/ru.mo locale/ru.po
test -f locale/pt.po || msginit --locale=pt --no-translator --input=locale/pikaur.pot --output=locale/pt.po
msgmerge --update locale/pt.po locale/pikaur.pot
..................... done.
msgfmt -o locale/pt.mo locale/pt.po
test -f locale/de.po || msginit --locale=de --no-translator --input=locale/pikaur.pot --output=locale/de.po
msgmerge --update locale/de.po locale/pikaur.pot
..................... done.
msgfmt -o locale/de.mo locale/de.po
test -f locale/is.po || msginit --locale=is --no-translator --input=locale/pikaur.pot --output=locale/is.po
msgmerge --update locale/is.po locale/pikaur.pot
..................... done.
msgfmt -o locale/is.mo locale/is.po
test -f locale/tr.po || msginit --locale=tr --no-translator --input=locale/pikaur.pot --output=locale/tr.po
msgmerge --update locale/tr.po locale/pikaur.pot
..................... done.
msgfmt -o locale/tr.mo locale/tr.po
test -f locale/da.po || msginit --locale=da --no-translator --input=locale/pikaur.pot --output=locale/da.po
msgmerge --update locale/da.po locale/pikaur.pot
......................... done.
msgfmt -o locale/da.mo locale/da.po
test -f locale/nl.po || msginit --locale=nl --no-translator --input=locale/pikaur.pot --output=locale/nl.po
msgmerge --update locale/nl.po locale/pikaur.pot
..................... done.
msgfmt -o locale/nl.mo locale/nl.po
test -f locale/es.po || msginit --locale=es --no-translator --input=locale/pikaur.pot --output=locale/es.po
msgmerge --update locale/es.po locale/pikaur.pot
..................... done.
msgfmt -o locale/es.mo locale/es.po
test -f locale/zh_CN.po || msginit --locale=zh_CN --no-translator --input=locale/pikaur.pot --output=locale/zh_CN.po
msgmerge --update locale/zh_CN.po locale/pikaur.pot
.................... done.
msgfmt -o locale/zh_CN.mo locale/zh_CN.po
test -f locale/it.po || msginit --locale=it --no-translator --input=locale/pikaur.pot --output=locale/it.po
msgmerge --update locale/it.po locale/pikaur.pot
.................. done.
msgfmt -o locale/it.mo locale/it.po
==> Entering fakeroot environment...
==> Starting package()...
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/pikaur
copying pikaur/news.py -> build/lib/pikaur
copying pikaur/i18n.py -> build/lib/pikaur
copying pikaur/argparse.py -> build/lib/pikaur
copying pikaur/conflicts.py -> build/lib/pikaur
copying pikaur/pikspect.py -> build/lib/pikaur
copying pikaur/makepkg_config.py -> build/lib/pikaur
copying pikaur/info_cli.py -> build/lib/pikaur
copying pikaur/args.py -> build/lib/pikaur
copying pikaur/pprint.py -> build/lib/pikaur
copying pikaur/prompt.py -> build/lib/pikaur
copying pikaur/progressbar.py -> build/lib/pikaur
copying pikaur/__init__.py -> build/lib/pikaur
copying pikaur/search_cli.py -> build/lib/pikaur
copying pikaur/install_cli.py -> build/lib/pikaur
copying pikaur/config.py -> build/lib/pikaur
copying pikaur/aur_deps.py -> build/lib/pikaur
copying pikaur/replacements.py -> build/lib/pikaur
copying pikaur/install_info_fetcher.py -> build/lib/pikaur
copying pikaur/aur.py -> build/lib/pikaur
copying pikaur/__main__.py -> build/lib/pikaur
copying pikaur/print_department.py -> build/lib/pikaur
copying pikaur/updates.py -> build/lib/pikaur
copying pikaur/srcinfo.py -> build/lib/pikaur
copying pikaur/pacman.py -> build/lib/pikaur
copying pikaur/core.py -> build/lib/pikaur
copying pikaur/build.py -> build/lib/pikaur
copying pikaur/exceptions.py -> build/lib/pikaur
copying pikaur/version.py -> build/lib/pikaur
copying pikaur/main.py -> build/lib/pikaur
running install_lib
creating /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr
creating /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib
creating /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8
creating /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages
creating /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/news.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/i18n.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/argparse.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/conflicts.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/pikspect.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/makepkg_config.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/info_cli.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/args.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/pprint.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/prompt.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/progressbar.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/__init__.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/search_cli.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/install_cli.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/config.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/aur_deps.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/replacements.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/install_info_fetcher.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/aur.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/__main__.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/print_department.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/updates.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/srcinfo.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/pacman.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/core.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/build.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/exceptions.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/version.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
copying build/lib/pikaur/main.py -> /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/news.py to news.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/i18n.py to i18n.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/argparse.py to argparse.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/conflicts.py to conflicts.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/pikspect.py to pikspect.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/makepkg_config.py to makepkg_config.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/info_cli.py to info_cli.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/args.py to args.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/pprint.py to pprint.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/prompt.py to prompt.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/progressbar.py to progressbar.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/__init__.py to __init__.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/search_cli.py to search_cli.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/install_cli.py to install_cli.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/config.py to config.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/aur_deps.py to aur_deps.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/replacements.py to replacements.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py to install_info_fetcher.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/aur.py to aur.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/__main__.py to __main__.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/print_department.py to print_department.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/updates.py to updates.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/srcinfo.py to srcinfo.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/pacman.py to pacman.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/core.py to core.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/build.py to build.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/exceptions.py to exceptions.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/version.py to version.cpython-38.pyc
byte-compiling /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur/main.py to main.cpython-38.pyc
writing byte-compilation script '/tmp/tmpib_8vekz.py'
/usr/bin/python3 /tmp/tmpib_8vekz.py
removing /tmp/tmpib_8vekz.py
running install_egg_info
Writing /home/ruben/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.8/site-packages/pikaur-1.6.5-py3.8.egg-info
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "pikaur"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: pikaur 1.6.5-1 (Tue 25 Feb 2020 12:17:00 AM CET)

loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) pikaur-1.6.5-1

Total Installed Size:  0.90 MiB
Net Upgrade Size:      0.01 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                              [################################################################] 100%
(1/1) checking package integrity                                                                            [################################################################] 100%
(1/1) loading package files                                                                                 [################################################################] 100%
(1/1) checking for file conflicts                                                                           [################################################################] 100%
(1/1) checking available disk space                                                                         [################################################################] 100%
:: Processing package changes...
(1/1) upgrading pikaur                                                                                      [################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[ruben@loki ~]$ pikaur -Syu --rebuild 
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 41, in <module>
    from .install_cli import InstallPackagesCLI
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 45, in <module>
    from .news import News
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/pikaur/news.py'

```

**Comment by SNvMK** [comment]
just encountered this error. no fix?
