### ISSUE TITLE
Failure after update -- pikaur 1.6.6.1 crashing?

### ISSUE THREAD

**Issue by c-dante** [actionless/pikaur#459]
```
pikaur -Vq
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 41, in <module>
    from .install_cli import InstallPackagesCLI
  File "<fstring>", line 1
    (pkg_base=)
             ^
SyntaxError: invalid syntax
```

##### [Optional] Prerequisites:
Doing a massive arch upgrade from a while ago -- unsure where the disconnect came from.
```
/usr/bin/python3
Python 3.7.4 (default, Jul 16 2019, 07:12:58)
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by c-dante** [comment]
Nope, had a borked python install.
