### ISSUE TITLE
KeyError when installing some AUR packages when PKGDEST set to shell variable

### ISSUE THREAD

**Issue by jeberger** [actionless/pikaur#479]
```
==> pikaur -Vq           
Pikaur v1.6.9.1
Pacman v5.2.1 - libalpm v12.0.1
```

I get the following stack trace when trying to upgrade some AUR packages:

```
=> makepkg --packagelist
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 435, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 324, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 135, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 994, in install_packages
    self.install_aur_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 954, in install_aur_packages
    aur_packages_to_install = {
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 955, in <dictcomp>
    pkg_name: self.package_builds_by_name[pkg_name].built_packages_paths[pkg_name]
KeyError: 'tuxguitar'
```

The crash occurs just after pikaur finished building the package and uninstalled the build dependencies.

I got the crash with:

```
pikaur -S tuxguitar tuxguitar-common
```

and with 

```
pikaur -S ttf-symbola
```

(Note that in the latter case, the `pkgbase` doesn't match the package name: `pkgbase` is `font-symbola`)

**Comment by actionless** [comment]
i can't reproduce it

**Comment by jeberger** [comment]
I was able to trace it back to the following line in my `.makepkg.conf`:

```
PKGDEST="$HOME/abs/packages"
```

Visibly pikaur doesn't expand the `$HOME` variable when searching for the build package (line 406 of `pikaur/build.py`).

Now I'm wondering why it works for most packages and only fails for one or two…

**Comment by actionless** [comment]
makepkg/makepkg.conf spec doesn't say it explicitly if shell variables are allowed in the paths

**Comment by actionless** [comment]
btw does it work if you use `~` instead of `$HOME`?

**Comment by jeberger** [comment]
Yes, it does work if I use `~` instead.

**Comment by jeberger** [comment]
However using `~` is not a solution because then plain `makepkg` doesn't work: it creates a folder named `~` in the current directory and gets confused between my home and that folder.

**Comment by actionless** [comment]
i'm thinking about this -- since it would be bad idea supporting  shell variables in general, mb to make a workaround, by replacing `$HOME` to `~` when reading paths from the config

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
