### ISSUE TITLE
crash in argparse when using --mflags

### ISSUE THREAD

**Issue by maep--** [actionless/pikaur#482]
I'm trying to pass a flag to makepkg and it crashes argparse.

```
Pikaur v1.6.9.1
Pacman v5.2.1 - libalpm v12.0.1
```

##### Attached log:

```
pikaur -S foo --mflags --skippgpcheck
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 23, in <module>
    from .help_cli import cli_print_help
  File "/usr/lib/python3.8/site-packages/pikaur/help_cli.py", line 9, in <module>
    from .core import spawn
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 20, in <module>
    from .pprint import print_stderr, color_line
  File "/usr/lib/python3.8/site-packages/pikaur/pprint.py", line 15, in <module>
    ARGS = parse_args()
  File "/usr/lib/python3.8/site-packages/pikaur/args.py", line 336, in parse_args
    parsed_args = parser.parse_pikaur_args(args)
  File "/usr/lib/python3.8/site-packages/pikaur/args.py", line 220, in parse_pikaur_args
    parsed_args, unknown_args = self.parse_known_args(raw_args)
  File "/usr/lib/python3.8/argparse.py", line 1807, in parse_known_args
    self.error(str(err))
  File "/usr/lib/python3.8/site-packages/pikaur/args.py", line 216, in error
    raise exc
  File "/usr/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/site-packages/pikaur/argparse.py", line 219, in _parse_known_args
    start_index, unknown_args = consume_optional(start_index)
  File "/usr/lib/python3.8/site-packages/pikaur/argparse.py", line 149, in consume_optional
    arg_count = match_argument(action, selected_patterns)
  File "/usr/lib/python3.8/argparse.py", line 2101, in _match_argument
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument --mflags: expected one argument
```

**Comment by maep--** [comment]
Sorry, I can't read. Maybe the error message could be more clear.

**Comment by actionless** [comment]
how could it be more clear than that? :)

>  argument --mflags: expected one argument
