### ISSUE TITLE
Recent update broke preceding pkgname with repo/

### ISSUE THREAD

**Issue by Svintooo** [actionless/pikaur#484]
This now results in a stacktrace: `pikaur -S aur/pkgname`
This works: `pikaur -S pkgname`

```
$ pikaur -Vq
Pikaur v1.6.10
Pacman v5.2.1 - libalpm v12.0.1
```

##### Attached log:

```
$ pikaur -S aur/mssql-tools
Reading repository package databases...
Reading local package database...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 435, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 324, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 135, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 246, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 67, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 164, in get_all_packages_info
    self.get_aur_pkgs_info(self.not_found_repo_pkgs_names)
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 374, in get_aur_pkgs_info
    if aur_packages_names_to_versions[aur_pkg.name](aur_pkg.version):
KeyError: 'mssql-tools'
$ 
$ 
$ pikaur -S mssql-tools
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: New dependencies will be installed from repository:
 patchelf (for msodbcsql)                                   -> 0.9-2
 unixodbc (for msodbcsql)                                   -> 2.3.7-2

:: AUR package will be installed:
 mssql-tools                                                -> 17.4.1.1-1

:: New dependency will be installed from AUR:
 msodbcsql (for mssql-tools)                                -> 17.4.2.1-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
```

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by Svintooo** [comment]
Seems to work now. Thanks!

**Comment by hrehfeld** [comment]
I'm running into this with `Pikaur v1.6.12` and *not* prefixing with repo!

```
$ pikaur -S man
Reading repository package databases...
Reading local package database...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 421, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 307, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 115, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 249, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 67, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 159, in get_all_packages_info
    self.get_repo_pkgs_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 289, in get_repo_pkgs_info
    self._get_repo_pkgs_info(pkg_lines=self.install_package_names) +
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 236, in _get_repo_pkgs_info
    return _get_pkg_install_infos(composed_result)
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 206, in _get_pkg_install_infos
    pkg = all_repo_pkgs[pkg_print.full_name]
KeyError: 'core/man-db'
$
```

**Comment by actionless** [comment]
@hrehfeld can't reproduce that:

```
$ pikaur -S man
Reading repository package databases...
Reading local package database...

:: Repository package will be installed:
 man-db                                2.9.3-1              -> 2.9.3-1

:: Proceed with installation? [Y/n]
:: [v]iew package details   [m]anually select packages
>> n

$ pikaur -Vq
Pikaur v1.6.12.r0.g641ce7f
Pacman v5.2.2 - libalpm v12.0.2
```

**Comment by hrehfeld** [comment]
Hm, not sure how to reproduce either, I was experimenting with a live system, updating, etc., so I couldn't really produce a test-case. Maybe try commenting (disabling) all sources in `/etc/pacman.d/mirrorlist`, I think I might have had that state at the time. Otherwise just ignore until further notice, and thanks for looking into it! ;-)

**Comment by actionless** [comment]
yup, please create a new issue if you'll have a test case
