### ISSUE TITLE
Installing packages prefixed with aur/package fails with version 1.6.10

### ISSUE THREAD

**Issue by bionade24** [actionless/pikaur#490]
```
pikaur -S aur/package

```

##### Attached log:

```
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 435, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 324, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 135, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 246, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 67, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 164, in get_all_packages_info
    self.get_aur_pkgs_info(self.not_found_repo_pkgs_names)
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 374, in get_aur_pkgs_info
    if aur_packages_names_to_versions[aur_pkg.name](aur_pkg.version):
KeyError: 'ignition-common-1'
```

**Comment by actionless** [comment]
was already fixed in b0b128f please check with `pikaur-git` if you still can reproduce
