### ISSUE TITLE
Exception: $pkg_name already added to the list

### ISSUE THREAD

**Issue by tuxayo** [actionless/pikaur#495]
```
Pikaur v1.6.10
Pacman v5.2.1 - libalpm v12.0.1

```

##### Attached log:

```
~ ❯❯❯ pikaur -S 0ad-git --verbose --pikaur-debug                                                                                                                         ✘ 130 
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['0ad-git']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync 0ad-git --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for aur_packages_versionmatchers=['0ad-git']... self.aur_updates_install_info=[]
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=0ad-git
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "0ad-git"   -> 21551-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest 0ad-data-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --sync --print-format=%% cmake boost 0ad-data-git
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=0ad-data-git
=> pacman --color=always --deptest 0ad-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --sync --print-format=%% 0ad-git
=> pacman --color=always --deptest 0ad-data-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --deptest 0ad-data-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --deptest 0ad-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --sync boost --print-format %r/%n
=> pacman --color=always --sync boost --print-format %r/%n
=> pacman --color=always --sync boost --print-format %r/%n
=> pacman --color=always --sync cmake --print-format %r/%n
=> pacman --color=always --sync cmake --print-format %r/%n
=> pacman --color=always --sync cmake --print-format %r/%n
=> pacman --color=always --sync --needed cmake boost boost boost cmake cmake --print-format %r/%n

:: New dependencies will be installed from repository:
 boost (for 0ad-git, 0ad-git, 0ad-data-git)                 -> 1.72.0-2
 cmake (for 0ad-git, 0ad-git, 0ad-data-git)                 -> 3.17.3-1
 jsoncpp (for cmake, cmake)                                 -> 1.9.2-1
 rhash (for cmake)                                          -> 1.3.9-2

:: AUR package will be installed:
 0ad-git                                                    -> 21551-1

:: New dependencies will be installed from AUR:
 0ad-data-git (for 0ad-git, 0ad-git)                        -> 21551-1
 0ad-git (for 0ad-data-git)                                 -> 21551-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
=> git -C /home/victor/.local/share/pikaur/aur_repos/0ad-git pull origin master
=> pacman --color=always --deptest binutils boost-libs curl enet libogg libpng libvorbis libxml2 openal sdl2 wxgtk zlib libgl glu gloox miniupnpc icu nspr
=> pacman --color=always --deptest boost cmake mesa zip python2 libsm git
=> pacman --color=always --deptest binutils boost-libs curl enet libogg libpng libvorbis libxml2 openal sdl2 wxgtk zlib libgl glu gloox miniupnpc icu nspr
=> pacman --color=always --deptest boost cmake mesa zip python2 libsm git
=> pacman --color=always --deptest binutils boost-libs curl enet libogg libpng libvorbis libxml2 openal sdl2 wxgtk zlib libgl glu gloox miniupnpc icu nspr
=> pacman --color=always --deptest boost cmake mesa zip python2 libsm git
:: warning: New build deps found for 0ad-git, 0ad-git, 0ad-data-git package: zlib, icu, boost-libs, libgl, openal, glu, wxgtk, libvorbis, nspr, miniupnpc, gloox, curl, sdl2, libxml2, libogg, binutils, libpng, enet
:: debug: install_cli: discarding install info for pkg... 0ad-git
:: debug: install_info_fetcher: discarding canceled_pkg_name='0ad-git'
:: debug: install_info_fetcher: aur_pkg_name='0ad-git': aur_deps=['0ad-data-git']
:: debug: install_info_fetcher: discarding canceled_pkg_name='0ad-data-git'
:: debug: install_info_fetcher: aur_pkg_name='0ad-data-git': aur_deps=['0ad-git']
:: debug: install_cli: discarded install info for pkg: 0ad-git
:: debug: install_cli: discarded install info for pkg: 0ad-data-git
:: debug: install_cli: discarding install info for pkg... 0ad-git
:: debug: install_info_fetcher: discarding canceled_pkg_name='0ad-git'
:: debug: install_cli: discarded install info for pkg: 0ad-git
:: debug: install_cli: discarding install info for pkg... 0ad-data-git
:: debug: install_info_fetcher: discarding canceled_pkg_name='0ad-data-git'
:: debug: install_cli: discarded install info for pkg: 0ad-data-git
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=[]
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={'/home/victor/.local/share/pikaur/aur_repos/0ad-git/PKGBUILD': ['0ad-git', '0ad-git', '0ad-data-git']}
    manually_excluded_packages_names=['0ad-git', '0ad-git', '0ad-data-git']

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
:: debug: install_info_fetcher: gonna get AUR pkgs install info for aur_packages_versionmatchers=[]... self.aur_updates_install_info=[]
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[]
:: debug: install_info_fetcher: gonna get install info from PKGBUILDs... self.aur_updates_install_info=[]
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 435, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 324, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 135, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 174, in main_sequence
    self.get_package_builds()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 519, in get_package_builds
    self._find_extra_aur_build_deps(
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 486, in _find_extra_aur_build_deps
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 246, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 67, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 166, in get_all_packages_info
    self.get_info_from_pkgbuilds()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 427, in get_info_from_pkgbuilds
    raise Exception(_(f"{pkg_name} already added to the list"))
Exception: 0ad-git already added to the list

```

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by tuxayo** [comment]
Confirmed!

Thanks a lot :D

**Comment by tuxayo** [comment]
@actionless Somehow, it's happening again :o 
```
~ ❯❯❯ pikaur -S 0ad-git --verbose --pikaur-debug                                                 ✘ 130 
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['0ad-git']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync 0ad-git --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for aur_packages_versionmatchers=['0ad-git']... self.aur_updates_install_info=[]
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=0ad-git
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "0ad-git"   -> 21551-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest 0ad-data-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --sync --print-format=%% 0ad-data-git
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=0ad-data-git
=> pacman --color=always --deptest 0ad-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --sync --print-format=%% 0ad-git
=> pacman --color=always --deptest 0ad-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --deptest 0ad-data-git boost cmake mesa zip python2 libsm git
=> pacman --color=always --deptest 0ad-data-git boost cmake mesa zip python2 libsm git

:: AUR package will be installed:
 0ad-git                                                    -> 21551-1

:: New dependencies will be installed from AUR:
 0ad-data-git (for 0ad-git, 0ad-git)                        -> 21551-1
 0ad-git (for 0ad-data-git)                                 -> 21551-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
=> git -C /home/victor/.local/share/pikaur/aur_repos/0ad-git pull origin master
=> pacman --color=always --deptest binutils boost-libs curl enet libogg libpng libvorbis libxml2 openal sdl2 wxgtk zlib libgl glu gloox miniupnpc icu nspr
=> pacman --color=always --deptest boost cmake mesa zip python2 libsm git
:: warning: New build deps found for 0ad-git, 0ad-data-git, 0ad-git package: miniupnpc, libpng, nspr, boost-libs, libxml2, curl, icu, openal, gloox, wxgtk, zlib, sdl2, libgl, libvorbis, enet, binutils, glu, libogg
:: debug: install_cli: discarding install info for pkg... 0ad-git
:: debug: install_info_fetcher: discarding canceled_pkg_name='0ad-git'
:: debug: install_info_fetcher: aur_pkg_name='0ad-git': aur_deps=['0ad-data-git']
:: debug: install_info_fetcher: discarding canceled_pkg_name='0ad-data-git'
:: debug: install_info_fetcher: aur_pkg_name='0ad-data-git': aur_deps=['0ad-git']
:: debug: install_cli: discarded install info for pkg: 0ad-data-git
:: debug: install_cli: discarded install info for pkg: 0ad-git
:: debug: install_cli: discarding install info for pkg... 0ad-data-git
:: debug: install_info_fetcher: discarding canceled_pkg_name='0ad-data-git'
:: debug: install_cli: discarded install info for pkg: 0ad-data-git
:: debug: install_cli: discarding install info for pkg... 0ad-git
:: debug: install_info_fetcher: discarding canceled_pkg_name='0ad-git'
:: debug: install_cli: discarded install info for pkg: 0ad-git
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=[]
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={'/home/victor/.local/share/pikaur/aur_repos/0ad-git/PKGBUILD': ['0ad-git', '0ad-data-git', '0ad-git']}
    manually_excluded_packages_names=['0ad-git', '0ad-data-git', '0ad-git']

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
:: debug: install_info_fetcher: gonna get AUR pkgs install info for aur_packages_versionmatchers=[]... self.aur_updates_install_info=[]
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[]
:: debug: install_info_fetcher: gonna get install info from PKGBUILDs... self.aur_updates_install_info=[]
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 435, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 324, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 135, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 174, in main_sequence
    self.get_package_builds()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 519, in get_package_builds
    self._find_extra_aur_build_deps(
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 486, in _find_extra_aur_build_deps
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 246, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 67, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 166, in get_all_packages_info
    self.get_info_from_pkgbuilds()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 427, in get_info_from_pkgbuilds
    raise Exception(_(f"{pkg_name} already added to the list"))
Exception: 0ad-git already added to the list

```
