### ISSUE TITLE
Cannot build Java/Gradle applications in fakeroot

### ISSUE THREAD

**Issue by piegamesde** [actionless/pikaur#498]
```
pikaur -Vq
Pikaur v1.6.10
Pacman v5.2.1 - libalpm v12.0.1
```

##### [Optional] Prerequisites:

Set `AlwaysUseDynamicUsers = yes`. This is not an option.

##### Attached log:

```
~ » pikaur -S blockmap-git --verbose --pikaur-debug

=> sudo /usr/bin/pikaur -S blockmap-git --verbose --pikaur-debug --pikaur-config ~/.config/pikaur.conf
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['blockmap-git']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync blockmap-git --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for aur_packages_versionmatchers=['blockmap-git']... self.aur_updates_install_info=[]
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=blockmap-git
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "blockmap-git" 2.0.0.r6.a900ba5-2 -> 2.0.0.r6.a900ba5-2>]
Resolving AUR dependencies...
=> pacman --color=always --deptest java-runtime>=12 hicolor-icon-theme archlinux-java-run sh java-environment>=12 git

:: AUR package will be installed:
 blockmap-git                          2.0.0.r6.a900ba5-2   -> 2.0.0.r6.a900ba5-2

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> Y
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/blockmap-git pull origin master
=> pacman --color=always --deptest java-runtime>=12 hicolor-icon-theme archlinux-java-run sh
=> pacman --color=always --deptest java-environment>=12 git
looking for conflicting AUR packages...
:: warning: Not showing diff for blockmap-git package (installing for the first time)
Do you want to edit PKGBUILD for blockmap-git package? [Y/n] n

:: debug: Gonna build self.package_builds_by_name={'blockmap-git': <pikaur.build.PackageBuild object at 0x7f6e7b0e02e0>}
:: debug: Gonna build pkg_build.package_names=['blockmap-git']
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp cp -r /var/cache/private/pikaur/aur_repos/blockmap-git/BlockMap.desktop /var/cache/private/pikaur/aur_repos/blockmap-git/PKGBUILD /var/cache/private/pikaur/aur_repos/blockmap-git/blockmap-gui.sh /var/cache/private/pikaur/aur_repos/blockmap-git/blockmap.sh /var/cache/private/pikaur/aur_repos/blockmap-git/.SRCINFO /var/cache/private/pikaur/aur_repos/blockmap-git/.gitignore /var/cache/private/pikaur/build/blockmap-git/
:: Downloading the latest sources for a devel package blockmap-git...
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/blockmap-git makepkg --nobuild --noprepare --nocheck --nodeps
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/blockmap-git makepkg --printsrcinfo -p PKGBUILD
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/blockmap-git makepkg --packagelist

:: Starting the build:
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/blockmap-git makepkg --force
Running as unit: run-u459.service
Press ^] three times within 1s to disconnect TTY.
==> Making package: blockmap-git 2.0.0.r6.a900ba5-2 (Thu 25 Jun 2020 01:20:56 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating blockmap-git git repo...
Fetching origin
  -> Found blockmap.sh
  -> Found blockmap-gui.sh
  -> Found BlockMap.desktop
==> Validating source files with sha512sums...
    blockmap-git ... Skipped
    blockmap.sh ... Passed
    blockmap-gui.sh ... Passed
    BlockMap.desktop ... Passed
==> Extracting sources...
  -> Creating working copy of blockmap-git git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Using JDK from /usr/lib/jvm/java-14-openjdk to build JabRef.
Exception in thread "main" java.lang.RuntimeException: Could not create parent directory for lock file /.gradle/wrapper/dists/gradle-6.3-bin/8tpu6egwsccjzp10c1jckl0rx/gradle-6.3-bin.zip.lck
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
==> ERROR: A failure occurred in build().
    Aborting...
Finished with result: exit-code
Main processes terminated with: code=exited/status=4
Service runtime: 2.290s

Command 'systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/blockmap-git makepkg --force' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
[e] edit PKGBUILD
------------------------
[s] skip building this package
[a] abort building all the packages
> a
```

**Comment by actionless** [comment]
if the issue is still reproducible when you running manually the `systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/blockmap-git makepkg --force` command -- pikaur have nothing to do with that

**Comment by actionless** [comment]
i believe, you just need to find a way to tell gradle to not use `/root/.gradle` directory which SystemD-DynUsers have no rights to write to
