### ISSUE TITLE
Trying to edit PKGBUILD after "Try recovering?" crashes

### ISSUE THREAD

**Issue by HanFox** [actionless/pikaur#501]
```
pikaur -Vq
Pikaur v1.6.10
Pacman v5.2.1 - libalpm v12.0.1
```

##### [Optional] Prerequisites:
N/A

##### Attached log:

```
pikaur -Syu --verbose --pikaur-debug

=> GET https://www.archlinux.org/feeds/news/
=> sudo pacman --color=always --sync --refresh
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date

:: Starting full AUR upgrade...
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=[]
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

Reading repository package databases...
Reading local package database...
:: debug: install_info_fetcher: Gonna get repo pkgs install info...
=> pacman --color=always --sync --sysupgrade --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for aur_packages_versionmatchers=[]... self.aur_updates_install_info=[]
Reading AUR packages info...
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=all-repository-fonts&arg[]=artwiz-fonts&arg[]=birdtray&arg[]=corectrl&arg[]=datagrip&arg[]=datagrip-jre&arg[]=dcaenc&arg[]=downgrade&arg[]=dxvk-bin&arg[]=fonts-tlwg&arg[]=gamemode&arg[]=gamin&arg[]=gconf&arg[]=gitkraken&arg[]=glib&arg[]=hamsket-nightly-bin&arg[]=jre8&arg[]=kalu-kde&arg[]=lib32-check&arg[]=lib32-gamemode&arg[]=lib32-libevdev&arg[]=lib32-mangohud-git&arg[]=libclc-git&arg[]=libunicodenames&arg[]=mangohud-git&arg[]=mcpelauncher-hx-script&arg[]=mcpelauncher-linux-git&arg[]=mcpelauncher-msa-git&arg[]=mcpelauncher-msa-ui-qt-git&arg[]=mcpelauncher-ui-git&arg[]=minecraft-launcher&arg[]=monogame-bin&arg[]=mpc-qt-git&arg[]=mpdris2&arg[]=multimc5&arg[]=openttd-jgrpp&arg[]=osl&arg[]=pamac-classic&arg[]=pcloud-drive&arg[]=phpstorm&arg[]=pikaur&arg[]=plasma5-applets-netspeed&arg[]=protontricks&arg[]=python-pygdbmi&arg[]=python-vdf&arg[]=python2-mutagen&arg[]=samrewritten-git&arg[]=spotify&arg[]=statusnotifier&arg[]=ttf-cheapskate&arg[]=ttf-freebanglafont&arg[]=ttf-mph-2b-damase&arg[]=ttf-ms-fonts&arg[]=ttf-ubraille&arg[]=virtualbox-ext-oracle&arg[]=vulkan-caps-viewer
:: Ignoring package update mcpelauncher-linux-git (stable.r12.g57f6253-1 => v0.1.beta.2.r11.gc2a2f53-1)
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "all-repository-fonts" 20200616-1 -> 20200630-2>, <InstallInfo "minecraft-launcher" 2.1.15166-1 -> 2.1.15852-1>, <InstallInfo "ttf-mph-2b-damase" 001.000.4.dfsg.2-7 -> 001.000.4.dfsg.2-8>]
Resolving AUR dependencies...
=> pacman --color=always --deptest adobe-source-code-pro-fonts adobe-source-han-sans-cn-fonts adobe-source-han-sans-hk-fonts adobe-source-han-sans-jp-fonts adobe-source-han-sans-kr-fonts adobe-source-han-sans-otc-fonts adobe-source-han-sans-tw-fonts adobe-source-han-serif-cn-fonts adobe-source-han-serif-jp-fonts adobe-source-han-serif-kr-fonts adobe-source-han-serif-otc-fonts adobe-source-han-serif-tw-fonts adobe-source-sans-pro-fonts adobe-source-serif-pro-fonts awesome-terminal-fonts bdf-unifont cantarell-fonts dina-font font-bh-ttf gentium-plus-font gnu-free-fonts gsfonts inter-font noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra opendesktop-fonts otf-cormorant otf-fantasque-sans-mono otf-fira-mono otf-fira-sans otf-font-awesome otf-ipaexfont otf-ipafont otf-ipamjfont otf-latin-modern otf-latinmodern-math otf-overpass powerline-fonts tamsyn-font terminus-font terminus-font-otb tex-gyre-fonts ttf-anonymous-pro ttf-arphic-ukai ttf-arphic-uming ttf-baekmuk ttf-bitstream-vera ttf-caladea ttf-carlito ttf-cascadia-code ttf-cormorant ttf-croscore ttf-dejavu ttf-droid ttf-fantasque-sans-mono ttf-fira-code ttf-fira-mono ttf-fira-sans ttf-font-awesome ttf-hack ttf-hanazono ttf-hannom ttf-ibm-plex ttf-inconsolata ttf-indic-otf ttf-ionicons ttf-jetbrains-mono ttf-joypixels ttf-junicode ttf-khmer ttf-lato ttf-liberation ttf-linux-libertine ttf-linux-libertine-g ttf-nerd-fonts-symbols ttf-opensans ttf-proggy-clean ttf-roboto ttf-roboto-mono ttf-sazanami ttf-tibetan-machine ttf-ubuntu-font-family wqy-bitmapfont wqy-microhei wqy-microhei-lite wqy-zenhei xorg-fonts-100dpi xorg-fonts-75dpi xorg-fonts-cyrillic xorg-fonts-misc xorg-fonts-type1
=> pacman --color=always --deptest xorg-fonts-encodings xorg-font-utils fontconfig
=> pacman --color=always --deptest java-runtime xorg-xrandr libxss libx11 libxcb alsa-lib gtk2 gtk3 gconf libxtst nss
=> pacman --color=always --sync --print-format=%% xorg-font-utils
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=xorg-font-utils
=> pacman --color=always --deptest xorg-font-utils
:: error: Can't resolve dependencies for AUR package 'ttf-mph-2b-damase':
:: error: Dependencies missing for ttf-mph-2b-damase
:: warning: Following package cannot be found in AUR:
    xorg-font-utils    
:: Try recovering?
[e] edit PKGBUILD
[s] skip this package
[A] abort
> e
=> git -C /home/hanfox/.local/share/pikaur/aur_repos/ttf-mph-2b-damase pull origin master
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 246, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 67, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 170, in get_all_packages_info
    self.get_aur_deps_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 450, in get_aur_deps_info
    self.aur_deps_relations = find_aur_deps(all_aur_pkgs)
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 249, in find_aur_deps
    raise exc
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 244, in find_aur_deps
    results = request.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 181, in find_missing_deps_for_aur_pkg
    handle_not_found_aur_pkgs(
  File "/usr/lib/python3.8/site-packages/pikaur/aur_deps.py", line 99, in handle_not_found_aur_pkgs
    raise PackagesNotFoundInAUR(
pikaur.exceptions.PackagesNotFoundInAUR: xorg-font-utils wanted by ttf-mph-2b-damase

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 435, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 324, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 135, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 259, in get_all_packages_info
    self.aur_pkg_not_found_prompt(pkg_name)
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 216, in aur_pkg_not_found_prompt
    self.package_builds_by_name.update(clone_aur_repos([pkg_name]))
  File "/usr/lib/python3.8/site-packages/pikaur/build.py", line 741, in clone_aur_repos
    raise CloneError(
pikaur.exceptions.CloneError
```

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
