### ISSUE TITLE
Edited PKGBUILD can't be restored to original PKGBUILD without manual intervention

### ISSUE THREAD

**Issue by Meister1593** [actionless/pikaur#518]
```
Pikaur v1.6.12
Pacman v5.2.2 - libalpm v12.0.2
```

##### Prerequisites:
Basically, i wanted to install one package (turbovnc) from AUR, and i had one error. I thought maybe edited PKGBUILD to download older version would help (it didn't). Then i decided to revert everything back to normal.
This is where it became difficult. I've tried doing `pikaur -Scc`, deleting `~/.cache/pikaur/build` folder, but every time it tried installing same package it used edited PKGBUILD, even if it would say it's new.

P.S I found that turbovnc files are presented at this path: `/home/plyshka/.local/share/pikaur/aur_repos/turbovnc`, is there any way to clean it with only pikaur?

##### Attached log:

```
plyshka:~$ pikaur -S turbovnc --verbose --pikaur-debug
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['turbovnc']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync turbovnc --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['turbovnc']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'turbovnc': <VersionMatcher turbovnc['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=turbovnc
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "turbovnc"   -> 2.2.5-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest libxaw libxt libxi libxcursor libjpeg-turbo java-environment>=8 openssl-1.0 cmake rsync

:: AUR package will be installed:
 turbovnc                                         -> 2.2.5-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
=> git -C /home/plyshka/.local/share/pikaur/aur_repos/turbovnc pull origin master
=> pacman --color=always --deptest libxaw libxt libxi libxcursor libjpeg-turbo java-environment>=8 openssl-1.0
=> pacman --color=always --deptest cmake rsync
looking for conflicting AUR packages...
:: warning: Not showing diff for turbovnc package (installing for the first time)
Do you want to edit PKGBUILD for turbovnc package? [Y/n] n

:: debug: Gonna build self.package_builds_by_name={'turbovnc': <pikaur.build.PackageBuild object at 0x7f1978131fd0>}
:: debug: Gonna build pkg_build.package_names=['turbovnc']
=> mkdir -p /home/plyshka/.cache/pikaur/build/turbovnc
=> cp -r /home/plyshka/.local/share/pikaur/aur_repos/turbovnc/vncserver.service /home/plyshka/.local/share/pikaur/aur_repos/turbovnc/PKGBUILD /home/plyshka/.local/share/pikaur/aur_repos/turbovnc/.SRCINFO /home/plyshka/.local/share/pikaur/aur_repos/turbovnc/.gitignore /home/plyshka/.cache/pikaur/build/turbovnc/
=> makepkg --packagelist

:: Starting the build:
=> makepkg --force
==> Making package: turbovnc 2.2.4-1 (Sun 18 Oct 2020 10:34:13 PM +04)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading turbovnc-2.2.4.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   425  100   425    0     0    506      0 --:--:-- --:--:-- --:--:--   506
100   339  100   339    0     0    203      0  0:00:01  0:00:01 --:--:--   843
  1 8803k    1 98062    0     0  31071      0  0:04:50  0:00:03  0:04:47  111k^CTraceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 421, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 310, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 762, in wait

    self._event.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
==> ERROR: Aborted by user! Exiting...
```

**Comment by Asraelite** [comment]
If this is the solution, perhaps it should be mentioned somewhere (FAQ, man page, help etc.)

I spent a long time searching for a proper way to do this before realizing there is none.

**Comment by actionless** [comment]
but what exactly do you propose instead?

**Comment by Asraelite** [comment]
I was just thinking something along the lines of what's currently in the **How to clean old or uninstalled AUR packages in ~/.cache/pikaur/pkg?** section of the FAQ. Just a brief mention that to clear edits, you `rm -r` the appropriate `aur_repos` folder.

I don't have any proposals for what actual functionality like `pikaur -Foobar turbovnc` would look like.

**Comment by actionless** [comment]
would you mind submitting a change to readme.md?
