### ISSUE TITLE
ValueError: list.remove(x): x not in list on -Su

### ISSUE THREAD

**Issue by hrehfeld** [actionless/pikaur#534]
##### Version
```
      /:}               _
     /--1             / :}
    /   |           / `-/
   |  ,  --------  /   /     Pikaur v1.6.13
   |'                 Y      (C) 2018-2020 Pikaur development team
  /                   l      Licensed under GPLv3
  l  /       \        l
  j  ●   .   ●        l      Pacman v5.2.2 - libalpm v12.0.2
 { )  ._,.__,   , -.  {      pyalpm v0.9.1
  У    \  _/     ._/   \
```

On a Raspberry PI (arm):
```
$ Linux a-hostname 4.19.73-1-ARCH #1 SMP PREEMPT Sat Sep 21 15:09:06 UTC 2019 armv7l GNU/Linux
```

##### Description:

Crash while updating system.

What flags can I use to find out which packages are causing this?

##### Attached log:

```
$ /usr/bin/pikaur --noconfirm --color=never --dynamic-users --cachedir /home/hrehfeld/.cache/pikaur/pkg -Su --devel --needed --dynamic-users
<snip>
:: AUR packages will be installed:
 homeshick-git                         1.1.0.r0.490013f-1   -> 2.0.0.r0.eea2fc5-1
 mopidy-alsamixer                      1.1.1-1              -> 2.0.0-3
 mopidy-internetarchive                0.5.0-1              -> 3.0.0-3
 python2-pyalsaaudio                   0.8.4-1              -> 0.9.0-1
 python2-configobj                     5.0.6-4              -> 5.0.6-6

:: New dependencies will be installed from AUR:
 python-pyalsaaudio (for mopidy-alsamixer)                  -> 0.9.0-1
 python-uritools (for mopidy-internetarchive)               -> 3.0.0-2

<snip>
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 426, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 312, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 994, in install_packages
    self.build_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 864, in build_packages
    packages_to_be_built.remove(_pkg_name)
ValueError: list.remove(x): x not in list

```

**Comment by actionless** [comment]
can you reproduce it when using `pikaur-git`?

if so please attach the log with `--pikaur-debug` flag as advised in the issue template

**Comment by vasiliu4556789** [comment]
A similar error

``File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
ModuleNotFoundError: No module named 'pikaur'

**Comment by vasiliu4556789** [comment]
rollback package version pikaur (1.6.13-2 => 1.6.13-1)  No errors

**Comment by hrehfeld** [comment]
Workaround: installing all packages from the above list manually with -S <pkg>. (no error happens on the update afterwards). I needed my system up.

Sadly, now the problem is gone, so I can't reproduce with debug flags. Maybe put those in the manpage? Also, put some text in the issue template, I thought i was supposed to put my *actual* commandline there...

**Comment by actionless** [comment]
do you at least haave the full version of the existing log above, but without `<snip>`s?

**Comment by hrehfeld** [comment]
Here are three:

```
sudo -S -p '[sudo] password: ' -H -u root sh -c '/usr/bin/pikaur --noconfirm --color=never -Su --needed --dynamic-users'
[sudo] password: :: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    config-concat
    gst-python2
    my-add-user-filesystem-music
    my-audio
    my-beets
    my-beets-web
    my-essential
    my-hostname
    my-mopidy
    my-network
    my-sshd-config-dir
    my-timezone-berlin
    python2-cachetools
    python2-pykka
    python2-pytoml
looking for conflicting AUR packages...
:: warning: python2-pyalsaaudio 0.8.4-1 local package is newer than in AUR (0.9.0-1) - skipping
:: Skipping review of PKGBUILD for mopidy-internetarchive package (--noconfirm)
:: Skipping review of PKGBUILD for python2-configobj package (--noconfirm)
:: Skipping review of PKGBUILD for python2-pyalsaaudio, python-pyalsaaudio package (--noconfirm)
:: Skipping review of PKGBUILD for homeshick-git package (--noconfirm)
:: Skipping review of PKGBUILD for python-uritools package (--noconfirm)
:: Skipping review of PKGBUILD for mopidy-alsamixer package (--noconfirm)
Reading local package database...
:: warning: python2-pyalsaaudio 0.8.4-1 local package is newer than in AUR (0.9.0-1) - skipping

:: Starting the build:
Running as unit: run-u796.service
    homeshick-git ... Skipped
Reset branch 'makepkg'
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 10.174s
:: Package python2-configobj is already built. Pass '--rebuild' flag to force the build.


:: Starting the build:
Running as unit: run-u802.service
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   121  100   121    0     0    373      0 --:--:-- --:--:-- --:--:--   373
100 21016    0 21016    0     0  24608      0 --:--:-- --:--:-- --:--:-- 67358
    v3.0.0.tar.gz ... Passed
no previously-included directories found matching 'docs/_build'
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 12.479s
:: Packages python2-pyalsaaudio, python-pyalsaaudio are already built. Pass '--rebuild' flag to force the build.

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 426, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 312, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 994, in install_packages
    self.build_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 864, in build_packages
    packages_to_be_built.remove(_pkg_name)
ValueError: list.remove(x): x not in list

```

```
sudo -S -p '[sudo] password: ' -H -u root sh -c '/usr/bin/pikaur --noconfirm --color=never --dynamic-users --cachedir /home/hrehfeld/.cache/pikaur/pkg -Su --devel --needed --dynamic-users'
[sudo] password: :: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    config-concat
    gst-python2
    my-add-user-filesystem-music
    my-audio
    my-beets
    my-beets-web
    my-essential
    my-hostname
    my-mopidy
    my-network
    my-sshd-config-dir
    my-timezone-berlin
    python2-cachetools
    python2-pykka
    python2-pytoml
looking for conflicting AUR packages...
:: warning: python2-pyalsaaudio 0.8.4-1 local package is newer than in AUR (0.9.0-1) - skipping
:: Skipping review of PKGBUILD for python2-pyalsaaudio, python-pyalsaaudio package (--noconfirm)
:: Skipping review of PKGBUILD for python2-configobj package (--noconfirm)
:: Skipping review of PKGBUILD for python-uritools package (--noconfirm)
:: Skipping review of PKGBUILD for homeshick-git package (--noconfirm)
:: Skipping review of PKGBUILD for mopidy-internetarchive package (--noconfirm)
:: Skipping review of PKGBUILD for mopidy-alsamixer package (--noconfirm)
Reading local package database...
:: warning: python2-pyalsaaudio 0.8.4-1 local package is newer than in AUR (0.9.0-1) - skipping
:: Package homeshick-git is already built. Pass '--rebuild' flag to force the build.

:: Package python2-configobj is already built. Pass '--rebuild' flag to force the build.

:: Packages python2-pyalsaaudio, python-pyalsaaudio are already built. Pass '--rebuild' flag to force the build.

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 426, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 312, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 994, in install_packages
    self.build_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 864, in build_packages
    packages_to_be_built.remove(_pkg_name)
ValueError: list.remove(x): x not in list

```


```
$ /usr/bin/pikaur --noconfirm --color=never -Su --needed --dynamic-users
[sudo] password for hrehfeld: 
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    config-concat
    gst-python2
    my-add-user-filesystem-music
    my-audio
    my-beets
    my-beets-web
    my-essential
    my-hostname
    my-mopidy
    my-network
    my-sshd-config-dir
    my-timezone-berlin
    python2-cachetools
    python2-pykka
    python2-pytoml
Resolving AUR dependencies...
looking for conflicting AUR packages...
:: Downloading the latest sources for a devel package homeshick-git...
:: warning: python2-pyalsaaudio 0.8.4-1 local package is newer than in AUR (0.9.0-1) - skipping
Not showing diff for mopidy-internetarchive package (--noconfirm)
:: Skipping review of PKGBUILD for mopidy-internetarchive package (--noconfirm)
Not showing diff for python2-pyalsaaudio, python-pyalsaaudio package (--noconfirm)
:: Skipping review of PKGBUILD for python2-pyalsaaudio, python-pyalsaaudio package (--noconfirm)
Not showing diff for python2-configobj package (--noconfirm)
:: Skipping review of PKGBUILD for python2-configobj package (--noconfirm)
Not showing diff for mopidy-alsamixer package (--noconfirm)
:: Skipping review of PKGBUILD for mopidy-alsamixer package (--noconfirm)
Not showing diff for homeshick-git package (--noconfirm)
:: Skipping review of PKGBUILD for homeshick-git package (--noconfirm)
Not showing diff for python-uritools package (--noconfirm)
:: Skipping review of PKGBUILD for python-uritools package (--noconfirm)

:: Starting full system upgrade...
 there is nothing to do
Reading local package database...
:: warning: python2-pyalsaaudio 0.8.4-1 local package is newer than in AUR (0.9.0-1) - skipping
:: Package python-uritools is already built. Pass '--rebuild' flag to force the build.

:: Packages python2-pyalsaaudio, python-pyalsaaudio are already built. Pass '--rebuild' flag to force the build.

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 426, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 312, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 994, in install_packages
    self.build_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 864, in build_packages
    packages_to_be_built.remove(_pkg_name)
ValueError: list.remove(x): x not in list
hrehfeld@musicpi /tmp/cm-aur_dhh52gl/pikaur
```

**Comment by actionless** [comment]
thanks! i'll try to figure out if it's helpful

**Comment by actionless** [comment]
i didnt managed to reproduce but hope this blind fix should help :)
