### ISSUE TITLE
pikaur fails when user is root and init system isn't systemd

### ISSUE THREAD

**Issue by ShyPixie** [actionless/pikaur#537]
```
Pikaur v1.6.15
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.2 
```

running from root account:

```
# pikaur
Traceback (most recent call last):
  File "/usr/sbin/pikaur", line 27, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 416, in main
    create_dirs()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 388, in create_dirs
    raise Exception(result)
Exception: InteractiveSpawn returned 1
```

however, it will work when running from a normal user even if the requested operation requires elevation.

**Comment by actionless** [comment]
not systemd-based root isolation is not currently supported, PRs welcome
