### ISSUE TITLE
Python SemLock: No such file or directory

### ISSUE THREAD

**Issue by Rio6** [actionless/pikaur#567]
```
$ pikaur -Vq
Pikaur v1.6.17.r6.g67a5014
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.2

$ uname -a
Linux tomato 5.12.2-artix1-1 #1 SMP PREEMPT Sat, 08 May 2021 13:47:18 +0000 x86_64 GNU/Linux
```

##### Description:

I've been getting the following error recently when using pikaur. I'm guessing it is more related to Python than pikaur, but this is the only program that gives me this error (so far). If you guys can give me some idea on how to debug this it'd be much appreciated.

Thanks!

##### Attached log:

```
$ pikaur -Ss
Searching... [-Traceback (most recent call last):
  File "/usr/bin/pikaur", line 36, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 345, in main
    cli_entry_point()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 265, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.9/site-packages/pikaur/search_cli.py", line 144, in cli_search_packages
    with ThreadPool() as pool:
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/usr/lib/python3.9/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 342, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory
```

It also happens when running with some other flags like `-Si` `-Qu`.

**Comment by Rio6** [comment]
3 minutes after I posted I found that it was caused by wrong permission on /dev/shm...

Issue solved
