### ISSUE TITLE
pikaur not working on WSL2

### ISSUE THREAD

**Issue by its5Q** [actionless/pikaur#569]
##### Description:
pikaur cannot run under WSL2 because of the usage of systemd-run command that doesn't work in WSL2

##### Attached log:

```
❯ pikaur --debug                                                                                                      ⏎
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 36, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 420, in main
    create_dirs()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 388, in create_dirs
    raise Exception(result)
Exception: InteractiveSpawn returned 1:
STDOUT:


STDERR:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by actionless** [comment]
you dont have systemd installed

**Comment by actionless** [comment]
also you running from root... :monkey: :boom:

**Comment by its5Q** [comment]
> you dont have systemd running 😃

oh well, I thought systemd doesn't work in WSL, my bad, it works after installing systemd...
