### ISSUE TITLE
pikaur -S UPPERCASEPACKAGENAME   gives error message that doesnt point the user in right direction.

### ISSUE THREAD

**Issue by rezad1393** [actionless/pikaur#592]
```
pikaur -Vq
pikaur -Vq
=> pacman --version
Pikaur v1.8
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6

```
pikaur -S LACT

running this command gives error as if the name of the program to be installed is interpreted as other than a program name

```
pikaur -S LACT --verbose --pikaur-debug
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-S', 'LACT', '--verbose', '--pikaur-debug']: cli_install_packages
[sudo] password for me: 
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['LACT']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync LACT --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['LACT']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'LACT': <VersionMatcher LACT['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=LACT
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 36, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 352, in main
    cli_entry_point()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 271, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.9/site-packages/pikaur/core.py", line 332, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.9/site-packages/pikaur/core.py", line 326, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 249, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.9/site-packages/pikaur/install_info_fetcher.py", line 68, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.9/site-packages/pikaur/install_info_fetcher.py", line 167, in get_all_packages_info
    self.get_aur_pkgs_info(self.not_found_repo_pkgs_names)
  File "/usr/lib/python3.9/site-packages/pikaur/install_info_fetcher.py", line 379, in get_aur_pkgs_info
    if aur_packages_names_to_versions[aur_pkg.name](aur_pkg.version):
KeyError: 'lact'




```

**Comment by actionless** [comment]
that's because AUR RPC search is case-insensitive, i think what would be the correct way to handle this

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
