### ISSUE TITLE
Pikaur doesn't run with Pacman 6.x.x

### ISSUE THREAD

**Issue by TheArcaneBrony** [actionless/pikaur#594]
```
pikaur -Vq
doesnt work, pacman says 1.8-1
```

##### Description:
libalpm was updated to v13, so it cannot be imported anymore

##### Solution/workaround:
Update pyalm (`(sudo) pip install -U pyalm`)

##### Attached log:

```
pikaur -S my-precious-package --verbose --pikaur-debug
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 6, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 17, in <module>
    import pyalpm
ImportError: libalpm.so.12: cannot open shared object file: No such file or directory

```

**Comment by actionless** [comment]
does the same happen if you just run `python -c 'import pyalpm'` without involving pikaur?
