### ISSUE TITLE
pikaur cannot resolve depends on i686 in chroot environment

### ISSUE THREAD

**Issue by Hayao0819** [actionless/pikaur#601]
```
[aurbuild@Hayao-ArchLinux ~]$ pikaur -Vq
Pikaur v1.8
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

##### Description:
I have built a chroot environment for Arch Linux32 i686 on Arch Linux 64. 
Since yay is no longer available on i686, I'm trying to use pikaur instead. 
But pikaur doesn't seem to be able to resolve dependencies.
In addition, other packages may not be able to resolve dependencies on AUR.

##### Attached log:

```
[aurbuild@Hayao-ArchLinux ~]$ LANG=C pikaur -S alterlinux-medit-themes --noconfirm --noedit --nodiff  --pikaur-debug
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-S', 'alterlinux-medit-themes', '--noconfirm', '--noedit', '--nodiff', '--pikaur-debug']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['alterlinux-medit-themes']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync --noconfirm alterlinux-medit-themes --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['alterlinux-medit-themes']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'alterlinux-medit-themes': <VersionMatcher alterlinux-medit-themes['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=alterlinux-medit-themes
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "alterlinux-medit-themes"   -> r19.67f0543-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest medit git
=> pacman --color=always --sync --print-format=%% medit
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=medit
=> pacman --color=always --deptest libsm pygtk intltool python
=> pacman --color=always --sync --print-format=%% pygtk intltool
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pygtk
=> pacman --color=always --deptest libglade python2-cairo python2-gobject2 python2-numpy
=> pacman --color=always --sync --print-format=%% python2-numpy python2-gobject2 python2-cairo libglade
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=python2-gobject2
=> pacman --color=always --deptest glib2 libffi python2 git
=> pacman --color=always --sync --print-format=%% python2
=> pacman --color=always --deptest libsm pygtk intltool python
=> pacman --color=always --deptest libglade python2-cairo python2-gobject2 python2-numpy
=> pacman --color=always --deptest medit git
=> pacman --color=always --deptest glib2 libffi python2 git
Reading repository package databases...
Reading repository package databases...
=> pacman --color=always --sync python2 --print-format %r/%n
Reading repository package databases...
=> pacman --color=always --sync intltool --print-format %r/%n
=> pacman --color=always --sync libglade --print-format %r/%n
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 36, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 352, in main
    cli_entry_point()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 271, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.9/site-packages/pikaur/core.py", line 332, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.9/site-packages/pikaur/core.py", line 326, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 249, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
  File "/usr/lib/python3.9/site-packages/pikaur/install_info_fetcher.py", line 68, in __init__
    self.get_all_packages_info()
  File "/usr/lib/python3.9/site-packages/pikaur/install_info_fetcher.py", line 176, in get_all_packages_info
    self.get_repo_deps_info()
  File "/usr/lib/python3.9/site-packages/pikaur/install_info_fetcher.py", line 344, in get_repo_deps_info
    new_dep_version_matchers = find_repo_deps_of_aur_pkgs(all_aur_pkgs)
  File "/usr/lib/python3.9/site-packages/pikaur/aur_deps.py", line 361, in find_repo_deps_of_aur_pkgs
    new_dep_names += result.get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/site-packages/pikaur/aur_deps.py", line 343, in _find_repo_deps_of_aur_pkg
    PackageDB.find_repo_package(version_matcher.line)
  File "/usr/lib/python3.9/site-packages/pikaur/pacman.py", line 495, in find_repo_package
    found_pkgs = [all_repo_pkgs[result.full_name] for result in results]
  File "/usr/lib/python3.9/site-packages/pikaur/pacman.py", line 495, in <listcomp>
    found_pkgs = [all_repo_pkgs[result.full_name] for result in results]
KeyError: 'extra/libglade'
[aurbuild@Hayao-ArchLinux ~]$
```

**Comment by actionless** [comment]
and what's the output for?

```
pacman --color=always --sync libglade --print-format '%r/%n'
```
