### ISSUE TITLE
pikaur installation failure?

### ISSUE THREAD

**Issue by SolarAquarion** [actionless/pikaur#63]
Traceback (most recent call last):
  File "/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 342, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 294, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 64, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 131, in __init__
    self.build_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 525, in build_packages
    repo_status.build(self.args, self.package_builds)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 395, in build
    self._set_built_package_path()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 322, in _set_built_package_path
    config_path=os.path.join(dest_dir, 'PKGBUILD')
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 295, in get
    value = cls.get_config(config_path=config_path).get(key)
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 284, in get_config
    with open(config_path) as config_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/pacman/custom/PKGBUILD'

**Comment by actionless** [comment]
and what the command caused that output?

**Comment by SolarAquarion** [comment]
pikaur -S flite1-patched when you have aurutils set up

**Comment by actionless** [comment]
please test
