### ISSUE TITLE
Pikaur fails during full system update

### ISSUE THREAD

**Issue by sdht0** [actionless/pikaur#639]
```
pikaur -Vq

Pikaur vr2019.20220319.3bdb370
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

##### Description:

Doing a full system update using pikaur is failing as shown below. It possibly could be because I have a local repo that I use for locally built packages. The error goes away after I use `pacman -Syu` first to update all repo packages.

##### Attached log:

```
pikaur -Syu --needed --verbose --pikaur-debug

:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-Syu', '--needed', '--verbose', '--pikaur-debug']: cli_install_packages
=> GET https://www.archlinux.org/feeds/news/
=> sudo pacman --color=always --sync --refresh
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 local-repo is up to date

:: Starting full AUR upgrade...
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=[]
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

Reading repository package databases...
Reading local package database...
:: debug: install_info_fetcher: Gonna get repo pkgs install info...
=> pacman --color=always --sync --sysupgrade --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=[]
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={}
:: debug: install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[]
    not_found_aur_pkgs=[]

Reading AUR packages info...
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=activitywatch-bin&arg[]=aha&arg[]=bibtool-git&arg[]=mullvad-vpn-beta-bin&arg[]=slack-desktop&arg[]=teams&arg[]=ttf-meslo-nerd-font-powerlevel10k&arg[]=visual-studio-code-bin&arg[]=write-good&arg[]=zfs-dkms&arg[]=zfs-utils&arg[]=zoom
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<AURInstallInfo "zoom" 5.9.6-1 -> 5.10.0-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest fontconfig glib2 libpulse libsm ttf-font libx11 libxtst libxcb libxcomposite libxfixes libxi libxcursor libxkbcommon-x11 libxrandr libxrender libxshmfence libxslt mesa nss xcb-util-image xcb-util-keysyms dbus ibus
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 36, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 354, in main
    cli_entry_point()
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 271, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 362, in run_with_sudo_loop
    raise catched_exc
  File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 356, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 168, in main_sequence
    self.get_all_packages_info()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 296, in get_all_packages_info
    (install_info in self.install_info.aur_updates_install_info)
  File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 48, in __eq__
    raise TypeError(
TypeError: 'RepoInstallInfo' is not an instance of 'AURInstallInfo'
```

**Comment by actionless** [comment]
afc18e7 is neither stable nor latest git revision, could you try with the latest first?

**Comment by sdht0** [comment]
Sorry I missed this notification.

I tried with Pikaur vr2019.20220319.3bdb370 and the error persists.

**Comment by actionless** [comment]
please paste the traceback from the version g3bdb370

**Comment by sdht0** [comment]
I updated the first comment.

I tried to reproduce the bug consistently and it seems to occur only where there is atleast one package update from **both** my local-repo and AUR. As soon as I update all packages from the local-repo (or AUR) using pacman, the bug in pikaur disappears.

**Comment by actionless** [comment]
the case of local repo is not tested, now it makes sense why i couldnt reproduce it 👍

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by sdht0** [comment]
Finally got a chance to test and it works. Thanks a lot!

**Comment by actionless** [comment]
thanks for testing @sdht0
