### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/tmp/pikaur_build_deps.lock' when using pikaur with multiple non-root users (i.e. with ansible )

### ISSUE THREAD

**Issue by moormaster** [actionless/pikaur#685]
```
$ pikaur -Vq
Pikaur v1.14.4
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### [Optional] Prerequisites:
- have a user aur_builder set up ( i.e. to be able to install aur packages with ansible - as recommended here https://wiki.archlinux.org/title/Ansible#AUR )

##### Description:
- install any aur package with aur_builder user
- install (the same or another) aur package with local user
-> Permission error on .lock file

Would it be possible for pikaur to simply delete the lock file after releasing the lock?

```
$ sudo -u aur_builder pikaur -S zeal --noconfirm
...
$ pikaur -S zeal --noconfirm 
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
looking for conflicting AUR packages...
Not showing diff for zeal package (--noconfirm)
:: Skipping review of PKGBUILD for zeal package (--noconfirm)

  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 369, in main
    cli_entry_point()
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 272, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 423, in run_with_sudo_loop
    raise catched_exc
  File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 417, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 136, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 186, in __init__
    self.main_sequence()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 205, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 1087, in install_packages
    self.build_packages()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 916, in build_packages
    pkg_build.build(
  File "/usr/lib/python3.10/site-packages/pikaur/build.py", line 818, in build
    self.install_all_deps(all_package_builds)
  File "/usr/lib/python3.10/site-packages/pikaur/build.py", line 569, in install_all_deps
    with FileLock(BUILD_DEPS_LOCK):
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 17, in __init__
    self.lock_file = open(  # pylint: disable=consider-using-with

PermissionError: [Errno 13] Permission denied: '/tmp/pikaur_build_deps.lock'
Exception ignored in: <function FileLock.__del__ at 0x7f0fee9ec4c0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 43, in __del__
    self.__exit__()
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 39, in __exit__
    if not self.lock_file.closed:
AttributeError: 'FileLock' object has no attribute 'lock_file'
```

##### Attached log:

```
$ pikaur -S zeal --noconfirm --verbose --pikaur-debug
:: debug: main: Setting stdout to utf-8...
:: debug: main: already set - nothing to do
:: debug: main: Setting stderr to utf-8...
:: debug: main: already set - nothing to do
:: debug: main: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-S', 'zeal', '--noconfirm', '--verbose', '--pikaur-debug']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['zeal']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
:: debug: install_info_fetcher: Checking if 'pkg_lines=['zeal']' is installable:
=> pacman --color=always --sync --noconfirm zeal --print-format %r/%n
:: debug: install_info_fetcher: Check failed - gonna check it separately:
=> pacman --color=always --sync --noconfirm zeal --print-format %r/%n
:: debug: install_info_fetcher: Checking if 'zeal' exists in the repo:
=> pacman --color=always --sync --noconfirm zeal --print-format %r/%n --nodeps --nodeps
:: debug: install_info_fetcher:   'zeal' is NOT found in the repo.
:: debug: install_info_fetcher: Check partially passed - gonna get install infos:
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['zeal']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'zeal': <VersionMatcher zeal['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=zeal
=> pacman --color=always --sync --noconfirm zeal --print-format %r/%n --nodeps --nodeps
:: debug: install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[<AURPackageInfo "zeal" 0.6.1-3>]
    not_found_aur_pkgs=[]

:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<AURInstallInfo "zeal" 0.6.1-3 -> 0.6.1-3>]
Resolving AUR dependencies...
=> pacman --color=always --deptest qt5-webkit hicolor-icon-theme libarchive qt5-x11extras cmake ninja extra-cmake-modules
=> pacman --color=always --deptest qt5-webkit hicolor-icon-theme libarchive qt5-x11extras cmake ninja extra-cmake-modules
=> pacman --color=always --sync --print-format=%% --nodeps extra-cmake-modules
=> pacman --color=always --sync --print-format=%% --nodeps extra-cmake-modules
=> pacman --color=always --deptest qt5-webkit hicolor-icon-theme libarchive qt5-x11extras cmake ninja extra-cmake-modules
=> pacman --color=always --deptest qt5-webkit hicolor-icon-theme libarchive qt5-x11extras cmake ninja extra-cmake-modules
=> pacman --color=always --sync extra-cmake-modules --print-format %r/%n --nodeps --nodeps
=> pacman --color=always --sync extra-cmake-modules --print-format %r/%n --nodeps --nodeps
:: debug: install_info_fetcher: Checking if 'pkg_lines=['extra-cmake-modules']' is installable:
=> pacman --color=always --sync --noconfirm --needed extra-cmake-modules --print-format %r/%n
=> pacman --color=always --sync --noconfirm --needed extra-cmake-modules --print-format %r/%n
:: debug: install_info_fetcher: Check passed - gonna get install infos:
:: debug: install_cli: self.install_info.all_install_info_containers=([], [<RepoInstallInfo "extra-cmake-modules"  -> 5.100.0-1>], [], [], [], [], [<AURInstallInfo "zeal" 0.6.1-3 -> 0.6.1-3>], [])
=> git -C /home/moormaster/.local/share/pikaur/aur_repos/zeal pull origin master
=> git -C /home/moormaster/.local/share/pikaur/aur_repos/zeal pull origin master
=> pacman --color=always --deptest qt5-webkit hicolor-icon-theme libarchive qt5-x11extras
=> pacman --color=always --deptest qt5-webkit hicolor-icon-theme libarchive qt5-x11extras
=> pacman --color=always --deptest cmake ninja extra-cmake-modules
=> pacman --color=always --deptest cmake ninja extra-cmake-modules
looking for conflicting AUR packages...
=> pacman --color=always --deptest qt5-webkit hicolor-icon-theme libarchive qt5-x11extras cmake ninja extra-cmake-modules
=> pacman --color=always --deptest qt5-webkit hicolor-icon-theme libarchive qt5-x11extras cmake ninja extra-cmake-modules
Not showing diff for zeal package (--noconfirm)
:: Skipping review of PKGBUILD for zeal package (--noconfirm)

:: debug: install_cli: Gonna build self.package_builds_by_name={'zeal': <pikaur.build.PackageBuild object at 0x7f6b09e8f970>}
:: debug: install_cli: Gonna build pkg_build.package_names=['zeal']
=> mkdir -p /home/moormaster/.cache/pikaur/build/zeal
=> mkdir -p /home/moormaster/.cache/pikaur/build/zeal
=> cp -r /home/moormaster/.local/share/pikaur/aur_repos/zeal/github_pr-1218.patch /home/moormaster/.local/share/pikaur/aur_repos/zeal/PKGBUILD /home/moormaster/.local/share/pikaur/aur_repos/zeal/.SRCINFO /home/moormaster/.local/share/pikaur/aur_repos/zeal/.gitignore /home/moormaster/.cache/pikaur/build/zeal/
=> cp -r /home/moormaster/.local/share/pikaur/aur_repos/zeal/github_pr-1218.patch /home/moormaster/.local/share/pikaur/aur_repos/zeal/PKGBUILD /home/moormaster/.local/share/pikaur/aur_repos/zeal/.SRCINFO /home/moormaster/.local/share/pikaur/aur_repos/zeal/.gitignore /home/moormaster/.cache/pikaur/build/zeal/
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 369, in main
    cli_entry_point()
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 272, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 423, in run_with_sudo_loop
    raise catched_exc
  File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 417, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 136, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 186, in __init__
    self.main_sequence()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 205, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 1087, in install_packages
    self.build_packages()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 916, in build_packages
    pkg_build.build(
  File "/usr/lib/python3.10/site-packages/pikaur/build.py", line 818, in build
    self.install_all_deps(all_package_builds)
  File "/usr/lib/python3.10/site-packages/pikaur/build.py", line 569, in install_all_deps
    with FileLock(BUILD_DEPS_LOCK):
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 17, in __init__
    self.lock_file = open(  # pylint: disable=consider-using-with

PermissionError: [Errno 13] Permission denied: '/tmp/pikaur_build_deps.lock'
:: debug: main: Restoring stdout...
:: debug: main: nothing to do
:: debug: main: Restoring stderr...
:: debug: main: nothing to do
Exception ignored in: <function FileLock.__del__ at 0x7f6b09de84c0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 43, in __del__
    self.__exit__()
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 39, in __exit__
    if not self.lock_file.closed:
AttributeError: 'FileLock' object has no attribute 'lock_file'
```

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by moormaster** [comment]
Works for me, thanks!
