### ISSUE TITLE
Running pikaur as root and installing a package from AUR fails if the directory `/root/.cache` doesn't exist.

### ISSUE THREAD

**Issue by Windore** [actionless/pikaur#697]
```
pikaur -Vq
Pikaur v1.14.6
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### Description:

When running pikaur as root and installing a package from AUR, pikaur raises an AttributeError and fails to install the package if the directory `/root/.cache` does not exist.

After creating the `/root/.cache/` directory manually, pikaur works as expected.

##### Attached log:

```
doas pikaur -S --rebuild pikaur --verbose --pikaur-debug
:: debug: main: Setting stdout to utf-8...
:: debug: main: already set - nothing to do
:: debug: main: Setting stderr to utf-8...
:: debug: main: already set - nothing to do
=> /usr/sbin/systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
=> /usr/sbin/systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
:: debug: main: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-S', '--rebuild', 'pikaur', '--verbose', '--pikaur-debug']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['pikaur']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]
 
:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
:: debug: install_info_fetcher: Checking if 'pkg_lines=['pikaur']' is installable:
=> pacman --color=always --sync pikaur --print-format %r/%n
:: debug: install_info_fetcher: Check failed - gonna check it separately:
=> pacman --color=always --sync pikaur --print-format %r/%n
:: debug: install_info_fetcher: Checking if 'pikaur' exists in the repo:
=> pacman --color=always --sync pikaur --print-format %r/%n --nodeps --nodeps
:: debug: install_info_fetcher:   'pikaur' is NOT found in the repo.
:: debug: install_info_fetcher: Check partially passed - gonna get install infos:
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['pikaur']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'pikaur': <VersionMatcher pikaur['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pikaur
:: debug: install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[<AURPackageInfo "pikaur" 1.14.6-1>]
    not_found_aur_pkgs=[]
 
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<AURInstallInfo "pikaur" 1.14.6-1 -> 1.14.6-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest pyalpm git python-wheel python-build python-installer python-setuptools python-markdown-it-py
=> pacman --color=always --deptest pyalpm git python-wheel python-build python-installer python-setuptools python-markdown-it-py
=> pacman --color=always --sync --print-format=%% --nodeps python-installer python-markdown-it-py python-wheel python-build
=> pacman --color=always --sync --print-format=%% --nodeps python-installer python-markdown-it-py python-wheel python-build
=> pacman --color=always --deptest pyalpm git python-wheel python-build python-installer python-setuptools python-markdown-it-py
=> pacman --color=always --deptest pyalpm git python-wheel python-build python-installer python-setuptools python-markdown-it-py
=> pacman --color=always --sync python-wheel --print-format %r/%n --nodeps --nodeps
=> pacman --color=always --sync python-wheel --print-format %r/%n --nodeps --nodeps
=> pacman --color=always --sync python-build --print-format %r/%n --nodeps --nodeps
=> pacman --color=always --sync python-build --print-format %r/%n --nodeps --nodeps
=> pacman --color=always --sync python-installer --print-format %r/%n --nodeps --nodeps
=> pacman --color=always --sync python-installer --print-format %r/%n --nodeps --nodeps
=> pacman --color=always --sync python-markdown-it-py --print-format %r/%n --nodeps --nodeps
=> pacman --color=always --sync python-markdown-it-py --print-format %r/%n --nodeps --nodeps
:: debug: install_info_fetcher: Checking if 'pkg_lines=['python-build', 'python-installer', 'python-markdown-it-py', 'python-wheel']' is installable:
=> pacman --color=always --sync --needed python-build python-installer python-markdown-it-py python-wheel --print-format %r/%n
=> pacman --color=always --sync --needed python-build python-installer python-markdown-it-py python-wheel --print-format %r/%n
:: debug: install_info_fetcher: Check passed - gonna get install infos:
=> pacman --color=always --sync pikaur --print-format %r/%n --nodeps --nodeps
:: debug: install_cli: self.install_info.all_install_info_containers=([], [<RepoInstallInfo "python-pep517"  -> 0.13.0-1>, <RepoInstallInfo "python-build"  -> 0.9.0-1>, <RepoInstallInfo "python-installer"  -> 0.6.0-1>, <RepoInstallInfo "python-uc-micro-py"  -> 1.0.1-3>, <RepoInstallInfo "python-mdurl"  -> 0.1.2-2>, <RepoInstallInfo "python-markdown-it-py"  -> 2.1.0-1>, <RepoInstallInfo "python-wheel"  -> 0.38.4-1>], [], [], [], [], [<AURInstallInfo "pikaur" 1.14.6-1 -> 1.14.6-1>], [])
 
:: New dependencies will be installed from repository:
 python-build (for pikaur)                                  -> 0.9.0-1
 python-installer (for pikaur)                              -> 0.6.0-1
 python-markdown-it-py (for pikaur)                         -> 2.1.0-1
 python-mdurl (for python-markdown-it-py)                   -> 0.1.2-2
 python-pep517 (for python-build)                           -> 0.13.0-1
 python-uc-micro-py (for python-mdurl)                      -> 1.0.1-3
 python-wheel (for pikaur)                                  -> 0.38.4-1
 
:: AUR package will be installed:
 pikaur                                1.14.6-1             -> 1.14.6-1
 
:: debug: prompt: Gonna get input from user...
:: debug: prompt_nolock: Restoring TTY...
:: debug: prompt_nolock: Using standard input reader...
:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
:: debug: prompt_nolock: Reverting to prev TTY state...
:: debug: prompt: Got answer: 'y'
=> /usr/sbin/systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/pikaur pull origin master
=> /usr/sbin/systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/pikaur pull origin master
=> pacman --color=always --deptest pyalpm git
=> pacman --color=always --deptest pyalpm git
=> pacman --color=always --deptest python-wheel python-build python-installer python-setuptools python-markdown-it-py
=> pacman --color=always --deptest python-wheel python-build python-installer python-setuptools python-markdown-it-py
looking for conflicting AUR packages...
=> pacman --color=always --deptest pyalpm git python-wheel python-build python-installer python-setuptools python-markdown-it-py
=> pacman --color=always --deptest pyalpm git python-wheel python-build python-installer python-setuptools python-markdown-it-py
:: warning: Not showing diff for pikaur package (already reviewed)
:: debug: prompt: Gonna get input from user...
:: debug: prompt_nolock: Restoring TTY...
:: debug: prompt_nolock: Using standard input reader...
Do you want to edit PKGBUILD for pikaur package? [y/N] n
:: debug: prompt_nolock: Reverting to prev TTY state...
:: debug: prompt: Got answer: 'n'
 
:: debug: install_cli: Gonna build self.package_builds_by_name={'pikaur': <PackageBuild "pikaur" ['pikaur']>}
:: debug: install_cli: Gonna build pkg_build.package_names=['pikaur']
=> /usr/sbin/systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp mkdir -p /var/cache/private/pikaur/build/pikaur
=> /usr/sbin/systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp mkdir -p /var/cache/private/pikaur/build/pikaur
=> /usr/sbin/systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp cp -r /var/cache/private/pikaur/aur_repos/pikaur/last_installed.txt /var/cache/private/pikaur/aur_repos/pikaur/CHANGELOG /var/cache/private/pikaur/aur_repos/pikaur/PKGBUILD /var/cache/private/pikaur/aur_repos/pikaur/.SRCINFO /var/cache/private/pikaur/build/pikaur/
=> /usr/sbin/systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp cp -r /var/cache/private/pikaur/aur_repos/pikaur/last_installed.txt /var/cache/private/pikaur/aur_repos/pikaur/CHANGELOG /var/cache/private/pikaur/aur_repos/pikaur/PKGBUILD /var/cache/private/pikaur/aur_repos/pikaur/.SRCINFO /var/cache/private/pikaur/build/pikaur/
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 369, in main
    cli_entry_point()
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 269, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 136, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 185, in __init__
    self.main_sequence()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 204, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 1084, in install_packages
    self.build_packages()
  File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 913, in build_packages
    pkg_build.build(
  File "/usr/lib/python3.10/site-packages/pikaur/build.py", line 827, in build
    self.install_all_deps(all_package_builds)
  File "/usr/lib/python3.10/site-packages/pikaur/build.py", line 578, in install_all_deps
    with FileLock(BUILD_DEPS_LOCK):
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 21, in __enter__
    self.lock_file = open(
 
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/pikaur_build_deps.lock'
:: debug: main: Restoring stdout...
:: debug: main: nothing to do
:: debug: main: Restoring stderr...
:: debug: main: nothing to do
Exception ignored in: <function FileLock.__del__ at 0x7f3f2811f5b0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 48, in __del__
    self.__exit__()
  File "/usr/lib/python3.10/site-packages/pikaur/filelock.py", line 38, in __exit__
    if self.lock_file:
AttributeError: 'FileLock' object has no attribute 'lock_file'
```

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by Windore** [comment]
Thanks for the quick fix! It works now with `pikaur-git`.
