### ISSUE TITLE
Problem with building  pikaur on ArchLinux

### ISSUE THREAD

**Issue by entr0p1sta** [actionless/pikaur#703]
`==> Making package: pikaur 1.14.7-1 (Sat 18 Feb 2023 01:36:13 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found pikaur-1.14.7.tar.gz
==> Validating source files with b2sums...
    pikaur-1.14.7.tar.gz ... Passed
==> Extracting sources...
  -> Extracting pikaur-1.14.7.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
find pikaur -type f -name '*.py' \
	| xargs xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
........................ done.
msgfmt -o locale/fr.mo locale/fr.po
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
........................ done.
msgfmt -o locale/ru.mo locale/ru.po
test -f locale/pt.po || msginit --locale=pt --no-translator --input=locale/pikaur.pot --output=locale/pt.po
msgmerge --update locale/pt.po locale/pikaur.pot
....................................... done.
msgfmt -o locale/pt.mo locale/pt.po
test -f locale/pt_BR.po || msginit --locale=pt_BR --no-translator --input=locale/pikaur.pot --output=locale/pt_BR.po
msgmerge --update locale/pt_BR.po locale/pikaur.pot
........................ done.
msgfmt -o locale/pt_BR.mo locale/pt_BR.po
test -f locale/de.po || msginit --locale=de --no-translator --input=locale/pikaur.pot --output=locale/de.po
msgmerge --update locale/de.po locale/pikaur.pot
........................ done.
msgfmt -o locale/de.mo locale/de.po
test -f locale/is.po || msginit --locale=is --no-translator --input=locale/pikaur.pot --output=locale/is.po
msgmerge --update locale/is.po locale/pikaur.pot
........................ done.
msgfmt -o locale/is.mo locale/is.po
test -f locale/tr.po || msginit --locale=tr --no-translator --input=locale/pikaur.pot --output=locale/tr.po
msgmerge --update locale/tr.po locale/pikaur.pot
........................ done.
msgfmt -o locale/tr.mo locale/tr.po
test -f locale/da.po || msginit --locale=da --no-translator --input=locale/pikaur.pot --output=locale/da.po
msgmerge --update locale/da.po locale/pikaur.pot
........................ done.
msgfmt -o locale/da.mo locale/da.po
test -f locale/nl.po || msginit --locale=nl --no-translator --input=locale/pikaur.pot --output=locale/nl.po
msgmerge --update locale/nl.po locale/pikaur.pot
........................ done.
msgfmt -o locale/nl.mo locale/nl.po
test -f locale/es.po || msginit --locale=es --no-translator --input=locale/pikaur.pot --output=locale/es.po
msgmerge --update locale/es.po locale/pikaur.pot
........................ done.
msgfmt -o locale/es.mo locale/es.po
test -f locale/zh_CN.po || msginit --locale=zh_CN --no-translator --input=locale/pikaur.pot --output=locale/zh_CN.po
msgmerge --update locale/zh_CN.po locale/pikaur.pot
........................ done.
msgfmt -o locale/zh_CN.mo locale/zh_CN.po
test -f locale/it.po || msginit --locale=it --no-translator --input=locale/pikaur.pot --output=locale/it.po
msgmerge --update locale/it.po locale/pikaur.pot
........................ done.
msgfmt -o locale/it.mo locale/it.po
test -f locale/ja.po || msginit --locale=ja --no-translator --input=locale/pikaur.pot --output=locale/ja.po
msgmerge --update locale/ja.po locale/pikaur.pot
........................ done.
msgfmt -o locale/ja.mo locale/ja.po
test -f locale/uk.po || msginit --locale=uk --no-translator --input=locale/pikaur.pot --output=locale/uk.po
msgmerge --update locale/uk.po locale/pikaur.pot
........................ done.
msgfmt -o locale/uk.mo locale/uk.po
mkdir -p dist/usr/bin
sed \
	-e "s/%PYTHON_BUILD_VERSION%/$( /usr/bin/python -c 'import sys ; print(f"{sys.version_info.major}.{sys.version_info.minor}") ')/g" \
	packaging/usr/bin/pikaur > dist/usr/bin/pikaur
chmod +x dist/usr/bin/pikaur
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 68, in <module>
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 253, in finalize_options
    if pd is not None and pd.key == self.egg_name.lower():
AttributeError: 'PathDistribution' object has no attribute 'key'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by roussak** [comment]
I have the same issue while building the pikaur.

**Comment by jonasmalacofilho** [comment]
Related: https://github.com/pypa/setuptools/commit/c428a57352138d01c21064012091b9bde3017060

**Comment by roussak** [comment]
It looks like the issue was resolved with last python-setuptools update.

**Comment by entr0p1sta** [comment]
> It looks like the issue was resolved with last python-setuptools update.

ill will check it at home and mark it resolved if it will be ok

**Comment by entr0p1sta** [comment]
Problem solved after python-setuptools update
