### ISSUE TITLE
Pikaur 1.15 error because "Final" is not defined

### ISSUE THREAD

**Issue by dschopf** [actionless/pikaur#713]
```
$ pikaur -Vq
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 6, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.11/site-packages/pikaur/main.py", line 18, in <module>
    from .args import parse_args
  File "/usr/lib/python3.11/site-packages/pikaur/args.py", line 9, in <module>
    from .config import PikaurConfig
  File "/usr/lib/python3.11/site-packages/pikaur/config.py", line 93, in <module>
    class UpgradeSortingValues:
  File "/usr/lib/python3.11/site-packages/pikaur/config.py", line 94, in UpgradeSortingValues
    VERSION: Final = "1.15-dev"
             ^^^^^
NameError: name 'Final' is not defined
```

##### Description:
Install latest pikaur version via `pikaur -S pikaur`
Calling pikaur afterwards always leads to the crash shown above.

**Comment by dschopf** [comment]
Ok, you already seem to have fixed it, I will wait for a package bump.
