### ISSUE TITLE
Bug: markdown_it module not found

### ISSUE THREAD

**Issue by keilmillerjr** [actionless/pikaur#718]
##### Description:

`ModuleNotFoundError: No module named 'markdown_it'`

##### Updating pikaur from pikaur:

```
pikaur -Syu
[sudo] password for keiljr: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 pikaur                                1.15.1-1             -> 1.15.2-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
:: warning: Not showing diff for pikaur package (installing for the first time)
Do you want to edit PKGBUILD for pikaur package? [Y/n] n

:: Starting full system upgrade...
 there is nothing to do

:: Starting the build:
==> Making package: pikaur 1.15.2-1 (Mon May 22 02:42:06 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading pikaur-1.15.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2155k  100 2155k    0     0   664k      0  0:00:03  0:00:03 --:--:-- 1003k
==> Validating source files with b2sums...
    pikaur-1.15.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting pikaur-1.15.2.tar.gz with bsdtar
==> Starting build()...
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
find pikaur -type f -name '*.py' -print0 \
	| xargs --null xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
................................ done.
msgfmt -o locale/fr.mo locale/fr.po
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
................................ done.
msgfmt -o locale/ru.mo locale/ru.po
test -f locale/pt.po || msginit --locale=pt --no-translator --input=locale/pikaur.pot --output=locale/pt.po
msgmerge --update locale/pt.po locale/pikaur.pot
................................ done.
msgfmt -o locale/pt.mo locale/pt.po
test -f locale/pt_BR.po || msginit --locale=pt_BR --no-translator --input=locale/pikaur.pot --output=locale/pt_BR.po
msgmerge --update locale/pt_BR.po locale/pikaur.pot
................................... done.
msgfmt -o locale/pt_BR.mo locale/pt_BR.po
test -f locale/de.po || msginit --locale=de --no-translator --input=locale/pikaur.pot --output=locale/de.po
msgmerge --update locale/de.po locale/pikaur.pot
................................ done.
msgfmt -o locale/de.mo locale/de.po
test -f locale/is.po || msginit --locale=is --no-translator --input=locale/pikaur.pot --output=locale/is.po
msgmerge --update locale/is.po locale/pikaur.pot
................................. done.
msgfmt -o locale/is.mo locale/is.po
test -f locale/tr.po || msginit --locale=tr --no-translator --input=locale/pikaur.pot --output=locale/tr.po
msgmerge --update locale/tr.po locale/pikaur.pot
................................. done.
msgfmt -o locale/tr.mo locale/tr.po
test -f locale/da.po || msginit --locale=da --no-translator --input=locale/pikaur.pot --output=locale/da.po
msgmerge --update locale/da.po locale/pikaur.pot
................................. done.
msgfmt -o locale/da.mo locale/da.po
test -f locale/nl.po || msginit --locale=nl --no-translator --input=locale/pikaur.pot --output=locale/nl.po
msgmerge --update locale/nl.po locale/pikaur.pot
.................................. done.
msgfmt -o locale/nl.mo locale/nl.po
test -f locale/es.po || msginit --locale=es --no-translator --input=locale/pikaur.pot --output=locale/es.po
msgmerge --update locale/es.po locale/pikaur.pot
................................... done.
msgfmt -o locale/es.mo locale/es.po
test -f locale/zh_CN.po || msginit --locale=zh_CN --no-translator --input=locale/pikaur.pot --output=locale/zh_CN.po
msgmerge --update locale/zh_CN.po locale/pikaur.pot
................................. done.
msgfmt -o locale/zh_CN.mo locale/zh_CN.po
test -f locale/it.po || msginit --locale=it --no-translator --input=locale/pikaur.pot --output=locale/it.po
msgmerge --update locale/it.po locale/pikaur.pot
.................................... done.
msgfmt -o locale/it.mo locale/it.po
test -f locale/ja.po || msginit --locale=ja --no-translator --input=locale/pikaur.pot --output=locale/ja.po
msgmerge --update locale/ja.po locale/pikaur.pot
................................ done.
msgfmt -o locale/ja.mo locale/ja.po
test -f locale/uk.po || msginit --locale=uk --no-translator --input=locale/pikaur.pot --output=locale/uk.po
msgmerge --update locale/uk.po locale/pikaur.pot
.................................. done.
msgfmt -o locale/uk.mo locale/uk.po
/home/keiljr/.asdf/shims/python ./maintenance_scripts/pikaman.py README.md pikaur.1
Traceback (most recent call last):
  File "/home/keiljr/.cache/pikaur/build/pikaur/src/pikaur-1.15.2/./maintenance_scripts/pikaman.py", line 23, in <module>
    import markdown_it
ModuleNotFoundError: No module named 'markdown_it'
make: *** [Makefile:48: pikaur.1] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

Command 'makepkg --force' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[f] skip 'check()' function of PKGBUILD
[n] skip 'prepare()' function of PKGBUILD
[i] ignore architecture
[d] delete build dir and try again
[e] edit PKGBUILD
------------------------
[s] skip building this package
[a] abort building all the packages
> a

```

##### Building from source:

```
sudo pacman -S --needed base-devel git
warning: base-devel-1-1 is up to date -- skipping
warning: git-2.40.1-1 is up to date -- skipping
 there is nothing to do
git clone https://aur.archlinux.org/pikaur.git
Cloning into 'pikaur'...
remote: Enumerating objects: 665, done.
remote: Counting objects: 100% (665/665), done.
remote: Compressing objects: 100% (376/376), done.
remote: Total 665 (delta 293), reused 661 (delta 289), pack-reused 0
Receiving objects: 100% (665/665), 141.11 KiB | 602.00 KiB/s, done.
Resolving deltas: 100% (293/293), done.
❯ cd pikaur
❯ makepkg -fsri
==> Making package: pikaur 1.15.2-1 (Mon May 22 02:40:32 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading pikaur-1.15.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2155k  100 2155k    0     0   795k      0  0:00:02  0:00:02 --:--:--  976k
==> Validating source files with b2sums...
    pikaur-1.15.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting pikaur-1.15.2.tar.gz with bsdtar
==> Starting build()...
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
find pikaur -type f -name '*.py' -print0 \
	| xargs --null xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
................................ done.
msgfmt -o locale/fr.mo locale/fr.po
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
................................ done.
msgfmt -o locale/ru.mo locale/ru.po
test -f locale/pt.po || msginit --locale=pt --no-translator --input=locale/pikaur.pot --output=locale/pt.po
msgmerge --update locale/pt.po locale/pikaur.pot
...................................... done.
msgfmt -o locale/pt.mo locale/pt.po
test -f locale/pt_BR.po || msginit --locale=pt_BR --no-translator --input=locale/pikaur.pot --output=locale/pt_BR.po
msgmerge --update locale/pt_BR.po locale/pikaur.pot
................................. done.
msgfmt -o locale/pt_BR.mo locale/pt_BR.po
test -f locale/de.po || msginit --locale=de --no-translator --input=locale/pikaur.pot --output=locale/de.po
msgmerge --update locale/de.po locale/pikaur.pot
........................................ done.
msgfmt -o locale/de.mo locale/de.po
test -f locale/is.po || msginit --locale=is --no-translator --input=locale/pikaur.pot --output=locale/is.po
msgmerge --update locale/is.po locale/pikaur.pot
................................. done.
msgfmt -o locale/is.mo locale/is.po
test -f locale/tr.po || msginit --locale=tr --no-translator --input=locale/pikaur.pot --output=locale/tr.po
msgmerge --update locale/tr.po locale/pikaur.pot
................................ done.
msgfmt -o locale/tr.mo locale/tr.po
test -f locale/da.po || msginit --locale=da --no-translator --input=locale/pikaur.pot --output=locale/da.po
msgmerge --update locale/da.po locale/pikaur.pot
...................................... done.
msgfmt -o locale/da.mo locale/da.po
test -f locale/nl.po || msginit --locale=nl --no-translator --input=locale/pikaur.pot --output=locale/nl.po
msgmerge --update locale/nl.po locale/pikaur.pot
................................. done.
msgfmt -o locale/nl.mo locale/nl.po
test -f locale/es.po || msginit --locale=es --no-translator --input=locale/pikaur.pot --output=locale/es.po
msgmerge --update locale/es.po locale/pikaur.pot
................................ done.
msgfmt -o locale/es.mo locale/es.po
test -f locale/zh_CN.po || msginit --locale=zh_CN --no-translator --input=locale/pikaur.pot --output=locale/zh_CN.po
msgmerge --update locale/zh_CN.po locale/pikaur.pot
................................ done.
msgfmt -o locale/zh_CN.mo locale/zh_CN.po
test -f locale/it.po || msginit --locale=it --no-translator --input=locale/pikaur.pot --output=locale/it.po
msgmerge --update locale/it.po locale/pikaur.pot
................................. done.
msgfmt -o locale/it.mo locale/it.po
test -f locale/ja.po || msginit --locale=ja --no-translator --input=locale/pikaur.pot --output=locale/ja.po
msgmerge --update locale/ja.po locale/pikaur.pot
.................................... done.
msgfmt -o locale/ja.mo locale/ja.po
test -f locale/uk.po || msginit --locale=uk --no-translator --input=locale/pikaur.pot --output=locale/uk.po
msgmerge --update locale/uk.po locale/pikaur.pot
................................. done.
msgfmt -o locale/uk.mo locale/uk.po
/home/keiljr/.asdf/shims/python ./maintenance_scripts/pikaman.py README.md pikaur.1
Traceback (most recent call last):
  File "/home/keiljr/pikaur/src/pikaur-1.15.2/./maintenance_scripts/pikaman.py", line 23, in <module>
    import markdown_it
ModuleNotFoundError: No module named 'markdown_it'
make: *** [Makefile:48: pikaur.1] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by actionless** [comment]
> /home/keiljr/.asdf/shims/python

that's wrong should be

```console
$ which python
/usr/sbin/python
```

**Comment by actionless** [comment]
you would have same error when using asdf/conda with almost any python package installed via Arch repos or AUR, not only pikaur - that's intended behavior
