### ISSUE TITLE
KeyError when updating

### ISSUE THREAD

**Issue by sudoHackr** [actionless/pikaur#73]
Using `pikaur-git 0.8+60+g7b90ae3-1` from AUR

I get the following error when attempting to update using `pikaur -Syu`. I should probably note that an update hasn't been done for about 3 months on this machine (just recently installed pikaur)
To me it seems related to issue #70

```
:: Proceed with installation? [Y/n]
:: [v]iew package detail   [m]anually select packages
> 
looking for conflicting packages...
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 269, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 212, in cli_entry_point
    cli_upgrade_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 112, in cli_upgrade_packages
    packages=all_package_names,
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 67, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 87, in __init__
    self.ask_about_package_replacements()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 420, in ask_about_package_replacements
    package_replacements = find_replacements()
  File "/usr/lib/python3.6/site-packages/pikaur/conflicts.py", line 175, in find_replacements
    PackageDB.get_repo_priority(all_repo_pkgs_info[replace_pkg_name].db.name) <=
KeyError: 'jbuilder'
```

**Comment by actionless** [comment]
please check if it helps

**Comment by sudoHackr** [comment]
Unfortunetly I can't say for sure; in the meantime I ran `pacman -Syu` and resolved a few conflicts myself so I'm not sure what helped, but it works now.

Thanks for the quick response and fix anyways :+1:
