### ISSUE TITLE
Error with pty import in pikspect when running 1.16

### ISSUE THREAD

**Issue by ppascher** [actionless/pikaur#731]
##### Description:
Building latest pikaur 1.16 works but when running I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 6, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.11/site-packages/pikaur/main.py", line 39, in <module>
    from .getpkgbuild_cli import cli_getpkgbuild
  File "/usr/lib/python3.11/site-packages/pikaur/getpkgbuild_cli.py", line 6, in <module>
    from .aur import AURPackageInfo, find_aur_packages, get_repo_url
  File "/usr/lib/python3.11/site-packages/pikaur/aur.py", line 12, in <module>
    from .urllib import get_gzip_from_url, get_json_from_url
  File "/usr/lib/python3.11/site-packages/pikaur/urllib.py", line 14, in <module>
    from .prompt import ask_to_continue
  File "/usr/lib/python3.11/site-packages/pikaur/prompt.py", line 14, in <module>
    from .pikspect import PikspectPopen, ReadlineKeycodes, TTYInputWrapper, TTYRestore
  File "/usr/lib/python3.11/site-packages/pikaur/pikspect.py", line 18, in <module>
    from pty import (  # type: ignore[attr-defined]
ImportError: cannot import name '_writen' from 'pty' (/usr/lib/python3.11/pty.py)
```

Those imports where defined in the recent commit 971206b7e060d83eba4a9cdf2045e069954a9cd8 (fix/refactor(pikspect))

**Comment by ppascher** [comment]
looking at https://github.com/python/cpython/blob/3.11/Lib/pty.py it seems "_writen" was removed in python 3.11 and still present in 3.10

**Comment by actionless** [comment]
```
$ grep -n _writen /usr/lib/python3.11/pty.py
124:def _writen(fd, data):
161:                _writen(master_fd, data)

$ python --version
Python 3.11.3
```

you must be using `test` repo
