### ISSUE TITLE
Compilation error with the version 1.18.3-1

### ISSUE THREAD

**Issue by darkbaboon** [actionless/pikaur#746]
```
pikaur -Vq
1.18.3-1
```

##### [Optional] Prerequisites:
Update of pikaur

##### Description:
Run the update
Unable to update pikaur to the the last version 1.18.3-1

##### Attached log:

```
pikaur -S pikaur --verbose --pikaur-debug
Traceback (most recent call last):
  File "/home/baboon/.cache/pikaur/build/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
    OptionsType = markdown_it.utils.OptionsType
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
...............................make: *** [Makefile:48: pikaur.1] Error 1
```

**Comment by actionless** [comment]
update the system first

**Comment by muntean-alex** [comment]
I believe this might still affect some users.
Manjaro, fully, updated.
For me this is:
```$ sudo pacman -Syyu
:: Synchronizing package databases...
 core                                          145.7 KiB   401 KiB/s 00:00 [##########################################] 100%
 extra                                           8.6 MiB  11.0 MiB/s 00:01 [##########################################] 100%
 community                                      29.0   B   391   B/s 00:00 [##########################################] 100%
 multilib                                      146.8 KiB  2011 KiB/s 00:00 [##########################################] 100%
:: Starting full system upgrade...
 there is nothing to do
```

And then pamac

```Preparing...
Cloning pikaur build files...
Generating pikaur information...
Checking pikaur dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building pikaur...
==> Making package: pikaur 1.18.3-1 (Sat 19 Aug 2023 12:15:44 AM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found pikaur-1.18.3.tar.gz
==> Validating source files with b2sums...
    pikaur-1.18.3.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting pikaur-1.18.3.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
find pikaur -type f -name '*.py' -print0 \
	| xargs --null xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
xgettext: The option '--sort-output' is deprecated.
mkdir -p dist/usr/bin
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
.................................. done.
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
Traceback (most recent call last):
  File "/var/tmp/pamac-build-user/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
    OptionsType = markdown_it.utils.OptionsType
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
............................. done.
make: *** [Makefile:48: pikaur.1] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
```

Sorry If I'm missing something else.

**Comment by HennoHimself** [comment]
This is still an issue for me, also.

Fully updated Archlinux system with the same error.

**Comment by plague-doctor** [comment]
Same here. Fully updated system

**Comment by darkbaboon** [comment]
> update the system first
my system was up-to-date, thank you for asking

**Comment by yourealwaysbe** [comment]
There are currently a [load of out of sync Arch mirrors](https://archlinux.org/mirrors/status/). I'm not sure if this is more than usual, but even after a reflector refresh of the mirrorlist i was getting out of sync mirrors.

Manually adding an [in-sync mirror](https://archlinux.org/mirrors/status/#successful) fixed the problem for me.
