### ISSUE TITLE
Backtrace when configuration file is not complete

### ISSUE THREAD

**Issue by whxvd** [actionless/pikaur#752]
```
Pikaur v1.18.3
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```
There is only one configuration setting in `~/.config/pikaur.conf` that I wish to change. For all other settings I would like to use whatever the current `pikaur` defaults are. Hence, I tried setting `~/.config/pikaur.conf` to just:

```
[misc]
privilegeescalationtarget = pacman
```

However, with that in place, e.g., `pikaur --help` produces the following output:

```
  File "/usr/lib/python3.11/site-packages/pikaur/main.py", line 416, in main
    check_runtime_deps()
  File "/usr/lib/python3.11/site-packages/pikaur/core.py", line 364, in check_runtime_deps
    privilege_escalation_tool = PikaurConfig().misc.PrivilegeEscalationTool.get_str()
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pikaur/config.py", line 672, in __getattr__
    return PikaurConfigSection(self.get_config()[attr])
                               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pikaur/config.py", line 607, in get_config
    cls.migrate_config()
  File "/usr/lib/python3.11/site-packages/pikaur/config.py", line 633, in migrate_config
    value_to_migrate = cls._config[section_name].get(option_name)
                       ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 979, in __getitem__
    raise KeyError(key)

KeyError: 'build'
```

Expected: Either (1) no issue.  Or (2) a non-backtrace error message explaining what the issue is.  Maybe `pikaur` is not intended to support the usual kind of "partial" configuration (using built-in defaults for everything that is not specified).

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by whxvd** [comment]
It does not produce an error anymore. However, pikaur still modifies/completes the configuration file. In general, I would prefer if pikaur would not modify it. But that is fine, too. Thank you!

**Comment by whxvd** [comment]
In the meantime the problem has reappeared. In the current version (1.32-2), the problem is present as described in first post. I see no possibility to reopen this issue. Should I create a new one?

**Comment by actionless** [comment]
you can upload a new traceback here

**Comment by whxvd** [comment]
When `~/.config/pikaur.conf` contains only

```
[misc]
privilegeescalationtarget = pacman
```

the backtrace of `pikaur --help` is:

```
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 41, in <module>
    main()
    ~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/main.py", line 518, in main
    with wrapper():
         ~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/main.py", line 107, in __enter__
    logger.debug(
    ~~~~~~~~~~~~^
        "Setting {} to {}...", attr, DEFAULT_INPUT_ENCODING,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lock=False,
        ^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/pikaur/logging_extras.py", line 81, in debug
    msg = f"{color_line(self.module_name, self.color)}: {' ' * indent}{str_message}"
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/pikaprint.py", line 189, in color_line
    if not color_enabled() and not force:
           ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/pikaprint.py", line 91, in color_enabled
    args = parse_args()
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 821, in parse_args
    parsed_args, _help = _parse_args(args=args)
                         ~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 780, in _parse_args
    parser, help_msgs = get_parser_for_action(app=app_name, args=args)
                        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 748, in get_parser_for_action
    ("store_true", get_pikaur_bool_opts(action=pikaur_action), True, None),
                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 240, in get_pikaur_bool_opts
    None, "print-commands", PikaurConfig().ui.PrintCommands.get_bool(),
                            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/config.py", line 705, in __getattr__
    return PikaurConfigSection(self.get_config()[attr])
                               ~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/config.py", line 698, in get_config
    cls.migrate_config()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/config.py", line 794, in migrate_config
    cls._handle_warning(option_schema, section_name, option_name)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/config.py", line 814, in _handle_warning
    current_value = cls._config[section_name][option_name]
                    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/configparser.py", line 998, in __getitem__
    raise KeyError(key)
KeyError: 'build'
```

When `~/.config/pikaur.conf` is an empty file, an equal traceback seems to be produced.

When `~/.config/pikaur.conf` does not exist, then `pikaur --help` writes a new `~/.config/pikaur.conf`.
