### ISSUE TITLE
Installation: AttributeError: module 'datetime' has no attribute 'UTC'

### ISSUE THREAD

**Issue by kellyiscute** [actionless/pikaur#778]
Python Version: 3.10.12

Error Log:
```
Traceback (most recent call last):
  File "[snip]/pikaur/pikaur/src/pikaur-1.18.4/./maintenance_scripts/pikaman.py", line 281, in <module>
    NroffRenderer(name="pikaur", section=1).render(
  File "[snip]/pikaur/pikaur/src/pikaur-1.18.4/./maintenance_scripts/pikaman.py", line 66, in render
    result = self.document_open()
  File "[snip]/pikaur/pikaur/src/pikaur-1.18.4/./maintenance_scripts/pikaman.py", line 255, in document_open
    date = datetime.datetime.now(tz=datetime.UTC).strftime("%B %Y")
AttributeError: module 'datetime' has no attribute 'UTC'
make: *** [Makefile:48: pikaur.1] Error 1
```

**Comment by actionless** [comment]
> Python Version: 3.10.12
