### ISSUE TITLE
pikaur gives only a ValueError when executed

### ISSUE THREAD

**Issue by dschopf** [actionless/pikaur#787]
```
pikaur -Vq

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 41, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 410, in main
    with wrapper():
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 97, in __enter__
    logger.debug(
  File "/usr/lib/python3.12/site-packages/pikaur/logging.py", line 80, in debug
    msg = f"{color_line(self.module_name, self.color)}: {' ' * indent}{str_message}"
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/pprint.py", line 168, in color_line
    if not color_enabled() and not force:
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/pprint.py", line 81, in color_enabled
    args = parse_args()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 732, in parse_args
    parsed_args, _help = _parse_args(args=args)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 693, in _parse_args
    parser, help_msgs = get_parser_for_action(app=app_name, args=args)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 652, in get_parser_for_action
    parsed_action = parser.parse_pikaur_args(args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 540, in parse_pikaur_args
    parsed_args, unknown_args = self.parse_known_args(raw_args)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1929, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/argparse.py", line 229, in _parse_known_args
    start_index, unknown_args = consume_optional(start_index)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/argparse.py", line 100, in consume_optional
    action, option_string, explicit_arg = option_tuple
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)
```

Version used is pikaur-git-1.19.r15.g1926482-1

##### [Optional] Prerequisites:
Update Arch Linux system to latest testing version.

##### Description:
After upgrading today this issue happens.

**Comment by dschopf** [comment]
Looks like a change in Python 3.12.3 caused this. With 3.12.2 it works without any issue.

**Comment by actionless** [comment]
thanks for reporting, i'll try to update before python 3.12 will hit the arch repos (you're using `testing` arch branch i suppose)

**Comment by actionless** [comment]
i've built python312 from aur and it works for me

could you add an extra print statement and show the output?

```console
$ git diff
diff --git a/pikaur/argparse.py b/pikaur/argparse.py
index b20c775..c61b6bc 100644
--- a/pikaur/argparse.py
+++ b/pikaur/argparse.py
@@ -97,6 +97,7 @@ class ArgumentParserWithUnknowns(ArgumentParser):
             action: Action | None
             option_string: str
             explicit_arg: str | None
+            print(option_tuple)
             action, option_string, explicit_arg = option_tuple

             # identify additional optionals in the same arg string


$ python3.12 -m pikaur -Vq
(_StoreTrueAction(option_strings=['-V', '--version'], dest='version', nargs=0, const=True, default=None, type=None,
choices=None, required=False, help=None, metavar=None), '-V', 'q')
(_StoreTrueAction(option_strings=['-V', '--version'], dest='version', nargs=0, const=True, default=None, type=None,
choices=None, required=False, help=None, metavar=None), '-V', 'q')
```

**Comment by actionless** [comment]
my bad, i didn't noticed you're using 3.12.3, i'll try building that one
