### ISSUE TITLE
python update breaks pikaur

### ISSUE THREAD

**Issue by switit** [actionless/pikaur#788]
```
pikaur -Vq

```

##### Description:
After a bunch of pyphon updates today (more than 10), pikaur -Syu is not working with warning that I have to rebuild pikaur manually. I did just that but when I pikaur -Syu again I got the error log.

##### Attached log:
$ pikaur -Syu
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 41, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 410, in main
    with wrapper():
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 97, in __enter__
    logger.debug(
  File "/usr/lib/python3.12/site-packages/pikaur/logging.py", line 80, in debug
    msg = f"{color_line(self.module_name, self.color)}: {' ' * indent}{str_message}"
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/pprint.py", line 168, in color_line
    if not color_enabled() and not force:
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/pprint.py", line 81, in color_enabled
    args = parse_args()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 732, in parse_args
    parsed_args, _help = _parse_args(args=args)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 693, in _parse_args
    parser, help_msgs = get_parser_for_action(app=app_name, args=args)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 652, in get_parser_for_action
    parsed_action = parser.parse_pikaur_args(args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 540, in parse_pikaur_args
    parsed_args, unknown_args = self.parse_known_args(raw_args)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1929, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/argparse.py", line 229, in _parse_known_args
    start_index, unknown_args = consume_optional(start_index)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/argparse.py", line 100, in consume_optional
    action, option_string, explicit_arg = option_tuple
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)
```
pikaur -S my-precious-package --verbose --pikaur-debug


```

**Comment by ronasimi** [comment]
pikaur-git seems to work after a rebuild

**Comment by andreyv** [comment]
See #787.

**Comment by switit** [comment]
Downgrading python from 3.12.3 to 3.12.2 solves the problem for now.

**Comment by siroccal** [comment]
> pikaur-git seems to work after a rebuild

Yeah, pikaur release 1.19 works for me with python 3.12.3, but the latest git doesn't work.

**Comment by nursoda** [comment]
@actionless Please do a release, otherwise your [installation instructions](https://github.com/actionless/pikaur?tab=readme-ov-file#installation) fail since they fetch 1.19 without the fix.

**Comment by siroccal** [comment]
@nursoda With "latest git" I meant `git clone https://aur.archlinux.org/pikaur.git` (which doesn't work). And with "release 1.19" I meant the 1.19 release from github (which does work). I just tried `git clone https://aur.archlinux.org/pikaur-git.git` and it does work. Sorry for the confusion.

**Comment by nursoda** [comment]
@actionless You closed 787 by committing a fix and you closed this issue 788 as duplicate. But as long as you don't release a new version to github and update the PKGBUILD, users will end up with a non-working pikaur even if they do the manual re-installation. Just sayin'

**Comment by actionless** [comment]
@nursoda i did that before closing, no worries
