### ISSUE TITLE
pikaur 1.21 is broken on Manjaro aarch64

### ISSUE THREAD

**Issue by renkei** [actionless/pikaur#800]
On my rpi4 with Manjaro I've used pikaur to install the pikaur 1.21 update. The build fails, but the package is still created. Worst case, I would say ;-)

```
* Getting build dependencies for wheel...
* Building wheel...
Successfully built pikaur-1.21-py3-none-any.whl
==> Betrete fakeroot Umgebung...
==> Beginne package()...
*** Error compiling '/home/renkei/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.11/site-packages/pikaur/install_cli.py'...
  File "/usr/lib/python3.11/site-packages/pikaur/install_cli.py", line 292
    self.edit_pkgbuild_during_the_build(pkg_name)
    ^
SyntaxError: f-string expression part cannot include a backslash

*** Error compiling '/home/renkei/.cache/pikaur/build/pikaur/pkg/pikaur/usr/lib/python3.11/site-packages/pikaur/install_cli.py'...
  File "/usr/lib/python3.11/site-packages/pikaur/install_cli.py", line 292
    self.edit_pkgbuild_during_the_build(pkg_name)
    ^
SyntaxError: f-string expression part cannot include a backslash

==> Säubere Installation...
  -> Entferne libtool Dateien...
  -> Bereinige ungewollte Dateien...
  -> Entferne statische Bibliotheken...
  -> Entferne unnötige Symbole aus Binär-Dateien und Bibliotheken...
  -> Komprimiere Man-Pages und Info-Seiten...
==> Prüfe auf Paketierungsprobleme...
==> Erstelle Paket "pikaur"...
  -> Erstelle .PKGINFO Datei...
  -> Erstelle .BUILDINFO Datei...
  -> Erstelle .MTREE-Datei...
  -> Komprimiere Paket...
==> Verlasse fakeroot Umgebung.
==> Beendete Erstellung: pikaur 1.21-1 (Sa 25 Mai 2024 12:47:48 CEST)
```

Because now, a broken pikaur package is installed beside my other updates:
```
Pakete werden geladen …
Abhängigkeiten werden aufgelöst …
Nach in Konflikt stehenden Paketen wird gesucht …

Pakete (8) aspnet-runtime-bin-8.0.5.sdk300-1  aspnet-targeting-pack-bin-8.0.5.sdk300-1  dotnet-host-bin-8.0.5.sdk300-1
           dotnet-runtime-bin-8.0.5.sdk300-1  dotnet-sdk-bin-8.0.5.sdk300-1  dotnet-targeting-pack-bin-8.0.5.sdk300-1
           netstandard-targeting-pack-bin-8.0.5.sdk300-1  pikaur-1.21-1

Gesamtgröße der installierten Pakete:  602,58 MiB
Größendifferenz der Aktualisierung:    -12,35 MiB

:: Installation fortsetzen? [J/n] J
(8/8) Schlüssel im Schlüsselbund werden geprüft                          [########################################] 100%
(8/8) Paket-Integrität wird überprüft                                    [########################################] 100%
(8/8) Paket-Dateien werden geladen                                       [########################################] 100%
(8/8) Auf Dateikonflikte wird geprüft                                    [########################################] 100%
(8/8) Verfügbarer Festplattenspeicher wird ermittelt                     [########################################] 100%
:: Paketänderungen werden verarbeitet …
(1/8) Aktualisiert wird dotnet-host-bin                                  [########################################] 100%
(2/8) Aktualisiert wird dotnet-runtime-bin                               [########################################] 100%
(3/8) Aktualisiert wird aspnet-runtime-bin                               [########################################] 100%
(4/8) Aktualisiert wird netstandard-targeting-pack-bin                   [########################################] 100%
(5/8) Aktualisiert wird dotnet-targeting-pack-bin                        [########################################] 100%
(6/8) Aktualisiert wird aspnet-targeting-pack-bin                        [########################################] 100%
(7/8) Aktualisiert wird dotnet-sdk-bin                                   [########################################] 100%
(8/8) Aktualisiert wird pikaur                                           [########################################] 100%
:: Post-transaction-Hooks werden gestartet …
(1/2) Reloading user manager configuration...
(2/2) Arming ConditionNeedsUpdate...
```
When I try to execute pikaur, I get now:
```
$ pikaur -Syu
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 6, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.11/site-packages/pikaur/main.py", line 40, in <module>
    from .install_cli import InstallPackagesCLI
  File "/usr/lib/python3.11/site-packages/pikaur/install_cli.py", line 292
    ),
    ^
SyntaxError: f-string expression part cannot include a backslash
```

**Comment by actionless** [comment]
your python is out-of-date: https://archlinux.org/packages/core/x86_64/python/

downgrade to previous pikaur version, if you can't update python
