### ISSUE TITLE
Pikaur is broken with Arch Linux update to python 3.13 

### ISSUE THREAD

**Issue by siroccal** [actionless/pikaur#857]
##### Description:

Can't run `pikaur` with updated Arch Linux system (with `python` 3.13).
Can't manually install `pikaur-static`, because one of its dependencies (`nuitka`) doesn't work with `python` 3.13. Can't use `pikaur-static` from release either, because it errors out (`KeyError: 'extra-testing/python-markdown-it-py'`).

##### Attached log:

```
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 41, in <module>
    main()
    ~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/main.py", line 518, in main
    with wrapper():
         ~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/main.py", line 107, in __enter__
    logger.debug(
    ~~~~~~~~~~~~^
        "Setting {} to {}...", attr, DEFAULT_INPUT_ENCODING,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lock=False,
        ^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/pikaur/logging_extras.py", line 81, in debug
    msg = f"{color_line(self.module_name, self.color)}: {' ' * indent}{str_message}"
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/pikaprint.py", line 189, in color_line
    if not color_enabled() and not force:
           ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/pikaprint.py", line 91, in color_enabled
    args = parse_args()
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 821, in parse_args
    parsed_args, _help = _parse_args(args=args)
                         ~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 780, in _parse_args
    parser, help_msgs = get_parser_for_action(app=app_name, args=args)
                        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 739, in get_parser_for_action
    parsed_action = parser.parse_pikaur_args(args)
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 629, in parse_pikaur_args
    parsed_args, unknown_args = self.parse_known_args(args_to_parse)
                                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/argparse.py", line 1899, in parse_known_args
    return self._parse_known_args2(args, namespace, intermixed=False)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/argparse.py", line 1928, in _parse_known_args2
    namespace, args = self._parse_known_args(args, namespace, intermixed)
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArgumentParserWithUnknowns._parse_known_args() takes 3 positional arguments but 4 were given
```

**Comment by actionless** [comment]
> Can't use pikaur-static from release either, because it errors out (KeyError: 'extra-testing/python-markdown-it-py').


could you provide the full log?

**Comment by grazzolini** [comment]
> > Can't use pikaur-static from release either, because it errors out (KeyError: 'extra-testing/python-markdown-it-py').
> 
> could you provide the full log?

The full log:
```
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 41, in <module>
    main()
    ~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/main.py", line 518, in main
    with wrapper():
         ~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/main.py", line 107, in __enter__
    logger.debug(
    ~~~~~~~~~~~~^
        "Setting {} to {}...", attr, DEFAULT_INPUT_ENCODING,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lock=False,
        ^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/pikaur/logging_extras.py", line 81, in debug
    msg = f"{color_line(self.module_name, self.color)}: {' ' * indent}{str_message}"
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/pikaprint.py", line 189, in color_line
    if not color_enabled() and not force:
           ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pikaur/pikaprint.py", line 91, in color_enabled
    args = parse_args()
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 821, in parse_args
    parsed_args, _help = _parse_args(args=args)
                         ~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 780, in _parse_args
    parser, help_msgs = get_parser_for_action(app=app_name, args=args)
                        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 739, in get_parser_for_action
    parsed_action = parser.parse_pikaur_args(args)
  File "/usr/lib/python3.13/site-packages/pikaur/args.py", line 629, in parse_pikaur_args
    parsed_args, unknown_args = self.parse_known_args(args_to_parse)
                                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/argparse.py", line 1899, in parse_known_args
    return self._parse_known_args2(args, namespace, intermixed=False)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/argparse.py", line 1928, in _parse_known_args2
    namespace, args = self._parse_known_args(args, namespace, intermixed)
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArgumentParserWithUnknowns._parse_known_args() takes 3 positional arguments but 4 were given

```

**Comment by siroccal** [comment]
> > Can't use pikaur-static from release either, because it errors out (KeyError: 'extra-testing/python-markdown-it-py').
> 
> could you provide the full log?

```
$ ./pikaur-static-v1.30.3.linux-64.exe -S pikaur-static

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

=> sudo --preserve-env=EDITOR -- /home/user/Programs/pikaur-static-v1.30.3.linux-64.exe -S pikaur-static --pikaur-config=/home/user/.config/pikaur.conf --user-id=1000 --home-dir=/home/user --xdg-cache-home=/home/user/.cache --xdg-config-home=/home/user/.config/ --xdg-data-home=/home/user/.local/share
[sudo] password for user: 

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync pikaur-static --print-format %r/%n
=> pacman --color=always --sync pikaur-static --print-format %r/%n --nodeps --nodeps
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pikaur-static
Resolving AUR dependencies...
=> pacman --color=always --deptest git nuitka ccache fish python-markdown-it-py python-pysocks python-defusedxml
=> pacman --color=always --sync nuitka python-markdown-it-py python-pysocks --print-format %r/%n --nodeps
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=nuitka
=> pacman --color=always --deptest libxml2 patchelf python python-appdirs python-setuptools>=42.0 python-wheel scons gdb git python-build python-installer ccache fuse2 python-boto3 python-brotli strace
=> pacman --color=always --sync python-markdown-it-py --print-format %r/%n --nodeps --nodeps
  File "/tmp/onefile_34049_1734391911_931875/pikaur/main.py", line 537, in main
  File "/tmp/onefile_34049_1734391911_931875/pikaur/main.py", line 363, in cli_entry_point
  File "/tmp/onefile_34049_1734391911_931875/pikaur/main.py", line 285, in execute_pikaur_operation
  File "/tmp/onefile_34049_1734391911_931875/pikaur/main.py", line 175, in cli_install_packages
  File "/tmp/onefile_34049_1734391911_931875/pikaur/install_cli.py", line 238, in __init__
  File "/tmp/onefile_34049_1734391911_931875/pikaur/install_cli.py", line 278, in main_sequence
  File "/tmp/onefile_34049_1734391911_931875/pikaur/install_cli.py", line 396, in get_all_packages_info
  File "/tmp/onefile_34049_1734391911_931875/pikaur/install_info_fetcher.py", line 99, in __init__
  File "/tmp/onefile_34049_1734391911_931875/pikaur/install_info_fetcher.py", line 251, in get_all_packages_info
  File "/tmp/onefile_34049_1734391911_931875/pikaur/install_info_fetcher.py", line 453, in get_repo_deps_info
  File "/tmp/onefile_34049_1734391911_931875/pikaur/aur_deps.py", line 453, in find_repo_deps_of_aur_pkgs
  File "/tmp/onefile_34049_1734391911_931875/multiprocessing/pool.py", line 774, in get
  File "/tmp/onefile_34049_1734391911_931875/multiprocessing/pool.py", line 125, in worker
  File "/tmp/onefile_34049_1734391911_931875/pikaur/aur_deps.py", line 423, in _find_repo_deps_of_aur_pkg
  File "/tmp/onefile_34049_1734391911_931875/pikaur/pacman.py", line 538, in find_repo_package

KeyError: 'extra-testing/python-markdown-it-py'
```

**Comment by actionless** [comment]
@siroccal and what's the output of `pacman -Ss python-markdown-it-py`?

**Comment by siroccal** [comment]
> @siroccal and what's the output of `pacman -Ss python-markdown-it-py`?

```
$ pacman -Ss python-markdown-it-py
extra-testing/python-markdown-it-py 3.0.0-4
    Python port of markdown-it. Markdown parsing, done right!
extra/python-markdown-it-py 3.0.0-2
    Python port of markdown-it. Markdown parsing, done right!
```

**Comment by actionless** [comment]
and same with pikaur?

**Comment by siroccal** [comment]
> and same with pikaur?

```
$ ./pikaur-static-v1.30.3.linux-64.exe -Ss python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

Searching... [=> GET https://aur.archlinux.org/rpc/?v=5&type=search&arg=python-markdown-it-py&by=name-desc
###
extra/python-markdown-it-py 3.0.0-2 
    Python port of markdown-it. Markdown parsing, done right!    
```

**Comment by actionless** [comment]
and now try -Ss and -S together with `--force-pacman-cli-db`

**Comment by actionless** [comment]
and `ls -la /var/lib/pacman/sync/`

**Comment by siroccal** [comment]
> and now try -Ss and -S together with `--force-pacman-cli-db`

```
$ ./pikaur-static-v1.30.3.linux-64.exe -Ss --force-pacman-cli-db python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

 >>> User forced to use pacman output
 >>> Switching to pure pacman-only mode (pacman CLI output will be used instead of ALPM DB)...


 >>> Retrieving local pacman database...
Searching... [=> GET https://aur.archlinux.org/rpc/?v=5&type=search&arg=python-markdown-it-py&by=name-desc
 >>> Retrieving local pacman database...
###
extra/python-markdown-it-py 3.0.0-2 
    Python port of markdown-it. Markdown parsing, done right!    
```

```
$ ./pikaur-static-v1.30.3.linux-64.exe -S --force-pacman-cli-db python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

 >>> User forced to use pacman output
 >>> Switching to pure pacman-only mode (pacman CLI output will be used instead of ALPM DB)...


=> sudo --preserve-env=EDITOR -- /home/user/Programs/pikaur-static-v1.30.3.linux-64.exe -S --force-pacman-cli-db python-markdown-it-py --pikaur-config=/home/user/.config/pikaur.conf --user-id=1000 --home-dir=/home/user --xdg-cache-home=/home/user/.cache --xdg-config-home=/home/user/.config/ --xdg-data-home=/home/user/.local/share

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

 >>> User forced to use pacman output
 >>> Switching to pure pacman-only mode (pacman CLI output will be used instead of ALPM DB)...


Reading repository package databases...
 >>> Retrieving local pacman database...
Reading local package database...
=> pacman --color=always --sync python-markdown-it-py --print-format %r/%n
  File "/tmp/onefile_51909_1734395700_303765/pikaur/main.py", line 537, in main
  File "/tmp/onefile_51909_1734395700_303765/pikaur/main.py", line 363, in cli_entry_point
  File "/tmp/onefile_51909_1734395700_303765/pikaur/main.py", line 285, in execute_pikaur_operation
  File "/tmp/onefile_51909_1734395700_303765/pikaur/main.py", line 175, in cli_install_packages
  File "/tmp/onefile_51909_1734395700_303765/pikaur/install_cli.py", line 238, in __init__
  File "/tmp/onefile_51909_1734395700_303765/pikaur/install_cli.py", line 278, in main_sequence
  File "/tmp/onefile_51909_1734395700_303765/pikaur/install_cli.py", line 396, in get_all_packages_info
  File "/tmp/onefile_51909_1734395700_303765/pikaur/install_info_fetcher.py", line 99, in __init__
  File "/tmp/onefile_51909_1734395700_303765/pikaur/install_info_fetcher.py", line 237, in get_all_packages_info
  File "/tmp/onefile_51909_1734395700_303765/pikaur/install_info_fetcher.py", line 410, in get_repo_pkgs_info
  File "/tmp/onefile_51909_1734395700_303765/pikaur/install_info_fetcher.py", line 322, in _get_repo_pkgs_info
  File "/tmp/onefile_51909_1734395700_303765/pikaur/install_info_fetcher.py", line 290, in _get_pkg_install_infos

KeyError: 'extra-testing/python-mdurl'
```



> and `ls -la /var/lib/pacman/sync/`

```ls -la /var/lib/pacman/sync/
total 9568
drwxr-xr-x 2 root root    4096 Dec 16 23:51 ./
drwxr-xr-x 4 root root    4096 Dec 17 00:23 ../
-rw-r--r-- 1 root root  118362 Dec 13 14:01 core.db
-rw-r--r-- 1 root root   17573 Dec 16 21:48 core-testing.db
-rw-r--r-- 1 root root 7952798 Dec 16 21:47 extra.db
-rw-r--r-- 1 root root 1547004 Dec 16 21:48 extra-testing.db
-rw-r--r-- 1 root root      45 Dec 12 15:08 kde-unstable.db
-rw-r--r-- 1 root root  135411 Dec 15 22:05 multilib.db
-rw-r--r-- 1 root root    1143 Dec 16 19:37 multilib-testing.db
```

**Comment by actionless** [comment]
this is super-weird, for some some reason none of 2 fallback db readers could read the correct list of repositories, try:

```console
$ pacman-conf --repo-list
$ git clone https://github.com/actionless/pikaur.git
$ cd pikaur/pikaur_static/
$ python -c 'from pypyalpm import PackageDB_ALPM9 ; print(PackageDB_ALPM9.get_db_names())'
$ python -c 'from pypyalpm import PackageDB_ALPM9 ; print(PackageDB_ALPM9.get_db_names())' --force-pacman-cli-db

**Comment by siroccal** [comment]
> this is super-weird, for some some reason none of 2 fallback db readers could read the correct list of repositories, try:
> 
> ```
> $ pacman-conf --repo-list
> $ git clone https://github.com/actionless/pikaur.git
> $ cd pikaur/pikaur_static/
> $ python -c 'from pypyalpm import PackageDB_ALPM9 ; print(PackageDB_ALPM9.get_db_names())'
> $ python -c 'from pypyalpm import PackageDB_ALPM9 ; print(PackageDB_ALPM9.get_db_names())' --force-pacman-cli-db
> ```

```
$ pacman-conf --repo-list
kde-unstable
core-testing
core
extra-testing
extra
multilib-testing
multilib
$ git clone https://github.com/actionless/pikaur.git
Cloning into 'pikaur'...
remote: Enumerating objects: 16398, done.
remote: Counting objects: 100% (2226/2226), done.
remote: Compressing objects: 100% (400/400), done.
remote: Total 16398 (delta 2009), reused 1874 (delta 1823), pack-reused 14172 (from 1)
Receiving objects: 100% (16398/16398), 6.73 MiB | 3.65 MiB/s, done.
Resolving deltas: 100% (12430/12430), done.
$ cd pikaur/pikaur_static/
$ python -c 'from pypyalpm import PackageDB_ALPM9 ; print(PackageDB_ALPM9.get_db_names())'

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

['multilib', 'extra-testing', 'multilib-testing', 'core-testing', 'extra', 'kde-unstable', 'core']
$ python -c 'from pypyalpm import PackageDB_ALPM9 ; print(PackageDB_ALPM9.get_db_names())' --force-pacman-cli-db

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

 >>> User forced to use pacman output
 >>> Switching to pure pacman-only mode (pacman CLI output will be used instead of ALPM DB)...


['multilib', 'extra-testing', 'multilib-testing', 'core-testing', 'extra', 'kde-unstable', 'core']
```

**Comment by actionless** [comment]
```
$ pacman -Qi | grep 'Name.*python-markdown-it-py' -B 1 -A 20
$ pacman -Si | grep 'Name.*python-markdown-it-py' -B 1 -A 17
```

**Comment by actionless** [comment]
git pull origin master
and try -S/-Ss with `./pikaur_static.py` inside aforementioned `pikaur/pikaur_static/` directory

**Comment by actionless** [comment]
[pikaur-standalone.exe.zip](https://github.com/user-attachments/files/18158813/pikaur-standalone.exe.zip)

**Comment by actionless** [comment]
and after that please test normal, non-static pikaur-git, if argparser is working fine with 3.13

**Comment by siroccal** [comment]
> git pull origin master and try -S/-Ss with `./pikaur_static.py` inside aforementioned `pikaur/pikaur_static/` directory

`pikaur-static`:

```
$ cd Programs/pikaur/
$ git pull origin master
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 16 (delta 12), reused 16 (delta 12), pack-reused 0 (from 0)
Unpacking objects: 100% (16/16), 2.89 KiB | 986.00 KiB/s, done.
From https://github.com/actionless/pikaur
 * branch              master     -> FETCH_HEAD
   e3e01311..3e71191f  master     -> origin/master
Updating e3e01311..3e71191f
Fast-forward
 pikaur/alpm.py                   |   4 ++++
 pikaur/argparse_extras.py        | 121 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
 pikaur_static/pacman_fallback.py |  13 +++++++++++
 pikaur_static/pypyalpm.py        |   6 ++++-
 4 files changed, 113 insertions(+), 31 deletions(-)
$ cd pikaur_static/
$ ./pikaur-static.py -Ss python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

Searching... [=> GET https://aur.archlinux.org/rpc/?v=5&type=search&arg=python-markdown-it-py&by=name-desc
###
extra/python-markdown-it-py 3.0.0-2 
    Python port of markdown-it. Markdown parsing, done right!    
$ ./pikaur-static.py -S python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

=> sudo --preserve-env=EDITOR -- ./pikaur-static.py -S python-markdown-it-py --pikaur-config=/home/user/.config/pikaur.conf --user-id=1000 --home-dir=/home/user --xdg-cache-home=/home/user/.cache --xdg-config-home=/home/user/.config/ --xdg-data-home=/home/user/.local/share
[sudo] password for user: 

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync python-markdown-it-py --print-format %r/%n
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/main.py", line 537, in main
    cli_entry_point()
    ~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/main.py", line 363, in cli_entry_point
    execute_pikaur_operation(pikaur_operation=pikaur_operation, require_sudo=require_sudo)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/main.py", line 285, in execute_pikaur_operation
    pikaur_operation()
    ~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/main.py", line 175, in cli_install_packages
    InstallPackagesCLI()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_cli.py", line 238, in __init__
    self.main_sequence()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_cli.py", line 278, in main_sequence
    self.get_all_packages_info()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_cli.py", line 396, in get_all_packages_info
    self.install_info = InstallInfoFetcher(
                        ~~~~~~~~~~~~~~~~~~^
        install_package_names=self.install_package_names,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        skip_checkdeps_for_pkgnames=self.skip_checkfunc_for_pkgnames,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_info_fetcher.py", line 99, in __init__
    self.get_all_packages_info()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_info_fetcher.py", line 237, in get_all_packages_info
    self.get_repo_pkgs_info()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_info_fetcher.py", line 410, in get_repo_pkgs_info
    self._get_repo_pkgs_info(pkg_lines=self.install_package_names) +
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_info_fetcher.py", line 322, in _get_repo_pkgs_info
    return _get_pkg_install_infos(composed_result)
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_info_fetcher.py", line 290, in _get_pkg_install_infos
    pkg = all_repo_pkgs[pkg_print.full_name]
          ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^

KeyError: 'extra-testing/python-mdurl'
```

`pikaur-standalone.exe`:

```
$ ./pikaur-standalone.exe -Ss python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

Searching... [=> GET https://aur.archlinux.org/rpc/?v=5&type=search&arg=python-markdown-it-py&by=name-desc
###
extra/python-markdown-it-py 3.0.0-2 
    Python port of markdown-it. Markdown parsing, done right!    
$ ./pikaur-standalone.exe -S python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

=> sudo --preserve-env=EDITOR -- /home/user/Programs/pikaur-standalone.exe -S python-markdown-it-py --pikaur-config=/home/user/.config/pikaur.conf --user-id=1000 --home-dir=/home/user --xdg-cache-home=/home/user/.cache --xdg-config-home=/home/user/.config/ --xdg-data-home=/home/user/.local/share
[sudo] password for user: 

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync python-markdown-it-py --print-format %r/%n
  File "/tmp/onefile_4489_1734433718_227303/pikaur/main.py", line 537, in main
  File "/tmp/onefile_4489_1734433718_227303/pikaur/main.py", line 363, in cli_entry_point
  File "/tmp/onefile_4489_1734433718_227303/pikaur/main.py", line 285, in execute_pikaur_operation
  File "/tmp/onefile_4489_1734433718_227303/pikaur/main.py", line 175, in cli_install_packages
  File "/tmp/onefile_4489_1734433718_227303/pikaur/install_cli.py", line 238, in __init__
  File "/tmp/onefile_4489_1734433718_227303/pikaur/install_cli.py", line 278, in main_sequence
  File "/tmp/onefile_4489_1734433718_227303/pikaur/install_cli.py", line 396, in get_all_packages_info
  File "/tmp/onefile_4489_1734433718_227303/pikaur/install_info_fetcher.py", line 99, in __init__
  File "/tmp/onefile_4489_1734433718_227303/pikaur/install_info_fetcher.py", line 237, in get_all_packages_info
  File "/tmp/onefile_4489_1734433718_227303/pikaur/install_info_fetcher.py", line 410, in get_repo_pkgs_info
  File "/tmp/onefile_4489_1734433718_227303/pikaur/install_info_fetcher.py", line 322, in _get_repo_pkgs_info
  File "/tmp/onefile_4489_1734433718_227303/pikaur/install_info_fetcher.py", line 290, in _get_pkg_install_infos

KeyError: 'extra-testing/python-mdurl'
```

**Comment by actionless** [comment]
thanks, i'll keep looking into the testing repositories issues in fallback

and does the mainline pikaur-git works for you in 3.13 already?

**Comment by siroccal** [comment]
> and after that please test normal, non-static pikaur-git, if argparser is working fine with 3.13

> and does the mainline pikaur-git works for you in 3.13 already?

Yes, `pikaur-git` seems to work fine with python 3.13.

**Comment by actionless** [comment]
i've tried another fix for pikaurstatic, please try if it works now

**Comment by siroccal** [comment]
> i've tried another fix for pikaur-static, please try if it works now

```
$ git pull origin master
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 435 bytes | 435.00 KiB/s, done.
From https://github.com/actionless/pikaur
 * branch              master     -> FETCH_HEAD
   3e71191f..0b0bac47  master     -> origin/master
Updating 3e71191f..0b0bac47
Fast-forward
 pikaur_static/pypyalpm.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

```
$ cd pikaur_static/
$ ./pikaur-static.py -Ss python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

Searching... [=> GET https://aur.archlinux.org/rpc/?v=5&type=search&arg=python-markdown-it-py&by=name-desc
###
extra/python-markdown-it-py 3.0.0-2 [installed: 3.0.0-4] 
    Python port of markdown-it. Markdown parsing, done right!    
extra-testing/python-markdown-it-py 3.0.0-4 [installed] 
    Python port of markdown-it. Markdown parsing, done right!    
```

```
$ ./pikaur-static.py -S python-markdown-it-py

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

=> sudo --preserve-env=EDITOR -- ./pikaur-static.py -S python-markdown-it-py --pikaur-config=/home/user/.config/pikaur.conf --user-id=1000 --home-dir=/home/user --xdg-cache-home=/home/user/.cache --xdg-config-home=/home/user/.config/ --xdg-data-home=/home/user/.local/share
[sudo] password for user: 

 !!! Pikaur-static (Python-only ALPM DB reader) activated
     (consider using it only in recovery situations)

Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync python-markdown-it-py --print-format %r/%n
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/main.py", line 537, in main
    cli_entry_point()
    ~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/main.py", line 363, in cli_entry_point
    execute_pikaur_operation(pikaur_operation=pikaur_operation, require_sudo=require_sudo)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/main.py", line 285, in execute_pikaur_operation
    pikaur_operation()
    ~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/main.py", line 175, in cli_install_packages
    InstallPackagesCLI()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_cli.py", line 238, in __init__
    self.main_sequence()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_cli.py", line 282, in main_sequence
    self.install_prompt()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_cli.py", line 603, in install_prompt
    answer = _confirm_sysupgrade()
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_cli.py", line 565, in _confirm_sysupgrade
    _print_sysupgrade(verbose=verbose, required_by_installed=required_by_installed)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/install_cli.py", line 549, in _print_sysupgrade
    print_stdout(pretty_format_sysupgrade(
                 ~~~~~~~~~~~~~~~~~~~~~~~~^
        install_info=self.install_info,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        verbose=verbose,
        ^^^^^^^^^^^^^^^^
        required_by_installed=required_by_installed,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ))
    ^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/print_department.py", line 663, in pretty_format_sysupgrade
    return SysupgradePrettyFormatter(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...<3 lines>...
        manual_package_selection=manual_package_selection,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    )()
    ~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/print_department.py", line 649, in __call__
    self.pformat_repo()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/print_department.py", line 556, in pformat_repo
    self.result.append(self.pretty_format_upgradeable(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.repo_packages_updates,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ))
    ^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/print_department.py", line 476, in pretty_format_upgradeable
    return pretty_format_upgradeable(
        install_infos,
        verbose=self.verbose, required_by_installed=self.required_by_installed,
        color=self.color, print_repo=print_repo,
    )
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/print_department.py", line 399, in pretty_format_upgradeable
    pretty_format(pkg_update)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/Programs/pikaur/pikaur_static/pikaur/print_department.py", line 295, in pretty_format
    pkg_size = f"{pkg_update.package.size / 1024 / 1024:.2f} MiB"
                  ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~

TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by actionless** [comment]
apparently you're having non-default config, with `showdownloadsize = yes`, i'll look into it

**Comment by actionless** [comment]
please try again now

**Comment by siroccal** [comment]
> please try again now

Yes, works fine now.

**Comment by actionless** [comment]
thanks for testing 👍 i'll make a release soon before 3.13 hit non-testing repos
