### ISSUE TITLE
config read fails for non-UTF8 PKGBUILD

### ISSUE THREAD

**Issue by cg505** [actionless/pikaur#96]
The package [hexter](https://aur.archlinux.org/packages/hexter/) has a PKGBUILD that uses ISO-8859-1. pikaur assumes UTF8 which causes a crash:

```
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 249, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 200, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 68, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 124, in __init__
    self.build_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 601, in build_packages
    repo_status.build(self.args, self.package_builds_by_name)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 431, in build
    self._set_built_package_path()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 356, in _set_built_package_path
    config_path=os.path.join(self.build_dir, 'PKGBUILD')
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 140, in get
    value = ConfigReader.get(key, value, config_path=config_path)
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 119, in get
    return cls.get_config(config_path=config_path).get(key) or fallback
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 112, in get_config
    for line in config_file.readlines()
  File "/usr/lib/python3.6/codecs.py", line 708, in readlines
    return self.reader.readlines(sizehint)
  File "/usr/lib/python3.6/codecs.py", line 617, in readlines
    data = self.read()
  File "/usr/lib/python3.6/codecs.py", line 503, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 133: invalid start byte
```

**Comment by actionless** [comment]
thanks for reporting!
